--1.source sql
SELECT *
  FROM (select VID, VISIT_DATE
          from fact_page_view
         where visit_date_key = 20180101
           and page_name = 'TV_QRC') a
  LEFT JOIN (SELECT TV_START_TIME, TV_END_TIME, ITEM_CODE
               FROM DIM_TV_GOOD
              where TV_STARTDAY_KEY = 20180101) b
    on a.VISIT_DATE between b.TV_START_TIME and b.TV_END_TIME;

--2.
INSERT INTO FACT_TV_QRC
  (VID,
   VISIT_DATE_KEY,
   VISIT_DATE,
   TV_START_TIME,
   TV_END_TIME,
   ITEM_CODE,
   W_INSERT_DT,
   W_UPDATE_DT)
  SELECT DISTINCT A.VID,
                  TO_CHAR(A.VISIT_DATE, 'YYYYMMDD') VISIT_DATE_KEY,
                  A.VISIT_DATE,
                  B.TV_START_TIME,
                  B.TV_END_TIME,
                  B.ITEM_CODE,
                  SYSDATE W_INSERT_DT,
                  SYSDATE W_UPDATE_DT
    FROM (SELECT VID, VISIT_DATE
            FROM FACT_PAGE_VIEW
           WHERE VISIT_DATE_KEY = 20180101
             AND PAGE_NAME = 'TV_QRC') A
    LEFT JOIN (SELECT TV_START_TIME, TV_END_TIME, ITEM_CODE
                 FROM DIM_TV_GOOD
                WHERE TV_STARTDAY_KEY = 20180101) B
      ON A.VISIT_DATE BETWEEN B.TV_START_TIME AND B.TV_END_TIME;

SELECT * FROM S_PARAMETERS2 FOR UPDATE;

--history
DECLARE
  IN_DATE_INT NUMBER(8);
  IN_DATE     DATE;
  BEGIN_DATE  DATE := DATE '2017-01-01';
  END_DATE    DATE := DATE '2017-12-31';
  IS_EXISTS   INT := 0;
BEGIN
  IN_DATE := BEGIN_DATE;
  WHILE IN_DATE <= END_DATE LOOP
    IN_DATE_INT := TO_CHAR(IN_DATE, 'YYYYMMDD');
    SELECT COUNT(1)
      INTO IS_EXISTS
      FROM FACT_TV_QRC A
     WHERE A.VISIT_DATE_KEY = IN_DATE_INT;
    IF IS_EXISTS = 0
    THEN
      YANGJIN_PKG.FACT_TV_QRC_PROC(IN_DATE_INT);
    END IF;
    IN_DATE := IN_DATE + 1;
  END LOOP;
END;
/

  SELECT *
    FROM W_ETL_LOG A
   WHERE A.PROC_NAME = 'YANGJIN_PKG.FACT_TV_QRC_PROC'
   ORDER BY A.START_TIME DESC;
	 
SELECT A.VISIT_DATE_KEY, COUNT(1)
  FROM FACT_TV_QRC A
 GROUP BY A.VISIT_DATE_KEY
 ORDER BY A.VISIT_DATE_KEY DESC;
