--2016年到2017 年  物料大类  品牌   订购件数   订购金额的表
SELECT D.MATDL,
       D.MATDLT,
       D.BRAND_NAME,
       SUM(C.NUMS) ORDER_QTY,
       SUM(C.ORDER_AMOUNT) ORDER_AMOUNT,
       DECODE(SUM(C.NUMS), 0, 0, SUM(C.ORDER_AMOUNT) / SUM(C.NUMS)) UNIT_PRICE
  FROM (SELECT A.GOODS_COMMON_KEY, A.UNIT_PRICE, A.ORDER_AMOUNT, A.NUMS
          FROM FACT_GOODS_SALES A
         WHERE A.POSTING_DATE_KEY BETWEEN 20160101 AND 20170719
           AND A.ORDER_STATE = 1) C,
       (SELECT DISTINCT B.GOODS_COMMONID,
                        B.ITEM_CODE,
                        B.MATDL,
                        B.MATDLT,
                        NVL(B.BRAND_NAME, '无品牌') BRAND_NAME
          FROM DIM_GOOD B) D
 WHERE C.GOODS_COMMON_KEY = D.ITEM_CODE
 GROUP BY D.MATDL, D.MATDLT, D.BRAND_NAME
 ORDER BY D.MATDL,D.BRAND_NAME;

--TMP

