--1.*************************************************************************************
SELECT /*+PARALLEL(16)*/
 COUNT(1)
  FROM ODSHAPPIGO.ODS_ORDER A
 WHERE A.CRMPOSTDAT = 20171201;
SELECT /*+PARALLEL(16)*/
 COUNT(1)
  FROM ODSHAPPIGO.ODS_ORDER A
 WHERE A.CRMPOSTDAT = 20171202;
SELECT /*+PARALLEL(16)*/
 COUNT(1)
  FROM ODSHAPPIGO.ODS_ORDER A
 WHERE A.CRMPOSTDAT = 20171203;

--2.*************************************************************************************
BEGIN
  -- CALL THE PROCEDURE
  YANGJIN_PKG.FACT_GOODS_SALES_FIX(20171201);
END;
/
BEGIN
  -- CALL THE PROCEDURE
  YANGJIN_PKG.FACT_GOODS_SALES_FIX(20171202);
END;
/
BEGIN
  -- CALL THE PROCEDURE
  YANGJIN_PKG.FACT_GOODS_SALES_FIX(20171203);
END;
/

--3.*************************************************************************************
BEGIN
  -- CALL THE PROCEDURE
  HAPPIGO_EC_PKG.MERGE_EC_TOP_LEVEL;
END;
/

--4.*************************************************************************************
BEGIN
  -- CALL THE PROCEDURE
  MEMBER_LABEL_PKG.ML_DATE_FIX(20171201);
END;
/
BEGIN
  -- CALL THE PROCEDURE
  MEMBER_LABEL_PKG.ML_DATE_FIX(20171202);
END;
/
BEGIN
  -- CALL THE PROCEDURE
  MEMBER_LABEL_PKG.ML_DATE_FIX(20171203);
END;
/

--5.*************************************************************************************
BEGIN
  -- CALL THE PROCEDURE
  MEMBER_SMS_PKG.MEMBER_SMS_DATE_FIX(20171201);
END;
/
BEGIN
  -- CALL THE PROCEDURE
  MEMBER_SMS_PKG.MEMBER_SMS_DATE_FIX(20171202);
END;
/
BEGIN
  -- CALL THE PROCEDURE
  MEMBER_SMS_PKG.MEMBER_SMS_DATE_FIX(20171203);
END;
/

--6.*************************************************************************************
BEGIN
  -- CALL THE PROCEDURE
  YANGJIN_PKG.YANGJIN_PKG_DATE_FIX(20171201);
END;
/
BEGIN
  -- CALL THE PROCEDURE
  YANGJIN_PKG.YANGJIN_PKG_DATE_FIX(20171202);
END;
/
BEGIN
  -- CALL THE PROCEDURE
  YANGJIN_PKG.YANGJIN_PKG_DATE_FIX(20171203);
END;
/

--7.10.10.204.18*************************************************************************************
BEGIN
  -- CALL THE PROCEDURE
  OPER_MEMBER_LIKE_PKG.OPER_MEMBER_LIKE_BASE_PROC(20171201);
  OPER_MEMBER_LIKE_PKG.OPER_MEMBER_LIKE_ITEM_PROC(20171201);
	OPER_MEMBER_LIKE_PKG.OPER_MEMBER_LIKE_MATXL_PROC(20171201);
	OPER_MEMBER_MARKETING_PKG.PROC_MBR_REG_WITHOUT_ORDER(20171201);
	OPER_MEMBER_MARKETING_PKG.PROC_MBR_FIRST_ORDER_15DAYS(20171201);
	OPER_MEMBER_MARKETING_PKG.PROC_MBR_SECOND_ORDER_20DAYS(20171201);
	OPER_MEMBER_MARKETING_PKG.PROC_MBR_THIRD_ORDER_30DAYS(20171201);
	OPER_MEMBER_MARKETING_PKG.PROC_MBR_ORDER_RETAIN_PUSH(20171201);
	OPER_MEMBER_MARKETING_PKG.PROC_MBR_THIRD_ORDER_MONTH(201711);
END;
/
BEGIN
  -- CALL THE PROCEDURE
  OPER_MEMBER_LIKE_PKG.OPER_MEMBER_LIKE_BASE_PROC(20171202);
  OPER_MEMBER_LIKE_PKG.OPER_MEMBER_LIKE_ITEM_PROC(20171202);
	OPER_MEMBER_LIKE_PKG.OPER_MEMBER_LIKE_MATXL_PROC(20171202);
	OPER_MEMBER_MARKETING_PKG.PROC_MBR_REG_WITHOUT_ORDER(20171202);
	OPER_MEMBER_MARKETING_PKG.PROC_MBR_FIRST_ORDER_15DAYS(20171202);
	OPER_MEMBER_MARKETING_PKG.PROC_MBR_SECOND_ORDER_20DAYS(20171202);
	OPER_MEMBER_MARKETING_PKG.PROC_MBR_THIRD_ORDER_30DAYS(20171202);
	OPER_MEMBER_MARKETING_PKG.PROC_MBR_ORDER_RETAIN_PUSH(20171202);
END;
/
BEGIN
  -- CALL THE PROCEDURE
  OPER_MEMBER_LIKE_PKG.OPER_MEMBER_LIKE_BASE_PROC(20171203);
  OPER_MEMBER_LIKE_PKG.OPER_MEMBER_LIKE_ITEM_PROC(20171203);
	OPER_MEMBER_LIKE_PKG.OPER_MEMBER_LIKE_MATXL_PROC(20171203);
	OPER_MEMBER_MARKETING_PKG.PROC_MBR_REG_WITHOUT_ORDER(20171203);
	OPER_MEMBER_MARKETING_PKG.PROC_MBR_FIRST_ORDER_15DAYS(20171203);
	OPER_MEMBER_MARKETING_PKG.PROC_MBR_SECOND_ORDER_20DAYS(20171203);
	OPER_MEMBER_MARKETING_PKG.PROC_MBR_THIRD_ORDER_30DAYS(20171203);
	OPER_MEMBER_MARKETING_PKG.PROC_MBR_ORDER_RETAIN_PUSH(20171203);
END;
/

--8.10.10.204.18.ML*************************************************************************************
BEGIN
  -- CALL THE PROCEDURE
	MEMBER_FILTER_PKG.SYNC_MEMBER_LABEL_HEAD(20171201);
	MEMBER_FILTER_PKG.SYNC_MEMBER_LABEL_LINK(20171201);
END;
/
BEGIN
  -- CALL THE PROCEDURE
	MEMBER_FILTER_PKG.SYNC_MEMBER_LABEL_HEAD(20171202);
	MEMBER_FILTER_PKG.SYNC_MEMBER_LABEL_LINK(20171202);
END;
/
BEGIN
  -- CALL THE PROCEDURE
	MEMBER_FILTER_PKG.SYNC_MEMBER_LABEL_HEAD(20171203);
	MEMBER_FILTER_PKG.SYNC_MEMBER_LABEL_LINK(20171203);
END;
/
