--1.create table
--CREATE TABLE DIM_MEMBER_ZONE AS
SELECT A.MEMBER_BP, B.ZONE, B.VTEXT1, B.VTEXT2, B.VTEXT3, B.VTEXT4
  FROM DIM_MEMBER A, DIM_ZONE B
 WHERE A.MEMBER_ZONE = B.ZONE;

--2.merge
MERGE /*+APPEND*/
INTO DIM_MEMBER_ZONE T
USING (SELECT A.MEMBER_BP, B.ZONE, B.VTEXT1, B.VTEXT2, B.VTEXT3, B.VTEXT4
         FROM DIM_MEMBER A, DIM_ZONE B
        WHERE A.MEMBER_ZONE = B.ZONE
             /*分二种情况：1、member_zone已经变更，2、新增BP号*/
          AND (EXISTS (SELECT 1
                         FROM DIM_MEMBER_ZONE C
                        WHERE A.MEMBER_BP = C.MEMBER_BP
                          AND A.MEMBER_ZONE <> C.ZONE) OR NOT EXISTS
               (SELECT 1
                  FROM DIM_MEMBER_ZONE D
                 WHERE A.MEMBER_BP = D.MEMBER_BP))) S
ON (T.MEMBER_BP = S.MEMBER_BP)
WHEN MATCHED THEN
  UPDATE
     SET T.ZONE   = S.ZONE,
         T.VTEXT1 = S.VTEXT1,
         T.VTEXT2 = S.VTEXT2,
         T.VTEXT3 = S.VTEXT3,
         T.VTEXT4 = S.VTEXT4
WHEN NOT MATCHED THEN
  INSERT
    (T.MEMBER_BP, T.ZONE, T.VTEXT1, T.VTEXT2, T.VTEXT3, T.VTEXT4)
  VALUES
    (S.MEMBER_BP, S.ZONE, S.VTEXT1, S.VTEXT2, S.VTEXT3, S.VTEXT4);

--tmp
SELECT A.MEMBER_BP, COUNT(1)
  FROM DIM_MEMBER_ZONE A
 GROUP BY A.MEMBER_BP
HAVING COUNT(1) > 1;
SELECT * from s_parameters2 for update;
