--1.
CREATE TABLE MEMBER_TMP_YANGJIN 
(MEMBER_KEY NUMBER(20));

CREATE TABLE MEMBER_TMP_YANGJIN1 
(MEMBER_KEY NUMBER(20));

CREATE TABLE MEMBER_TMP_YANGJIN2 
(MEMBER_KEY NUMBER(20));

CREATE TABLE MEMBER_TMP_YANGJIN3 
(MEMBER_KEY NUMBER(20));

SELECT * FROM MEMBER_TMP_YANGJIN3 FOR UPDATE;

drop table MEMBER_TMP_YANGJIN;
drop table MEMBER_TMP_YANGJIN1;
drop table MEMBER_TMP_YANGJIN2;
drop table MEMBER_TMP_YANGJIN3;

--2.
--访问回应率：7812/25536
SELECT COUNT(DISTINCT T.MEMBER_KEY)
  FROM FACT_PAGE_VIEW T
 WHERE T.VISIT_DATE_KEY BETWEEN 20170616 AND 20170618
   AND EXISTS
 (SELECT 1 FROM MEMBER_TMP_YANGJIN S WHERE T.MEMBER_KEY = S.MEMBER_KEY);

SELECT COUNT(1) FROM MEMBER_TMP_YANGJIN;

SELECT 7812/25536 FROM DUAL;

--3.订购回应率
SELECT COUNT(B.MEMBER_KEY) MEMBER_COUNT, SUM(B.ORDER_AMOUNT) ORDER_AMOUNT
  FROM (SELECT A.MEMBER_KEY,
               COUNT(A.ORDER_OBJ_ID) ORDER_COUNT,
               SUM(A.ORDER_AMOUNT) ORDER_AMOUNT
          FROM (SELECT T.POSTING_DATE_KEY,
                       T.ORDER_OBJ_ID,
                       T.MEMBER_KEY,
                       T.ORDER_AMOUNT
                  FROM FACT_ORDER T
                 WHERE T.POSTING_DATE_KEY BETWEEN 20170619 AND 20170622 /*过账日期*/
                   AND T.SALES_SOURCE_KEY = 20 /*新媒体通路*/
                   AND T.ORDER_STATE = 1
                   AND EXISTS
                 (SELECT 1
                          FROM MEMBER_TMP_YANGJIN3 C
                         WHERE T.MEMBER_KEY = C.MEMBER_KEY)) A
         GROUP BY A.MEMBER_KEY) B;

SELECT COUNT(B.MEMBER_KEY) MEMBER_COUNT, SUM(B.ORDER_AMOUNT) ORDER_AMOUNT
  FROM (SELECT A.MEMBER_KEY,
               COUNT(A.ORDER_OBJ_ID) ORDER_COUNT,
               SUM(A.ORDER_AMOUNT) ORDER_AMOUNT
          FROM (SELECT T.POSTING_DATE_KEY,
                       T.ORDER_OBJ_ID,
                       T.MEMBER_KEY,
                       T.ORDER_AMOUNT
                  FROM FACT_ORDER T
                 WHERE T.POSTING_DATE_KEY = 20170618 /*过账日期*/
                   AND T.SALES_SOURCE_KEY = 20 /*新媒体通路*/
                   AND T.ORDER_STATE = 1
                   AND EXISTS
                 (SELECT 1
                          FROM MEMBER_TMP_YANGJIN3 C
                         WHERE T.MEMBER_KEY = C.MEMBER_KEY)) A
         GROUP BY A.MEMBER_KEY) B;

--4.

--5.

--6.
