--OPER_PRODUCT_DAILY_PREVIEW历史数据补全，从2017.1.1开始
DECLARE
  IN_DATE_INT NUMBER(8);
  IN_DATE     DATE;
  BEGIN_DATE  DATE := DATE '2017-01-01';
  END_DATE    DATE := DATE '2018-01-22';
BEGIN
  IN_DATE := BEGIN_DATE;
  WHILE IN_DATE <= END_DATE LOOP
    IN_DATE_INT := TO_CHAR(IN_DATE, 'YYYYMMDD');
    YANGJIN_PKG.OPER_PRODUCT_DAILY_PREVIEW(IN_DATE_INT);
    IN_DATE := IN_DATE + 1;
  END LOOP;
END;
/

--TMP
  SELECT DISTINCT A.POSTING_DATE_KEY
    FROM OPER_PRODUCT_DAILY_PREVIEW A
   ORDER BY A.POSTING_DATE_KEY DESC;

SELECT * FROM W_ETL_LOG A WHERE A.PROC_NAME='YANGJIN_PKG.OPER_PRODUCT_DAILY_PREVIEW' ORDER BY A.START_TIME DESC;

SELECT A.POSTING_DATE_KEY, A.ITEM_CODE, COUNT(1)
  FROM OPER_PRODUCT_DAILY_PREVIEW A
 GROUP BY A.POSTING_DATE_KEY, A.ITEM_CODE
HAVING COUNT(1) > 1;
