MERGE INTO SAP_BIC_AZTCRD00100 T
USING (SELECT *
         FROM SAP_BIC_AZTCRD00100_MODIFY_TP
        WHERE CRMPOSTDAT >= '20130101'
           OR "/BIC/ZTCMC021" >= '20130101') P
ON (T.CRM_OBJ_ID = P.CRM_OBJ_ID AND T.CRM_NUMINT = P.CRM_NUMINT)
WHEN MATCHED THEN
  UPDATE
     SET T.RECORDMODE       = P.RECORDMODE,
         T."/BIC/ZEAMC008"  = P."/BIC/ZEAMC008",
         T.CRM_OHGUID       = P.CRM_OHGUID,
         T.CRM_ITMGUI       = P.CRM_ITMGUI,
         T.CRM_PRCTYP       = P.CRM_PRCTYP,
         T."/BIC/ZCRMD023"  = P."/BIC/ZCRMD023",
         T.CRM_ITMTYP       = P.CRM_ITMTYP,
         T."/BIC/ZTCMC002"  = P."/BIC/ZTCMC002",
         T."/BIC/ZTCMC006"  = P."/BIC/ZTCMC006",
         T.SALESORG         = P.SALESORG,
         T.DISTR_CHAN       = P.DISTR_CHAN,
         T.SALES_OFF        = P.SALES_OFF,
         T.DIVISION         = P.DIVISION,
         T."/BIC/ZMATERIAL" = P."/BIC/ZMATERIAL",
         T."/BIC/ZEAMC027"  = P."/BIC/ZEAMC027",
         T."/BIC/ZLIFNR"    = P."/BIC/ZLIFNR",
         T.CRM_ENDCST       = P.CRM_ENDCST,
         T."/BIC/ZTCMC016"  = P."/BIC/ZTCMC016",
         T.AGE              = P.AGE,
         T."/BIC/ZTCMC020"  = P."/BIC/ZTCMC020",
         T.CRM_SOLDTO       = P.CRM_SOLDTO,
         T."/BIC/ZKUNNR_L1" = P."/BIC/ZKUNNR_L1",
         T."/BIC/ZKUNNR_L2" = P."/BIC/ZKUNNR_L2",
         T."/BIC/ZTHRC015"  = P."/BIC/ZTHRC015",
         T.BP_EMPLO         = P.BP_EMPLO,
         T."/BIC/ZTHRC016"  = P."/BIC/ZTHRC016",
         T."/BIC/ZTHRC017"  = P."/BIC/ZTHRC017",
         T."/BIC/ZESDC113"  = P."/BIC/ZESDC113",
         T.CRMPOSTDAT       = P.CRMPOSTDAT,
         T."/BIC/ZPST_TIM"  = P."/BIC/ZPST_TIM",
         T."/BIC/ZGZ_TIME"  = P."/BIC/ZGZ_TIME",
         T."/BIC/ZCRMD001"  = P."/BIC/ZCRMD001",
         T.CRM_USSTAT       = P.CRM_USSTAT,
         T.CRM_STSMA        = P.CRM_STSMA,
         T.CRM_CTD_BY       = P.CRM_CTD_BY,
         T.CRM_CRD_AT       = P.CRM_CRD_AT,
         T.CREA_TIME        = P.CREA_TIME,
         T."/BIC/ZEAMC001"  = P."/BIC/ZEAMC001",
         T."/BIC/ZEAMC010"  = P."/BIC/ZEAMC010",
         T."/BIC/ZEAMC011"  = P."/BIC/ZEAMC011",
         T."/BIC/ZEAMC012"  = P."/BIC/ZEAMC012",
         T."/BIC/ZEAMC037"  = P."/BIC/ZEAMC037",
         T."/BIC/ZEAMC013"  = P."/BIC/ZEAMC013",
         T."/BIC/ZEAMC014"  = P."/BIC/ZEAMC014",
         T."/BIC/ZTCMC021"  = P."/BIC/ZTCMC021",
         T."/BIC/ZTCMC022"  = P."/BIC/ZTCMC022",
         T."/BIC/ZTCMC027"  = P."/BIC/ZTCMC027",
         T."/BIC/ZTCMC026"  = P."/BIC/ZTCMC026",
         T."/BIC/ZTCMC030"  = P."/BIC/ZTCMC030",
         T."/BIC/ZTCMC007"  = P."/BIC/ZTCMC007",
         T."/BIC/ZTCMC008"  = P."/BIC/ZTCMC008",
         T."/BIC/ZTCMC009"  = P."/BIC/ZTCMC009",
         T."/BIC/ZTCMC023"  = P."/BIC/ZTCMC023",
         T."/BIC/ZTCMC024"  = P."/BIC/ZTCMC024",
         T."/BIC/ZTCMC025"  = P."/BIC/ZTCMC025",
         T."/BIC/ZCRMD015"  = P."/BIC/ZCRMD015",
         T."/BIC/ZCRMD016"  = P."/BIC/ZCRMD016",
         T."/BIC/ZCRMD017"  = P."/BIC/ZCRMD017",
         T."/BIC/ZCRMD018"  = P."/BIC/ZCRMD018",
         T."/BIC/ZCR_ON"    = P."/BIC/ZCR_ON",
         T."/BIC/ZOBJ_CC"   = P."/BIC/ZOBJ_CC",
         T."/BIC/ZDSXD"     = P."/BIC/ZDSXD",
         T."/BIC/ZJSJF_YN"  = P."/BIC/ZJSJF_YN",
         T."/BIC/ZCRMD025"  = P."/BIC/ZCRMD025",
         T."/BIC/ZCRMD020"  = P."/BIC/ZCRMD020",
         T."/BIC/ZCRMD021"  = P."/BIC/ZCRMD021",
         T."/BIC/ZTCRMC01"  = P."/BIC/ZTCRMC01",
         T."/BIC/ZTCRMC02"  = P."/BIC/ZTCRMC02",
         T."/BIC/ZTCRMC03"  = P."/BIC/ZTCRMC03",
         T."/BIC/ZTCRMC04"  = P."/BIC/ZTCRMC04",
         T."/BIC/ZTCRMC05"  = P."/BIC/ZTCRMC05",
         T.UNIT             = P.UNIT,
         T.NETVALORD        = P.NETVALORD,
         T.CRM_TAXAMO       = P.CRM_TAXAMO,
         T.GRSVALORD        = P.GRSVALORD,
         T."/BIC/ZAMK0011"  = P."/BIC/ZAMK0011",
         T."/BIC/ZAMK0010"  = P."/BIC/ZAMK0010",
         T."/BIC/ZCRMK006"  = P."/BIC/ZCRMK006",
         T."/BIC/ZCRMK007"  = P."/BIC/ZCRMK007",
         T."/BIC/ZCRMK009"  = P."/BIC/ZCRMK009",
         T.CRM_SRVKB        = P.CRM_SRVKB,
         T."/BIC/ZCRMK003"  = P."/BIC/ZCRMK003",
         T."/BIC/ZCRMK004"  = P."/BIC/ZCRMK004",
         T."/BIC/ZCRMK005"  = P."/BIC/ZCRMK005",
         T."/BIC/ZYF_PAY"   = P."/BIC/ZYF_PAY",
         T."/BIC/ZXY_PAY"   = P."/BIC/ZXY_PAY",
         T."/BIC/ZNPT_ATM"  = P."/BIC/ZNPT_ATM",
         T.CRM_NUMOFI       = P.CRM_NUMOFI,
         T."/BIC/ZAMK0024"  = P."/BIC/ZAMK0024",
         T."/BIC/ZCRMK008"  = P."/BIC/ZCRMK008",
         T.SALES_UNIT       = P.SALES_UNIT,
         T.CURRENCY         = P.CURRENCY,
         T.CRM_CURREN       = P.CRM_CURREN,
         T."/BIC/ZCRMD031"  = P."/BIC/ZCRMD031",
         T."/BIC/ZEHRC012"  = P."/BIC/ZEHRC012",
         T."/BIC/ZCRMD048"  = P."/BIC/ZCRMD048",
         T."/BIC/ZCRMD086"  = P."/BIC/ZCRMD086",
         T."/BIC/ZCRMD019"  = P."/BIC/ZCRMD019",
         T."/BIC/ZTHRC027"  = P."/BIC/ZTHRC027",
         T."/BIC/ZTHRC026"  = P."/BIC/ZTHRC026",
         T."/BIC/ZTHRC025"  = P."/BIC/ZTHRC025",
         T."/BIC/ZTCRMC11"  = P."/BIC/ZTCRMC11",
         T."/BIC/ZCRMD199"  = P."/BIC/ZCRMD199",
         T."/BIC/ZTLEC001"  = P."/BIC/ZTLEC001",
         T."/BIC/ZCONDK001" = P."/BIC/ZCONDK001",
         T."/BIC/ZCRMD120"  = P."/BIC/ZCRMD120",
         T.CHANGED_BY       = P.CHANGED_BY,
         T."/BIC/ZMATER2"   = P."/BIC/ZMATER2",
         T."/BIC/ZZTRANSF"  = P."/BIC/ZZTRANSF",
         T."/BIC/ZTMSTAMP"  = P."/BIC/ZTMSTAMP"
WHEN NOT MATCHED THEN
  INSERT
  VALUES
    (P.CRM_OBJ_ID,
     P.CRM_NUMINT,
     P.RECORDMODE,
     P."/BIC/ZEAMC008",
     P.CRM_OHGUID,
     P.CRM_ITMGUI,
     P.CRM_PRCTYP,
     P."/BIC/ZCRMD023",
     P.CRM_ITMTYP,
     P."/BIC/ZTCMC002",
     P."/BIC/ZTCMC006",
     P.SALESORG,
     P.DISTR_CHAN,
     P.SALES_OFF,
     P.DIVISION,
     P."/BIC/ZMATERIAL",
     P."/BIC/ZEAMC027",
     P."/BIC/ZLIFNR",
     P.CRM_ENDCST,
     P."/BIC/ZTCMC016",
     P.AGE,
     P."/BIC/ZTCMC020",
     P.CRM_SOLDTO,
     P."/BIC/ZKUNNR_L1",
     P."/BIC/ZKUNNR_L2",
     P."/BIC/ZTHRC015",
     P.BP_EMPLO,
     P."/BIC/ZTHRC016",
     P."/BIC/ZTHRC017",
     P."/BIC/ZESDC113",
     P.CRMPOSTDAT,
     P."/BIC/ZPST_TIM",
     P."/BIC/ZGZ_TIME",
     P."/BIC/ZCRMD001",
     P.CRM_USSTAT,
     P.CRM_STSMA,
     P.CRM_CTD_BY,
     P.CRM_CRD_AT,
     P.CREA_TIME,
     P."/BIC/ZEAMC001",
     P."/BIC/ZEAMC010",
     P."/BIC/ZEAMC011",
     P."/BIC/ZEAMC012",
     P."/BIC/ZEAMC037",
     P."/BIC/ZEAMC013",
     P."/BIC/ZEAMC014",
     P."/BIC/ZTCMC021",
     P."/BIC/ZTCMC022",
     P."/BIC/ZTCMC027",
     P."/BIC/ZTCMC026",
     P."/BIC/ZTCMC030",
     P."/BIC/ZTCMC007",
     P."/BIC/ZTCMC008",
     P."/BIC/ZTCMC009",
     P."/BIC/ZTCMC023",
     P."/BIC/ZTCMC024",
     P."/BIC/ZTCMC025",
     P."/BIC/ZCRMD015",
     P."/BIC/ZCRMD016",
     P."/BIC/ZCRMD017",
     P."/BIC/ZCRMD018",
     P."/BIC/ZCR_ON",
     P."/BIC/ZOBJ_CC",
     P."/BIC/ZDSXD",
     P."/BIC/ZJSJF_YN",
     P."/BIC/ZCRMD025",
     P."/BIC/ZCRMD020",
     P."/BIC/ZCRMD021",
     P."/BIC/ZTCRMC01",
     P."/BIC/ZTCRMC02",
     P."/BIC/ZTCRMC03",
     P."/BIC/ZTCRMC04",
     P."/BIC/ZTCRMC05",
     P.UNIT,
     P.NETVALORD,
     P.CRM_TAXAMO,
     P.GRSVALORD,
     P."/BIC/ZAMK0011",
     P."/BIC/ZAMK0010",
     P."/BIC/ZCRMK006",
     P."/BIC/ZCRMK007",
     P."/BIC/ZCRMK009",
     P.CRM_SRVKB,
     P."/BIC/ZCRMK003",
     P."/BIC/ZCRMK004",
     P."/BIC/ZCRMK005",
     P."/BIC/ZYF_PAY",
     P."/BIC/ZXY_PAY",
     P."/BIC/ZNPT_ATM",
     P.CRM_NUMOFI,
     P."/BIC/ZAMK0024",
     P."/BIC/ZCRMK008",
     P.SALES_UNIT,
     P.CURRENCY,
     P.CRM_CURREN,
     P."/BIC/ZCRMD031",
     P."/BIC/ZEHRC012",
     P."/BIC/ZCRMD048",
     P."/BIC/ZCRMD086",
     P."/BIC/ZCRMD019",
     P."/BIC/ZTHRC027",
     P."/BIC/ZTHRC026",
     P."/BIC/ZTHRC025",
     P."/BIC/ZTCRMC11",
     P."/BIC/ZCRMD199",
     P."/BIC/ZTLEC001",
     P."/BIC/ZCONDK001",
     P."/BIC/ZCRMD120",
     P.CHANGED_BY,
     P."/BIC/ZMATER2",
     P."/BIC/ZZTRANSF",
     P."/BIC/ZTMSTAMP")
