--用户调取条件：4-7月购物车有过数码电器(40)、保健用品(53)、母婴用品(54)、家居厨房(45)记录的用户；
--tmp table 
DROP TABLE JIN_TMP;
CREATE TABLE JIN_TMP AS
SELECT A.MEMBER_KEY, A.SCGID
  FROM FACT_SHOPPINGCAR A
 WHERE A.CREATE_DATE_KEY BETWEEN 20170401 AND 20170731
   AND A.MEMBER_KEY <> 0;
	 
--	 
SELECT DISTINCT A.MEMBER_KEY
  FROM JIN_TMP A
 WHERE EXISTS (SELECT 1
          FROM (SELECT C.ITEM_CODE
                  FROM DIM_GOOD C
                 WHERE C.MATDL IN (40, 45, 53, 54)
                   AND C.CURRENT_FLG = 'Y') B
         WHERE A.SCGID = B.ITEM_CODE)
 ORDER BY 1;

--TMP
SELECT DISTINCT A.MATDL,A.MATDLT,A.MATZL,A.MATZLT,A.MATXL,A.MATXLT
FROM DIM_GOOD A
ORDER BY 1,3,5;

SELECT DISTINCT A.MATDL,A.MATDLT,A.MATZL,A.MATZLT,A.MATXL,A.MATXLT
FROM DIM_MATERCATE A
WHERE A.MATZLT LIKE '%家居%'
ORDER BY 1,3,5;

SELECT A.MEMBER_KEY, A.SCGID
  FROM FACT_SHOPPINGCAR A
 WHERE A.CREATE_DATE_KEY BETWEEN 20170401 AND 20170731
   AND A.MEMBER_KEY <> 0;
