--1.
/*
字段名          含义       类型    描述
user_id         用户编号   string  购物的用户ID
item_id         物品编号   string  被购买物品的编号
active_type     购物行为   string  0表示点击，1表示购买，2表示收藏，3表示购物车
active_date     购物时间   string  购物发生的时间
*/
INSERT INTO CR_DATA_BASE
  (USER_ID, ITEM_ID, ACTIVE_TYPE, ACTIVE_DATE)
--active_type=0
  SELECT DISTINCT TO_CHAR(A1.MEMBER_KEY) USER_ID,
                  TO_CHAR(A1.PAGE_VALUE) AS ITEM_ID,
                  0 ACTIVE_TYPE,
                  TO_CHAR(A1.VISIT_DATE_KEY) ACTIVE_DATE
    FROM FACT_PAGE_VIEW A1
   WHERE A1.PAGE_KEY IN
         (1924, 2303, 2841, 2842, 11586, 24146, 38629, 40899, 40903)
     AND REGEXP_LIKE(A1.PAGE_VALUE, '^[1-9]\d{5}$')
     AND A1.VISIT_DATE_KEY = 20180205
     AND A1.MEMBER_KEY <> 0
  UNION ALL
  --active_type=1
  SELECT TO_CHAR(A2.MEMBER_KEY) USER_ID,
         TO_CHAR(A2.GOODS_COMMON_KEY) ITEM_ID,
         1 ACTIVE_TYPE,
         TO_CHAR(A2.POSTING_DATE_KEY) ACTIVE_DATE
    FROM FACT_GOODS_SALES A2
   WHERE A2.POSTING_DATE_KEY = 20180205
  UNION ALL
  --active_type=2
  SELECT (SELECT TO_CHAR(MAX(B3.MEMBER_CRMBP))
            FROM FACT_ECMEMBER B3
           WHERE A3.MEMBER_ID = B3.MEMBER_ID) USER_ID,
         TO_CHAR(A3.FAV_ID) ITEM_ID,
         2 ACTIVE_TYPE,
         TO_CHAR(A3.FAV_TIME) ACTIVE_DATE
    FROM FACT_FAVORITES A3
   WHERE A3.FAV_TYPE = 'goods'
     AND A3.FAV_TIME = 20180205
  UNION ALL
  --active_type=3
  SELECT TO_CHAR(A4.MEMBER_KEY) USER_ID,
         TO_CHAR(A4.SCGID) ITEM_ID,
         3 ACTIVE_TYPE,
         TO_CHAR(A4.CREATE_DATE_KEY) ACTIVE_DATE
    FROM FACT_SHOPPINGCAR A4
   WHERE A4.PAGE_KEY IN (297, 11586)
     AND A4.CREATE_DATE_KEY = 20180205
     AND A4.MEMBER_KEY <> 0;

--2.
DECLARE
  IN_DATE_INT NUMBER(8);
  IN_DATE     DATE;
  BEGIN_DATE  DATE := DATE '2018-01-01';
  END_DATE    DATE := DATE '2018-05-31';
BEGIN
  IN_DATE := BEGIN_DATE;
  WHILE IN_DATE <= END_DATE LOOP
    IN_DATE_INT := TO_CHAR(IN_DATE, 'YYYYMMDD');
    YANGJIN_PKG.CR_DATA_BASE_PROC(IN_DATE_INT); 
    IN_DATE := IN_DATE + 1;
  END LOOP;
END;
/

--3.
CREATE TABLE ALIYUN_CR_DATA_TRAIN AS
SELECT *
  FROM CR_DATA_BASE A
 WHERE A.ACTIVE_DATE BETWEEN 20170101 AND 20171231;
 
TRUNCATE TABLE ALIYUN_CR_DATA_TRAIN;
INSERT INTO ALIYUN_CR_DATA_TRAIN
  SELECT *
    FROM CR_DATA_BASE A
   WHERE A.ACTIVE_DATE BETWEEN 20180101 AND 20180531;
COMMIT;


CREATE TABLE ALIYUN_CR_DATA_VALIDATION AS
SELECT *
  FROM CR_DATA_BASE A
 WHERE A.ACTIVE_DATE BETWEEN 20180101 AND 20180131;

TRUNCATE TABLE ALIYUN_CR_DATA_VALIDATION;
INSERT INTO ALIYUN_CR_DATA_VALIDATION
  SELECT *
    FROM CR_DATA_BASE A
   WHERE A.ACTIVE_DATE BETWEEN 20180101 AND 20180131;
COMMIT;

--4.

--tmp.
SELECT * FROM S_PARAMETERS2 FOR UPDATE;
SELECT A4.MEMBER_KEY      USER_ID,
       A4.SCGID           ITEM_ID,
       3                  active_type,
       A4.CREATE_DATE_KEY ACTIVE_DATE
  FROM FACT_SHOPPINGCAR A4
 WHERE A4.PAGE_KEY IN (297, 11586)
   AND A4.CREATE_DATE_KEY = 20180205
   AND A4.MEMBER_KEY <> 0;
SELECT DISTINCT A4.PAGE_KEY, A4.PAGE_NAME
  FROM FACT_SHOPPINGCAR A4
 WHERE A4.SCGID <> 0
 ORDER BY 1, 2;
SELECT * FROM FACT_SHOPPINGCAR A4 WHERE A4.PAGE_KEY = 11586;
SELECT (SELECT MAX(B3.MEMBER_CRMBP)
          FROM FACT_ECMEMBER B3
         WHERE A3.MEMBER_ID = B3.MEMBER_ID) USER_ID,
       A3.FAV_ID ITEM_ID,
       2 active_type,
       A3.FAV_TIME ACTIVE_DATE
  FROM FACT_FAVORITES A3
 WHERE A3.FAV_TYPE = 'goods'
   AND A3.FAV_TIME = 20180205;

SELECT A.MEMBER_ID, COUNT(1)
  FROM FACT_ECMEMBER A
 GROUP BY A.MEMBER_ID
HAVING COUNT(1) > 1;
SELECT * FROM FACT_ECMEMBER A WHERE A.MEMBER_ID = 1651819;
SELECT *
  FROM ALL_SOURCE A
 WHERE UPPER(A.TEXT) LIKE '%INSERT%FACT_FAVORITES%';
SELECT *
  FROM ALL_ALL_TABLES A
 WHERE A.table_name LIKE '%MEMBER%'
 ORDER BY A.owner, A.table_name;
SELECT * FROM FACT_ECMEMBER;
