--1.W_ETL_LOG check
SELECT *
  FROM W_ETL_LOG T
 WHERE TRUNC(T.START_TIME) >= TRUNC(SYSDATE) - 1
   AND (T.ETL_STATUS <> 'SUCCESS' OR T.ETL_STATUS IS NULL)
 ORDER BY T.START_TIME DESC;

SELECT *
  FROM W_ETL_LOG@BITONEWBI T
 WHERE TRUNC(T.START_TIME) >= TRUNC(SYSDATE) - 1
   AND (T.ETL_STATUS <> 'SUCCESS' OR T.ETL_STATUS IS NULL)
 ORDER BY T.START_TIME DESC;

--2.
--2.1
SELECT T.START_TIME,
       T.END_TIME,
       T.PROC_NAME,
       T.TABLE_NAME,
       T.ETL_STATUS,
       T.ETL_DURATION,
       T.ETL_RECORD_INS,
       T.ETL_RECORD_UPD,
       T.ERR_MSG
  FROM W_ETL_LOG T
 WHERE T.PROC_NAME LIKE 'YANGJIN_PKG%'
    OR T.PROC_NAME LIKE 'MEMBER%'
 ORDER BY T.START_TIME DESC;
--2.2
SELECT T.START_TIME,
       T.END_TIME,
       T.PROC_NAME,
       T.TABLE_NAME,
       T.ETL_STATUS,
       T.ETL_DURATION,
       T.ETL_RECORD_INS,
       T.ETL_RECORD_UPD,
       T.ERR_MSG
  FROM W_ETL_LOG@BITONEWBI T
 WHERE T.PROC_NAME LIKE 'OPER_MEMBER%'
 ORDER BY T.START_TIME DESC;

--2.3
SELECT * FROM FACT_GOODS_SALES A WHERE A.POSTING_DATE_KEY = TO_CHAR(TRUNC(SYSDATE)-1,'YYYYMMDD');
SELECT *
  FROM FACT_GOODS_SALES_REVERSE A
 WHERE A.POSTING_DATE_KEY = TO_CHAR(TRUNC(SYSDATE)-1,'YYYYMMDD');
SELECT * FROM FACT_ORDER A WHERE A.POSTING_DATE_KEY = TO_CHAR(TRUNC(SYSDATE)-1,'YYYYMMDD');
SELECT /*+PARALLEL(16)*/
 *
  FROM ODSHAPPIGO.ODS_ORDER A
 WHERE A.CRMPOSTDAT = 20170814;

--2.4.商品资料缺失
SELECT DISTINCT A.GOODS_KEY FROM OPER_PRODUCT_DAILY_REPORT A WHERE A.POSTING_DATE_KEY=TO_CHAR(TRUNC(SYSDATE)-1,'YYYYMMDD') AND A.GOODS_NAME IS NULL;
SELECT *
  from dim_good a
 where a.item_code in
       (218041, 224133, 224297, 224339, 224665, 224686, 224979);
SELECT *
  from ods_zmaterial a
 where a.zmater2 in (218041, 224133, 224297, 224339, 224665, 224686, 224979)
   and a.zmaterial not like '%F%'
   and a.ZEAMC027 is not null
   and a.zeamc027 != 0;
	 
--3.
--3.1.YANGJIN_PKG.PROCESSMAKETHMSC_IA
SELECT *
  FROM W_ETL_LOG T
 WHERE T.PROC_NAME = 'YANGJIN_PKG.PROCESSMAKETHMSC_IA'
 ORDER BY T.START_TIME DESC;

--3.2.YANGJIN_PKG.OPER_PRODUCT_DAILY_RPT
SELECT *
  FROM W_ETL_LOG T
 WHERE T.PROC_NAME = 'YANGJIN_PKG.OPER_PRODUCT_DAILY_RPT'
 ORDER BY T.START_TIME DESC;

--3.3.YANGJIN_PKG.OPER_PRODUCT_PVUV_DAILY_RPT
SELECT *
  FROM W_ETL_LOG T
 WHERE T.PROC_NAME = 'YANGJIN_PKG.OPER_PRODUCT_PVUV_DAILY_RPT'
 ORDER BY T.START_TIME DESC;

--3.4.YANGJIN_PKG.OPER_PRODUCT_PVUV_DAILY_RPT
SELECT *
  FROM W_ETL_LOG T
 WHERE T.PROC_NAME = 'YANGJIN_PKG.OPER_MEMBER_MBLEVEL_DCGOOD'
 ORDER BY T.START_TIME DESC;


--3.4.YANGJIN_PKG.DIM_GOOD_FIX
SELECT *
  FROM W_ETL_LOG T
 WHERE T.PROC_NAME = 'YANGJIN_PKG.DIM_GOOD_FIX'
 ORDER BY T.START_TIME DESC;

--4.正逆向订单
SELECT *
  FROM W_ETL_LOG T
 WHERE T.PROC_NAME IN ('createfactordergoodsreverse',
                       'createordergoods',
                       'processupdateorder',
                       'processupdateorderreverse')
 ORDER BY T.START_TIME DESC;

--5.
--检查ODS_ORDER是否重复
SELECT /*+PARALLEL(16)*/
 A.CRM_OBJ_ID,
 A.CRM_NUMINT,
 A.ZEAMC008,
 A.CRM_OHGUID,
 A.CRM_ITMGUI,
 A.CRM_PRCTYP,
 A.ZCRMD023,
 A.CRM_ITMTYP,
 A.ZTCMC002,
 A.ZTCMC006,
 A.SALESORG,
 A.DISTR_CHAN,
 A.SALES_OFF,
 A.DIVISION,
 A.ZMATERIAL,
 A.ZEAMC027,
 A.ZLIFNR,
 A.CRM_ENDCST,
 A.ZTCMC016,
 A.AGE,
 A.ZTCMC020,
 A.CRM_SOLDTO,
 A.ZKUNNR_L1,
 A.ZKUNNR_L2,
 A.ZTHRC015,
 A.BP_EMPLO,
 A.ZTHRC016,
 A.ZTHRC017,
 A.ZESDC113,
 A.CRMPOSTDAT,
 A.ZPST_TIM,
 A.ZGZ_TIME,
 A.ZCRMD001,
 A.CRM_USSTAT,
 A.CRM_STSMA,
 A.CRM_CTD_BY,
 A.CRM_CRD_AT,
 A.CREA_TIME,
 A.ZEAMC001,
 A.ZEAMC010,
 A.ZEAMC011,
 A.ZEAMC012,
 A.ZEAMC037,
 A.ZEAMC013,
 A.ZEAMC014,
 A.ZTCMC021,
 A.ZTCMC022,
 A.ZTCMC027,
 A.ZTCMC026,
 A.ZTCMC030,
 A.ZTCMC007,
 A.ZTCMC008,
 A.ZTCMC009,
 A.ZTCMC023,
 A.ZTCMC024,
 A.ZTCMC025,
 A.ZCRMD015,
 A.ZCRMD016,
 A.ZCRMD017,
 A.ZCRMD018,
 A.ZCR_ON,
 A.ZOBJ_CC,
 A.ZDSXD,
 A.ZJSJF_YN,
 A.ZCRMD025,
 A.ZCRMD020,
 A.ZCRMD021,
 A.ZTCRMC01,
 A.ZTCRMC02,
 A.ZTCRMC03,
 A.ZTCRMC04,
 A.ZTCRMC05,
 A.NETVALORD,
 A.CRM_TAXAMO,
 A.GRSVALORD,
 A.ZAMK0011,
 A.ZAMK0010,
 A.ZCRMK006,
 A.ZCRMK007,
 A.ZCRMK009,
 A.CRM_SRVKB,
 A.ZCRMK003,
 A.ZCRMK004,
 A.ZCRMK005,
 A.ZYF_PAY,
 A.ZXY_PAY,
 A.ZNPT_ATM,
 A.CRM_NUMOFI,
 A.ZAMK0024,
 A.ZCRMK008,
 A.SALES_UNIT,
 A.CURRENCY,
 A.CRM_CURREN,
 A.ZCRMD031,
 A.ZEHRC012,
 A.ZCRMD048,
 A.ZCRMD086,
 A.ZCRMD019,
 A.ZTHRC027,
 A.ZTHRC026,
 A.ZTHRC025,
 A.ZTCRMC11,
 A.ZCRMD199,
 A.ZTLEC001,
 A.ZCONDK001,
 A.ZCRMD120,
 A.CHANGED_BY,
 A.ZMATER2,
 A.ZZTRANSF,
 A.ZTMSTAMP,
 COUNT(1)
  FROM ODSHAPPIGO.ODS_ORDER A
 WHERE A.CRMPOSTDAT = TO_CHAR(TRUNC(SYSDATE - 1), 'YYYYMMDD')
 GROUP BY A.CRM_OBJ_ID,
          A.CRM_NUMINT,
          A.ZEAMC008,
          A.CRM_OHGUID,
          A.CRM_ITMGUI,
          A.CRM_PRCTYP,
          A.ZCRMD023,
          A.CRM_ITMTYP,
          A.ZTCMC002,
          A.ZTCMC006,
          A.SALESORG,
          A.DISTR_CHAN,
          A.SALES_OFF,
          A.DIVISION,
          A.ZMATERIAL,
          A.ZEAMC027,
          A.ZLIFNR,
          A.CRM_ENDCST,
          A.ZTCMC016,
          A.AGE,
          A.ZTCMC020,
          A.CRM_SOLDTO,
          A.ZKUNNR_L1,
          A.ZKUNNR_L2,
          A.ZTHRC015,
          A.BP_EMPLO,
          A.ZTHRC016,
          A.ZTHRC017,
          A.ZESDC113,
          A.CRMPOSTDAT,
          A.ZPST_TIM,
          A.ZGZ_TIME,
          A.ZCRMD001,
          A.CRM_USSTAT,
          A.CRM_STSMA,
          A.CRM_CTD_BY,
          A.CRM_CRD_AT,
          A.CREA_TIME,
          A.ZEAMC001,
          A.ZEAMC010,
          A.ZEAMC011,
          A.ZEAMC012,
          A.ZEAMC037,
          A.ZEAMC013,
          A.ZEAMC014,
          A.ZTCMC021,
          A.ZTCMC022,
          A.ZTCMC027,
          A.ZTCMC026,
          A.ZTCMC030,
          A.ZTCMC007,
          A.ZTCMC008,
          A.ZTCMC009,
          A.ZTCMC023,
          A.ZTCMC024,
          A.ZTCMC025,
          A.ZCRMD015,
          A.ZCRMD016,
          A.ZCRMD017,
          A.ZCRMD018,
          A.ZCR_ON,
          A.ZOBJ_CC,
          A.ZDSXD,
          A.ZJSJF_YN,
          A.ZCRMD025,
          A.ZCRMD020,
          A.ZCRMD021,
          A.ZTCRMC01,
          A.ZTCRMC02,
          A.ZTCRMC03,
          A.ZTCRMC04,
          A.ZTCRMC05,
          A.NETVALORD,
          A.CRM_TAXAMO,
          A.GRSVALORD,
          A.ZAMK0011,
          A.ZAMK0010,
          A.ZCRMK006,
          A.ZCRMK007,
          A.ZCRMK009,
          A.CRM_SRVKB,
          A.ZCRMK003,
          A.ZCRMK004,
          A.ZCRMK005,
          A.ZYF_PAY,
          A.ZXY_PAY,
          A.ZNPT_ATM,
          A.CRM_NUMOFI,
          A.ZAMK0024,
          A.ZCRMK008,
          A.SALES_UNIT,
          A.CURRENCY,
          A.CRM_CURREN,
          A.ZCRMD031,
          A.ZEHRC012,
          A.ZCRMD048,
          A.ZCRMD086,
          A.ZCRMD019,
          A.ZTHRC027,
          A.ZTHRC026,
          A.ZTHRC025,
          A.ZTCRMC11,
          A.ZCRMD199,
          A.ZTLEC001,
          A.ZCONDK001,
          A.ZCRMD120,
          A.CHANGED_BY,
          A.ZMATER2,
          A.ZZTRANSF,
          A.ZTMSTAMP
HAVING COUNT(1) > 1;
