--W_ETL_LOG check
SELECT *
  FROM W_ETL_LOG T
 WHERE TRUNC(T.START_TIME) = TRUNC(SYSDATE) - 1
   AND T.ETL_STATUS <> 'SUCCESS';
	 
--YANGJIN_PKG.PROCESSMAKETHMSC_IA
SELECT *
  FROM W_ETL_LOG T
 WHERE T.PROC_NAME = 'YANGJIN_PKG.PROCESSMAKETHMSC_IA'
 ORDER BY T.START_TIME DESC;

--YANGJIN_PKG.OPER_PRODUCT_DAILY_RPT
SELECT *
  FROM W_ETL_LOG T
 WHERE T.PROC_NAME = 'YANGJIN_PKG.OPER_PRODUCT_DAILY_RPT'
 ORDER BY T.START_TIME DESC;
 
--YANGJIN_PKG.OPER_PRODUCT_PVUV_DAILY_RPT
SELECT *
  FROM W_ETL_LOG T
 WHERE T.PROC_NAME = 'YANGJIN_PKG.OPER_PRODUCT_PVUV_DAILY_RPT'
 ORDER BY T.START_TIME DESC;

SELECT *
  FROM W_ETL_LOG T
 WHERE T.PROC_NAME LIKE 'YANGJIN_PKG%'
 ORDER BY T.START_TIME DESC;
