--1.uv
DROP TABLE YANGJIN.GOODUV_201805231;
CREATE TABLE YANGJIN.GOODUV_201805231 AS
SELECT DISTINCT A.VISIT_DATE_KEY, A.PAGE_VALUE ITEM_CODE, A.VID
  FROM FACT_PAGE_VIEW A
 WHERE A.VISIT_DATE_KEY BETWEEN 20180101 AND 20180331
   AND A.PAGE_KEY IN (1924, 2841)
   AND A.PAGE_VALUE =
       TRANSLATE(A.PAGE_VALUE,
                 '0' || TRANSLATE(A.PAGE_VALUE, '#0123456789', '#'),
                 '0');

SELECT '2018Q1' QUARTER, D.GC_NAME, ROUND(AVG(VID_COUNT)) AVG_VID_COUNT
  FROM (SELECT A.VISIT_DATE_KEY, C.GC_NAME, COUNT(DISTINCT A.VID) VID_COUNT
          FROM YANGJIN.GOODUV_201805231 A, DIM_GOOD B, DIM_GOOD_CLASS C
         WHERE A.ITEM_CODE = B.ITEM_CODE
           AND B.MATDL = C.MATDL
         GROUP BY A.VISIT_DATE_KEY, C.GC_NAME) D
 GROUP BY D.GC_NAME;

--2.¶©¹ºÈËÊý
SELECT '2018Q1' QUARTER, F.GC_NAME, ROUND(AVG(F.VID_COUNT)) AVG_VID_COUNT
  FROM (SELECT C.ORDER_DATE, E.GC_NAME, COUNT(DISTINCT C.VID) VID_COUNT
          FROM (SELECT DISTINCT TO_CHAR(TRUNC(A.ADD_TIME), 'YYYYMMDD') ORDER_DATE,
                                B.GOODS_COMMONID,
                                A.VID
                  FROM FACT_EC_ORDER_2 A, FACT_EC_ORDER_GOODS B
                 WHERE A.ORDER_ID = B.ORDER_ID
                   AND A.ORDER_STATE >= 20
                   AND TRUNC(A.ADD_TIME) BETWEEN DATE
                 '2018-01-01'
                   AND DATE '2018-03-31'
                   AND B.ERP_CODE <> 0) C,
               DIM_GOOD D,
               DIM_GOOD_CLASS E
         WHERE C.GOODS_COMMONID = D.GOODS_COMMONID
           AND D.MATDL = E.MATDL
         GROUP BY C.ORDER_DATE, E.GC_NAME) F
 GROUP BY F.GC_NAME;

--tmp
SELECT DISTINCT A.GC_ID, A.GC_NAME FROM DIM_GOOD_CLASS A;
SELECT * FROM DIM_GOOD_CLASS;
SELECT * FROM DIM_GOOD;
SELECT * FROM DIM_EC_GOOD;
SELECT * FROM FACT_EC_ORDER_GOODS;
SELECT * FROM FACT_EC_ORDER_2;
