--1.
/*
SNAME:VID
S1:活跃天数
S2:1
S3:生命周期
S4:1
*/
SELECT * FROM LS_TEST1 T;

--2.临时表
DROP TABLE YANGJIN.APP_LIFE_CYCLE_TMP;
CREATE TABLE YANGJIN.APP_LIFE_CYCLE_TMP AS
  SELECT '20180620-20180820' PERIOD,
         A.VID,
         ACTIVE_DAYS,
         (CASE
           WHEN LAST_ACTIVE_DATE - REG_DATE >= 365 THEN
            '7'
           WHEN LAST_ACTIVE_DATE - REG_DATE >= 185 THEN
            '6'
           WHEN LAST_ACTIVE_DATE - REG_DATE >= 92 THEN
            '5'
           WHEN LAST_ACTIVE_DATE - REG_DATE >= 31 THEN
            '4'
           WHEN LAST_ACTIVE_DATE - REG_DATE >= 7 THEN
            '3'
           WHEN LAST_ACTIVE_DATE - REG_DATE >= 1 THEN
            '2'
           ELSE
            '1'
         END) LIFE_CYCLE_TYPE
    FROM (SELECT VID, COUNT(DISTINCT START_DATE_KEY) ACTIVE_DAYS
            FROM FACT_SESSION
           WHERE START_DATE_KEY BETWEEN 20180620 AND 20180820
             AND APPLICATION_KEY IN (10, 20)
           GROUP BY VID) A
    JOIN (SELECT VID, CREATE_DATE REG_DATE
            FROM FACT_VISITOR_REGISTER
           WHERE APPLICATION_KEY IN (10, 20)) B
      ON A.VID = B.VID
    JOIN (SELECT VID, MAX(START_TIME) LAST_ACTIVE_DATE
            FROM FACT_SESSION
           WHERE START_DATE_KEY BETWEEN 20180620 AND 20180820
             AND APPLICATION_KEY IN (10, 20)
           GROUP BY VID) C
      ON A.VID = C.VID;

INSERT INTO YANGJIN.APP_LIFE_CYCLE_TMP
  (PERIOD, VID, ACTIVE_DAYS, LIFE_CYCLE_TYPE)
  SELECT '20170620-20170820' PERIOD,
         A.VID,
         ACTIVE_DAYS,
         (CASE
           WHEN LAST_ACTIVE_DATE - REG_DATE >= 365 THEN
            '7'
           WHEN LAST_ACTIVE_DATE - REG_DATE >= 185 THEN
            '6'
           WHEN LAST_ACTIVE_DATE - REG_DATE >= 92 THEN
            '5'
           WHEN LAST_ACTIVE_DATE - REG_DATE >= 31 THEN
            '4'
           WHEN LAST_ACTIVE_DATE - REG_DATE >= 7 THEN
            '3'
           WHEN LAST_ACTIVE_DATE - REG_DATE >= 1 THEN
            '2'
           ELSE
            '1'
         END) LIFE_CYCLE_TYPE
    FROM (SELECT VID, COUNT(DISTINCT START_DATE_KEY) ACTIVE_DAYS
            FROM FACT_SESSION
           WHERE START_DATE_KEY BETWEEN 20170620 AND 20170820
             AND APPLICATION_KEY IN (10, 20)
           GROUP BY VID) A
    JOIN (SELECT VID, CREATE_DATE REG_DATE
            FROM FACT_VISITOR_REGISTER
           WHERE APPLICATION_KEY IN (10, 20)) B
      ON A.VID = B.VID
    JOIN (SELECT VID, MAX(START_TIME) LAST_ACTIVE_DATE
            FROM FACT_SESSION
           WHERE START_DATE_KEY BETWEEN 20170620 AND 20170820
             AND APPLICATION_KEY IN (10, 20)
           GROUP BY VID) C
      ON A.VID = C.VID;

TRUNCATE TABLE YANGJIN.APP_LIFE_CYCLE_TMP;

--3.订购金额 订购人数  订购单数 订购件数 
SELECT B.LIFE_CYCLE_TYPE,
       COUNT(1) VID_CNT,
       SUM(ORDER_CNT) ORDER_CNT,
       SUM(ORDER_QTY) ORDER_QTY,
       SUM(ORDER_AMOUNT) ORDER_AMOUNT,
       SUM(GOODS_AMOUNT) GOODS_AMOUNT
  FROM (SELECT VID,
               COUNT(1) ORDER_CNT,
               SUM(GOODS_NUM) ORDER_QTY,
               SUM(ORDER_AMOUNT) ORDER_AMOUNT,
               SUM(GOODS_AMOUNT) GOODS_AMOUNT
          FROM FACTEC_ORDER
         WHERE ADD_TIME BETWEEN 20180620 AND 20180820
           AND ORDER_STATE > 10
         GROUP BY VID) A
  JOIN (SELECT C.VID, C.LIFE_CYCLE_TYPE FROM YANGJIN.APP_LIFE_CYCLE_TMP C) B
    ON A.VID = B.VID
 GROUP BY B.LIFE_CYCLE_TYPE;

--4.页面访问
SELECT A.PAGE_NAME,
       B.LIFE_CYCLE_TYPE,
       SUM(PV) PV,
       COUNT(DISTINCT A.VID) VID_CNT
  FROM (SELECT PAGE_NAME, VID, COUNT(1) AS PV
          FROM FACT_PAGE_VIEW
         WHERE VISIT_DATE_KEY BETWEEN 20180501 AND 20180531
           AND APPLICATION_KEY IN (10, 20)
         GROUP BY PAGE_NAME, VID) A
  JOIN (SELECT C.VID, C.LIFE_CYCLE_TYPE FROM YANGJIN.APP_LIFE_CYCLE_TMP C) B
    ON A.VID = B.VID
 GROUP BY A.PAGE_NAME, B.LIFE_CYCLE_TYPE;

--5.物料大类
SELECT B.LIFE_CYCLE_TYPE,
       C.MATDLT,
       SUM(GOODS_NUM) ORDER_QTY,
       COUNT(DISTINCT A.VID) VID_CNT
  FROM (SELECT VID, ITEM_CODE, SS.GOODS_NUM
          FROM FACTEC_ORDER S
          JOIN FACTEC_ORDER_GOODS SS
            ON S.ORDER_ID = SS.ORDER_ID
         WHERE ADD_TIME BETWEEN 20180501 AND 20180531
           AND ORDER_STATE > 10
           AND GOODS_TYPE IN (1, 3)
           AND ITEM_CODE < 300000
           AND GOODS_PAY_PRICE >= 50
         GROUP BY VID, ITEM_CODE, SS.GOODS_NUM) A
  JOIN (SELECT D.VID, D.LIFE_CYCLE_TYPE FROM YANGJIN.APP_LIFE_CYCLE_TMP D) B
    ON A.VID = B.VID
  JOIN (SELECT GROUP_NAME, MATDLT, GOODS_NAME, ITEM_CODE FROM DIM_GOOD) C
    ON A.ITEM_CODE = C.ITEM_CODE
 GROUP BY B.LIFE_CYCLE_TYPE, C.MATDLT;

--6.商品浏览
SELECT C.MATDLT,
       B.LIFE_CYCLE_TYPE,
       SUM(A.PV) PV,
       COUNT(DISTINCT A.VID) VID_CNT
  FROM (SELECT PAGE_NAME, VID, PAGE_VALUE, COUNT(1) AS PV
          FROM FACT_PAGE_VIEW
         WHERE VISIT_DATE_KEY BETWEEN 20180501 AND 20180531
           AND APPLICATION_KEY IN (10, 20)
           AND PAGE_NAME = 'Good'
         GROUP BY PAGE_NAME, VID, PAGE_VALUE) A
  JOIN (SELECT D.VID, D.LIFE_CYCLE_TYPE FROM YANGJIN.APP_LIFE_CYCLE_TMP D) B
    ON A.VID = B.VID
  JOIN (SELECT TO_CHAR(GOODS_COMMONID) GOODS_COMMONID, MATDLT
          FROM DIM_EC_GOOD
         WHERE STORE_ID = 1) C
    ON A.PAGE_VALUE = C.GOODS_COMMONID
 GROUP BY C.MATDLT, B.LIFE_CYCLE_TYPE;

--7.APP会员生命周期
DROP TABLE YANGJIN.APP_LEFT_CYCLE_TMP1;
CREATE TABLE YANGJIN.APP_LEFT_CYCLE_TMP1 AS
  SELECT B.PERIOD, /*日期范围*/
         CASE
           WHEN B.LIFE_CYCLE_TYPE = 1 THEN
            '1天'
           WHEN B.LIFE_CYCLE_TYPE = 2 THEN
            '一周以内'
           WHEN B.LIFE_CYCLE_TYPE = 3 THEN
            '1周~1个月'
           WHEN B.LIFE_CYCLE_TYPE = 4 THEN
            '1~3个月'
           WHEN B.LIFE_CYCLE_TYPE = 5 THEN
            '4~6个月'
           WHEN B.LIFE_CYCLE_TYPE = 6 THEN
            '7~12个月'
           WHEN B.LIFE_CYCLE_TYPE = 7 THEN
            '12个月以上'
         END LIFT_CYCLE_DESC, /*生命周期阶段*/
         COUNT(B.VID) VID_CNT, /*活跃人数*/
         AVG(B.ACTIVE_DAYS) ACTIVE_DAYS, /*活跃天数*/
         COUNT(A.VID_ORDER) VID_ORDER_CNT, /*订购率*/
         SUM(ORDER_CNT) ORDER_CNT, /*订单数*/
         SUM(ORDER_QTY) ORDER_QTY, /*订购件数*/
         SUM(ORDER_AMOUNT) ORDER_AMOUNT /*订购金额*/
    FROM (SELECT VID VID_ORDER,
                 COUNT(1) ORDER_CNT,
                 SUM(GOODS_NUM) ORDER_QTY,
                 SUM(ORDER_AMOUNT) ORDER_AMOUNT
            FROM FACTEC_ORDER
           WHERE ADD_TIME BETWEEN 20180620 AND 20180820
             AND ORDER_STATE > 10
           GROUP BY VID) A,
         (SELECT C.PERIOD, C.VID, C.LIFE_CYCLE_TYPE, C.ACTIVE_DAYS
            FROM YANGJIN.APP_LIFE_CYCLE_TMP C
           WHERE C.PERIOD = '20180620-20180820') B
   WHERE A.VID_ORDER(+) = B.VID
   GROUP BY B.PERIOD, B.LIFE_CYCLE_TYPE
   ORDER BY B.LIFE_CYCLE_TYPE;

INSERT INTO YANGJIN.APP_LEFT_CYCLE_TMP1
  (PERIOD,
   LIFT_CYCLE_DESC,
   VID_CNT,
   ACTIVE_DAYS,
   VID_ORDER_CNT,
   ORDER_CNT,
   ORDER_QTY,
   ORDER_AMOUNT)
  SELECT B.PERIOD, /*日期范围*/
         CASE
           WHEN B.LIFE_CYCLE_TYPE = 1 THEN
            '1天'
           WHEN B.LIFE_CYCLE_TYPE = 2 THEN
            '一周以内'
           WHEN B.LIFE_CYCLE_TYPE = 3 THEN
            '1周~1个月'
           WHEN B.LIFE_CYCLE_TYPE = 4 THEN
            '1~3个月'
           WHEN B.LIFE_CYCLE_TYPE = 5 THEN
            '4~6个月'
           WHEN B.LIFE_CYCLE_TYPE = 6 THEN
            '7~12个月'
           WHEN B.LIFE_CYCLE_TYPE = 7 THEN
            '12个月以上'
         END LIFT_CYCLE_DESC, /*生命周期阶段*/
         COUNT(B.VID) VID_CNT, /*活跃人数*/
         AVG(B.ACTIVE_DAYS) ACTIVE_DAYS, /*活跃天数*/
         COUNT(A.VID_ORDER) VID_ORDER_CNT, /*订购率*/
         SUM(ORDER_CNT) ORDER_CNT, /*订单数*/
         SUM(ORDER_QTY) ORDER_QTY, /*订购件数*/
         SUM(ORDER_AMOUNT) ORDER_AMOUNT /*订购金额*/
    FROM (SELECT VID VID_ORDER,
                 COUNT(1) ORDER_CNT,
                 SUM(GOODS_NUM) ORDER_QTY,
                 SUM(ORDER_AMOUNT) ORDER_AMOUNT
            FROM FACTEC_ORDER
           WHERE ADD_TIME BETWEEN 20170620 AND 20170820
             AND ORDER_STATE > 10
           GROUP BY VID) A,
         (SELECT C.PERIOD, C.VID, C.LIFE_CYCLE_TYPE, C.ACTIVE_DAYS
            FROM YANGJIN.APP_LIFE_CYCLE_TMP C
           WHERE C.PERIOD = '20170620-20170820') B
   WHERE A.VID_ORDER(+) = B.VID
   GROUP BY B.PERIOD, B.LIFE_CYCLE_TYPE
   ORDER BY B.LIFE_CYCLE_TYPE;

--同比
CREATE TABLE APP_MEMBER_LIFE_CYCLE_REPORT AS
  SELECT A.PERIOD,
         A.LIFT_CYCLE_DESC,
         A.VID_CNT,
         B.VID_CNT         LY_VID_CNT,
         A.ACTIVE_DAYS,
         B.ACTIVE_DAYS     LY_ACTIVE_DAYS,
         A.VID_ORDER_CNT,
         B.VID_ORDER_CNT   LY_VID_ORDER_CNT,
         A.ORDER_CNT,
         B.ORDER_CNT       LY_ORDER_CNT,
         A.ORDER_QTY,
         B.ORDER_QTY       LY_ORDER_QTY,
         A.ORDER_AMOUNT,
         B.ORDER_AMOUNT    LY_ORDER_AMOUNT
    FROM YANGJIN.APP_LEFT_CYCLE_TMP1 A, YANGJIN.APP_LEFT_CYCLE_TMP1 B
   WHERE A.PERIOD = '20180620-20180820'
     AND B.PERIOD = '20170620-20170820'
     AND A.LIFT_CYCLE_DESC = B.LIFT_CYCLE_DESC;

--访问率
SELECT B.LIFE_CYCLE_TYPE, SUM(PV) PV, COUNT(DISTINCT A.VID) VID_CNT
  FROM (SELECT PAGE_NAME, VID, COUNT(1) AS PV
          FROM FACT_PAGE_VIEW
         WHERE VISIT_DATE_KEY BETWEEN 20180620 AND 20180820
           AND APPLICATION_KEY IN (10, 20)
         GROUP BY PAGE_NAME, VID) A
  JOIN (SELECT C.VID, C.LIFE_CYCLE_TYPE
          FROM YANGJIN.APP_LIFE_CYCLE_TMP C
         WHERE C.PERIOD = '20180620-20180820') B
    ON A.VID = B.VID
 GROUP BY B.LIFE_CYCLE_TYPE;

--报表1
SELECT A.PERIOD 日期范围,
       A.LIFT_CYCLE_DESC 生命周期阶段,
       A.VID_CNT 活跃人数,
       A.LY_VID_CNT 去年活跃人数,
       A.ACTIVE_DAYS 活跃天数,
       A.LY_ACTIVE_DAYS 去年活跃天数,
       A.VID_ORDER_CNT / A.VID_CNT 转化率,
       A.LY_VID_ORDER_CNT / A.LY_VID_CNT 去年转化率,
       A.VID_ORDER_CNT 订购人数,
       A.LY_VID_ORDER_CNT 去年订购人数,
       A.ORDER_QTY 订购件数,
       A.LY_ORDER_QTY 去年订购件数,
       A.ORDER_AMOUNT 订购金额,
       A.LY_ORDER_AMOUNT 去年订购金额,
       A.ORDER_CNT / A.VID_ORDER_CNT 订购频次,
       A.LY_ORDER_CNT / A.LY_VID_ORDER_CNT 去年订购频次
  FROM APP_MEMBER_LIFE_CYCLE_REPORT A;

--APP订购喜好
SELECT B.PERIOD,
       CASE
         WHEN B.LIFE_CYCLE_TYPE = 1 THEN
          '1天'
         WHEN B.LIFE_CYCLE_TYPE = 2 THEN
          '一周以内'
         WHEN B.LIFE_CYCLE_TYPE = 3 THEN
          '1周~1个月'
         WHEN B.LIFE_CYCLE_TYPE = 4 THEN
          '1~3个月'
         WHEN B.LIFE_CYCLE_TYPE = 5 THEN
          '4~6个月'
         WHEN B.LIFE_CYCLE_TYPE = 6 THEN
          '7~12个月'
         WHEN B.LIFE_CYCLE_TYPE = 7 THEN
          '12个月以上'
       END LIFT_CYCLE_DESC, /*生命周期阶段*/
       C.MATDLT,
       SUM(GOODS_NUM) ORDER_QTY,
       COUNT(DISTINCT A.VID) VID_CNT
  FROM (SELECT VID, ITEM_CODE, SS.GOODS_NUM
          FROM FACTEC_ORDER S
          JOIN FACTEC_ORDER_GOODS SS
            ON S.ORDER_ID = SS.ORDER_ID
         WHERE ADD_TIME BETWEEN 20180620 AND 20180820
           AND ORDER_STATE > 10
           AND GOODS_TYPE IN (1, 3)
           AND ITEM_CODE < 300000
           AND GOODS_PAY_PRICE >= 50
         GROUP BY VID, ITEM_CODE, SS.GOODS_NUM) A,
       (SELECT D.PERIOD, D.VID, D.LIFE_CYCLE_TYPE
          FROM YANGJIN.APP_LIFE_CYCLE_TMP D
         WHERE D.PERIOD = '20180620-20180820') B,
       (SELECT GROUP_NAME, MATDLT, GOODS_NAME, ITEM_CODE FROM DIM_GOOD) C
 WHERE A.VID = B.VID
   AND A.ITEM_CODE = C.ITEM_CODE
 GROUP BY B.PERIOD, B.LIFE_CYCLE_TYPE, C.MATDLT
 ORDER BY B.PERIOD, B.LIFE_CYCLE_TYPE, C.MATDLT;
