/*
在其他渠道下单了但是没有在电商注册会员的每天发短信
*/

-- Create sequence 
create sequence OPER_MEMBER_NOT_IN_EC_SEQ
minvalue 1
maxvalue 9999999999999999999999999999
start with 0
increment by 1
cache 20;


CREATE TABLE OPER_MEMBER_NOT_IN_EC AS
SELECT DISTINCT A.POSTING_DATE_KEY, A.MEMBER_KEY
  FROM FACT_ORDER A
 WHERE A.POSTING_DATE_KEY = TO_CHAR(TRUNC(SYSDATE - 1), 'YYYYMMDD')
   AND A.SALES_SOURCE_KEY <> 20
   AND NOT EXISTS (SELECT 1
          FROM (SELECT C.MEMBER_CRMBP FROM FACT_ECMEMBER C) B
         WHERE A.MEMBER_KEY = B.MEMBER_CRMBP);

INSERT INTO OPER_MEMBER_NOT_IN_EC
SELECT DISTINCT A.POSTING_DATE_KEY, A.MEMBER_KEY
  FROM FACT_ORDER A
 WHERE A.POSTING_DATE_KEY = TO_CHAR(TRUNC(SYSDATE - 1), 'YYYYMMDD')
   AND A.SALES_SOURCE_KEY <> 20
   AND NOT EXISTS (SELECT 1
          FROM (SELECT C.MEMBER_CRMBP FROM FACT_ECMEMBER C) B
         WHERE A.MEMBER_KEY = B.MEMBER_CRMBP);
				 
--TMP
SELECT * FROM W_ETL_LOG A WHERE A.PROC_NAME='createordergoods' ORDER BY A.START_TIME DESC;				 
TRUNCATE TABLE OPER_MEMBER_NOT_IN_EC;
SELECT * FROM OPER_MEMBER_NOT_IN_EC;
