CREATE OR REPLACE PACKAGE YANGJIN_PKG_TEST IS

  -- AUTHOR  : YANGJIN
  -- CREATED : 2017-05-31 10:41:42
  -- PURPOSE : YANGJIN PACKAGE

  FUNCTION GET_IP_CITY(IN_IP_INT IN NUMBER) RETURN VARCHAR2;
  /*返回ip归属城市*/
  FUNCTION MEMBER_REPURCHASE_CYCLE_DAYS(IN_MEMBER_KEY IN NUMBER)
    RETURN NUMBER;
  /*
  函数名：      MEMBER_REPURCHASE_CYCLE_DAYS
  目的：        返回会员的复购周期（天数）
  创建时间：    2017/08/17
  作者:         yangjin
  创建时间：    2017/08/24
  最后修改人：
  最后更改日期：
  */

END YANGJIN_PKG_TEST;
/
CREATE OR REPLACE PACKAGE BODY YANGJIN_PKG_TEST IS

  FUNCTION GET_IP_CITY(IN_IP_INT IN NUMBER) RETURN VARCHAR2 IS
    RESULT_IP_CITY VARCHAR2(50);
  BEGIN
    SELECT /*+ INDEX(A,IP_START_IDX) */
     A.IP_CITY
      INTO RESULT_IP_CITY
      FROM DIM_IP_GEO A
     WHERE A.IP_START <= IN_IP_INT
       AND A.IP_END >= IN_IP_INT
       AND A.IP_CITY IS NOT NULL;
    RETURN(RESULT_IP_CITY);
  END GET_IP_CITY;

  FUNCTION MEMBER_REPURCHASE_CYCLE_DAYS(IN_MEMBER_KEY IN NUMBER)
    RETURN NUMBER IS
    RESULT_DAYS NUMBER;
    /*返回会员的复购周期（天数）*/
  BEGIN
    SELECT ROUND(NVL(SUM(C.POSTING_DATE - C.LAST_POSTING_DATE) /
                     COUNT(C.ORDER_KEY),
                     -1))
      INTO RESULT_DAYS
      FROM (SELECT B.MEMBER_KEY,
                   B.ORDER_KEY,
                   B.POSTING_DATE,
                   LAG(B.POSTING_DATE) OVER(PARTITION BY B.MEMBER_KEY ORDER BY B.POSTING_DATE) LAST_POSTING_DATE
              FROM (SELECT A.MEMBER_KEY,
                           TO_DATE(A.POSTING_DATE_KEY, 'yyyymmdd') POSTING_DATE,
                           A.ORDER_KEY
                      FROM MEMBER_LIFE_PERIOD_TMP_B A
                     WHERE A.ORDER_STATE = 1
                       AND A.MEMBER_KEY = IN_MEMBER_KEY
                          /*只取2016年之后的数据*/
                       AND A.POSTING_DATE_KEY >= 20160101) B) C
     WHERE C.LAST_POSTING_DATE IS NOT NULL;
    RETURN(RESULT_DAYS);
  END MEMBER_REPURCHASE_CYCLE_DAYS;

END YANGJIN_PKG_TEST;
/
