--1.
SELECT A.GEVAL_ID, COUNT(1)
  FROM FACT_GOODS_EVALUATE A
 GROUP BY A.GEVAL_ID
HAVING COUNT(1) > 1;
SELECT A.GEVAL_ADDTIME_KEY, COUNT(1)
  FROM FACT_GOODS_EVALUATE A
 GROUP BY A.GEVAL_ADDTIME_KEY;

SELECT * FROM EC_GOODS_EVALUATE_TMP;

SELECT COUNT(1) FROM EC_GOODS_EVALUATE_TMP;
SELECT * FROM FACT_GOODS_EVALUATE A WHERE A.GEVAL_ADDTIME_KEY=20180723;

SELECT *
  FROM FACT_GOODS_EVALUATE A
 WHERE A.GEVAL_ORDERNO <> 0
   AND A.GEVAL_ADDTIME_KEY = 20180723;
	 
SELECT * FROM DIM_GOOD A WHERE A.ITEM_CODE=131599;
SELECT * FROM DIM_GOOD A WHERE A.GOODS_COMMONID=131599;

SELECT * FROM FACT_EC_ORDER_GOODS A WHERE A.GOODS_ID=1370589;

CREATE TABLE YANGJIN.N_TEST(CA NUMBER(5, 30));

INSERT INTO YANGJIN.N_TEST VALUES (-0.39276797266285496);

SELECT * FROM S_PARAMETERS2 FOR UPDATE;

SELECT *
  FROM W_ETL_LOG A
 WHERE A.PROC_NAME = 'HAPPIGO_EC_PKG.MERGE_FACT_GOODS_EVALUATE'
 ORDER BY A.START_TIME DESC;

SELECT *
  FROM FACT_GOODS_EVALUATE A
 WHERE A.Geval_Sentiment_Polarity <> 0
 order by a.geval_addtime;
