--1.
SELECT A.GEVAL_ADDTIME_KEY,COUNT(1)
  FROM FACT_GOODS_EVALUATE A
 WHERE A.GEVAL_SENTIMENT_POLARITY <> 0
   AND A.GEVAL_SENTIMENT_POLARITY_IASPE IS NOT NULL
   AND A.GEVAL_SENTIMENT_POLARITY_IASPE LIKE '%}]'
   AND NOT EXISTS (SELECT 1
          FROM FACT_GOODS_EVALUATE_ASPECT B
         WHERE A.GEVAL_ID = B.GEVAL_ID)
				 GROUP BY A.GEVAL_ADDTIME_KEY;

SELECT COUNT(1) FROM FACT_GOODS_EVALUATE_ASPECT;

--2.
SELECT * FROM S_PARAMETERS2 FOR UPDATE;

--3.
SELECT *
  FROM W_ETL_LOG A
 WHERE A.PROC_NAME = 'GOODS_LABEL_PKG.GOODS_EVALUATE_ASPECT'
 ORDER BY A.START_TIME DESC;

--4.
TRUNCATE TABLE FACT_GOODS_EVALUATE_ASPECT;

--5.
drop sequence FACT_GOODS_EVALUATE_ASPECT_SEQ;
create sequence FACT_GOODS_EVALUATE_ASPECT_SEQ
minvalue 1
maxvalue 9999999999999999999999999999
start with 1
increment by 1
cache 20;

--tmp
SELECT * FROM FACT_GOODS_EVALUATE_ASPECT;
select * from dim_ec_good a where a.goods_commonid = 177752;

SELECT * FROM FACT_GOODS_EVALUATE_ALIYUN A WHERE A.GEVAL_ID = 1138870;
SELECT * FROM FACT_GOODS_EVALUATE A WHERE A.GEVAL_ID = 1138870;
select * from fact_ec_order_goods a where a.order_id = 2920921;
select to_char(a.geval_orderno)
  FROM FACT_GOODS_EVALUATE A
 WHERE A.GEVAL_ID = 1169509;

select *
  from fact_ec_order_2 a
 where to_char(a.order_sn) = '860577670097614853';
select * from fact_ec_order_goods a where a.order_id = 2920921;

SELECT A.GEVAL_ID, COUNT(1)
  FROM FACT_GOODS_EVALUATE_ALIYUN A
 GROUP BY A.GEVAL_ID
 ORDER BY COUNT(1) DESC;

SELECT * FROM EC_GOODS_EVALUATE_TMP;

SELECT A.GEVAL_CONTENT, A.GEVAL_SENTIMENT_POLARITY_IASPE
  FROM FACT_GOODS_EVALUATE A
 WHERE A.GEVAL_ID = 1323015;

SELECT A.GEVAL_ID,
       A.GEVAL_SENTIMENT_POLARITY_IASPE,
       LENGTH(A.GEVAL_SENTIMENT_POLARITY_IASPE)
  FROM FACT_GOODS_EVALUATE A
 WHERE A.GEVAL_SENTIMENT_POLARITY_IASPE IS NOT NULL
 ORDER BY 3 DESC;
