???CREATE OR REPLACE FORCE VIEW DW_USER.DBA_TABLESPACE_FSFI_V AS
SELECT A.TABLESPACE_NAME,
       A.FILE_ID,
       SQRT(MAX(A.BLOCKS) / SUM(A.BLOCKS)) *
       (100 / SQRT(SQRT(COUNT(A.BLOCKS)))) FSFI,
       SUM(A.BYTES) / 1024 / 1024 FREE_SPACE_MB,
       COUNT(1) FREE_EXT_CNT
  FROM DBA_FREE_SPACE A, DBA_TABLESPACES B
 WHERE A.TABLESPACE_NAME = B.TABLESPACE_NAME
   AND B.CONTENTS NOT IN ('TEMPORARY', 'UNDO')
 GROUP BY A.TABLESPACE_NAME, A.FILE_ID
 ORDER BY FSFI;

