???create or replace force view dw_user.fact_page_view_hitevent as
select "ID","PAGE_VIEW_KEY","VID","DEVICE_KEY","IP","IP_GEO_KEY","IP_INT","URL","PAGE_KEY","PAGE_NAME","PAGE_VALUE","LAST_PAGE_KEY","HMSC_KEY","HMSC","APPLICATION_KEY","APPLICATION_NAME","VISIT_DATE_KEY","VISIT_DATE","PAGEBEGIN_TIME","PAGEEND_TIME","PAGE_STAYTIME_KEY","PAGE_STAYTIME","MEMBER_KEY","VISIT_HOUR_KEY","VISIT_HOUR","VER_KEY","VER_NAME","AGENT","HMMD","HMPL","HMKW","HMCI","VISIT_MONTH","SESSION_KEY","CHANNEL_KEY","IPGEO_KEY","HIT_IS" from fact_page_view_hit;

