???CREATE OR REPLACE FORCE VIEW DW_USER.YJ_DAILY_CHECK_FPV_V AS
SELECT DISTINCT A.VISIT_DATE_KEY, TO_CHAR(A.VISIT_DATE, 'hh24mi') HH24MI
  FROM FACT_PAGE_VIEW A
 WHERE A.VISIT_DATE_KEY >= TO_CHAR(SYSDATE - 1, 'YYYYMMDD')
 ORDER BY A.VISIT_DATE_KEY DESC, TO_CHAR(A.VISIT_DATE, 'hh24mi') DESC;

