???CREATE OR REPLACE FORCE VIEW DW_USER.YJ_EC_ORDER_DETAIL AS
SELECT A.CUST_NO,
       A.ORDER_ID,
       B.GOODS_COMMONID,
       C.ITEM_CODE,
       D.GC_ID,
       D.GC_NAME
  FROM FACT_EC_ORDER_2     A,
       FACT_EC_ORDER_GOODS B,
       DIM_EC_GOOD         C,
       DIM_GOOD_CLASS      D
 WHERE A.ORDER_ID = B.ORDER_ID
   AND B.GOODS_COMMONID = C.GOODS_COMMONID
   AND C.MATDL = C.MATDL
   AND A.ORDER_STATE >= 20
   AND A.CUST_NO <> 0;

