ALTER TABLE DATA_ACQUISITION_ITEM MOVE SUBPARTITION ZP703 COMPRESS PARALLEL 8;
ALTER TABLE DATA_ACQUISITION_ITEM MOVE SUBPARTITION ZP704 COMPRESS PARALLEL 8;
ALTER TABLE DATA_ACQUISITION_ITEM MOVE SUBPARTITION ZP705 COMPRESS PARALLEL 8;
ALTER TABLE DATA_ACQUISITION_ITEM MOVE SUBPARTITION ZP706 COMPRESS PARALLEL 8;
ALTER TABLE DATA_ACQUISITION_ITEM MOVE SUBPARTITION ZP707 COMPRESS PARALLEL 8;
ALTER TABLE DATA_ACQUISITION_ITEM MOVE SUBPARTITION ZP708 COMPRESS PARALLEL 8;
ALTER TABLE DATA_ACQUISITION_ITEM MOVE SUBPARTITION ZP709 COMPRESS PARALLEL 8;
ALTER TABLE DATA_ACQUISITION_ITEM MOVE SUBPARTITION ZP801 COMPRESS PARALLEL 8;
ALTER TABLE DATA_ACQUISITION_ITEM MOVE SUBPARTITION ZP802 COMPRESS PARALLEL 8;
ALTER TABLE DATA_ACQUISITION_ITEM MOVE SUBPARTITION ZP803 COMPRESS PARALLEL 8;
ALTER TABLE DATA_ACQUISITION_ITEM MOVE SUBPARTITION ZP804 COMPRESS PARALLEL 8;
ALTER TABLE DATA_ACQUISITION_ITEM MOVE SUBPARTITION ZP805 COMPRESS PARALLEL 8;
ALTER TABLE DATA_ACQUISITION_ITEM MOVE SUBPARTITION ZP806 COMPRESS PARALLEL 8;
ALTER TABLE DATA_ACQUISITION_ITEM MOVE SUBPARTITION ZP807 COMPRESS PARALLEL 8;
ALTER TABLE DATA_ACQUISITION_ITEM MOVE SUBPARTITION ZP808 COMPRESS PARALLEL 8;
ALTER TABLE DATA_ACQUISITION_ITEM MOVE SUBPARTITION ZP809 COMPRESS PARALLEL 8;
ALTER TABLE DATA_ACQUISITION_ITEM MOVE SUBPARTITION ZP901 COMPRESS PARALLEL 8;
ALTER TABLE DATA_ACQUISITION_ITEM MOVE SUBPARTITION ZP902 COMPRESS PARALLEL 8;
ALTER TABLE DATA_ACQUISITION_ITEM MOVE SUBPARTITION ZP903 COMPRESS PARALLEL 8;
ALTER TABLE DATA_ACQUISITION_ITEM MOVE SUBPARTITION ZP904 COMPRESS PARALLEL 8;
ALTER TABLE DATA_ACQUISITION_ITEM MOVE SUBPARTITION ZP905 COMPRESS PARALLEL 8;
ALTER TABLE DATA_ACQUISITION_ITEM MOVE SUBPARTITION ZP906 COMPRESS PARALLEL 8;
ALTER TABLE DATA_ACQUISITION_ITEM MOVE SUBPARTITION ZP907 COMPRESS PARALLEL 8;
ALTER TABLE DATA_ACQUISITION_ITEM MOVE SUBPARTITION ZP908 COMPRESS PARALLEL 8;
ALTER TABLE DATA_ACQUISITION_ITEM MOVE SUBPARTITION ZP909 COMPRESS PARALLEL 8;


--ALTER INDEX DATA_ACQUISITION_ITEM_I1 REBUILD;
--ALTER INDEX DATA_ACQUISITION_ITEM_I2 REBUILD;
--ALTER INDEX IDX_DATA_ACQUISITION_ITEM_P1 REBUILD;
--ALTER INDEX IDX_DATA_ACQUISITION_ITEM_P30 REBUILD;

DROP INDEX DATA_ACQUISITION_ITEM_I1;
create index DATA_ACQUISITION_ITEM_I1 on DATA_ACQUISITION_ITEM (PERIOD) LOCAL
  tablespace DWDATA00
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
	
DROP INDEX DATA_ACQUISITION_ITEM_I2;
create index DATA_ACQUISITION_ITEM_I2 on DATA_ACQUISITION_ITEM (ACQ_ITEM_CODE) LOCAL
  tablespace DWDATA00
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );

DROP INDEX IDX_DATA_ACQUISITION_ITEM_P1;
create index IDX_DATA_ACQUISITION_ITEM_P1 on DATA_ACQUISITION_ITEM (INSERT_DATE, DATA_SOURCE, ACQ_CATEGORY_NAME) LOCAL
  tablespace ITEMS
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
	
DROP INDEX IDX_DATA_ACQUISITION_ITEM_P30;
create index IDX_DATA_ACQUISITION_ITEM_P30 on DATA_ACQUISITION_ITEM (INSERT_DATE, DATA_SOURCE, ACQ_NAME) LOCAL
  tablespace ITEMS
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );


BEGIN
  DBMS_STATS.GATHER_TABLE_STATS(OWNNAME => 'DW_USER',
                                TABNAME => 'DATA_ACQUISITION_ITEM',
                                DEGREE  => 8,
                                CASCADE => TRUE);
END;
/
