--1.
SELECT 'CALL YJ_OPTIMIZATION.ALTER_TABLE_SHRINK_SPACE(''' || A.SEGMENT_NAME ||
       ''');' SQL1,
       A.*
  FROM DBA_SEGMENTS A
 WHERE A.OWNER = 'DW_USER'
   AND A.SEGMENT_NAME LIKE 'Z%'
	 AND A.SEGMENT_TYPE='TABLE'
 ORDER BY A.SEGMENT_NAME;

--2.
SELECT 'alter database datafile ''' || A.FILE_NAME || ''' resize ' ||
       ROUND(A.FILESIZE - (A.FILESIZE - C.HWMSIZE - 100) * 0.8) || 'M;' S,
       A.FILESIZE || 'M' AS "数据文件的总大小",
       C.HWMSIZE || 'M' AS "数据文件的实用大小",
       A.FILESIZE - C.HWMSIZE || 'M' AS "收缩大小"
  FROM (SELECT FILE_ID, FILE_NAME, ROUND(BYTES / 1024 / 1024) AS FILESIZE
          FROM DBA_DATA_FILES GG
        /*WHERE GG.TABLESPACE_NAME = 'ODSDATA01'*/
        ) A,
       (SELECT FILE_ID, ROUND(MAX(BLOCK_ID) * 8 / 1024) AS HWMSIZE
          FROM DBA_EXTENTS GGG
        /*WHERE GGG.TABLESPACE_NAME = 'ODSDATA01'*/
         GROUP BY FILE_ID) C
 WHERE A.FILE_ID = C.FILE_ID
   AND A.FILESIZE - C.HWMSIZE > 100
 ORDER BY A.FILESIZE - C.HWMSIZE DESC;
