--压缩分区
ALTER TABLE DATA_ACQUISITION_ITEM_BASE MOVE PARTITION P201709 COMPRESS PARALLEL 10;

--解压分区
ALTER TABLE DATA_ACQUISITION_ITEM_BASE MOVE PARTITION P201709 NOCOMPRESS PARALLEL 10;

--SQL
SELECT 'ALTER TABLE ' || A.TABLE_NAME || ' MOVE SUBPARTITION ' ||
       A.SUBPARTITION_NAME || ' COMPRESS PARALLEL 8;' S
  FROM DBA_TAB_SUBPARTITIONS A
 WHERE A.TABLE_NAME = 'DATA_ACQUISITION_ITEM'
   AND A.PARTITION_NAME IN
       ('P4', 'P5', 'P6', 'P7', 'P8', 'P9', 'P10', 'P11', 'P12')
 ORDER BY A.PARTITION_NAME, A.SUBPARTITION_NAME;
