CREATE TABLE `g_activity_goods` (
  `id` int(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `group_id` int(10) unsigned NOT NULL COMMENT '活动分组id',
  `goods_name` varchar(50) NOT NULL DEFAULT '' COMMENT '商品名称',
  `goods_commonid` varchar(20) NOT NULL DEFAULT '' COMMENT '商品编号',
  `item_code` varchar(150) NOT NULL DEFAULT '' COMMENT '商品货号',
  `goods_jingle` varchar(200) NOT NULL DEFAULT '1' COMMENT '商品热点1',
  `goods_jingle2` varchar(200) NOT NULL DEFAULT '' COMMENT '商品热点2',
  `goods_reduction` varchar(50) NOT NULL DEFAULT '' COMMENT '满减文案',
  `superscript_image` varchar(200) DEFAULT NULL COMMENT 'EC角标路径',
  `goods_image` varchar(200) NOT NULL COMMENT '商品图片',
  `goods_promotion_price` varchar(10) NOT NULL COMMENT '商品促销价',
  `goods_marketprice` varchar(10) DEFAULT '' COMMENT '商品市场价',
  `goods_storage` int(11) NOT NULL DEFAULT '0' COMMENT '商品库存',
  `goods_state` int(11) NOT NULL DEFAULT '0' COMMENT '商品状态 0下架，1正常，10违规（禁售）',
  `goods_sales` int(11) NOT NULL DEFAULT '0' COMMENT '活动销量',
  `enable` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否启用 1 启用 0 不启用',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `sort` int(11) NOT NULL DEFAULT '0' COMMENT '排序号，值越大越在前面',
  `sales_sort` int(11) DEFAULT '0' COMMENT '销量排序',
  `sync_status` tinyint(1) DEFAULT '0' COMMENT '1:成功、0：待同步、-1：失败',
  `sync_time` datetime DEFAULT NULL COMMENT '同步时间',
  `sync_enable` tinyint(1) DEFAULT '1' COMMENT '1:同步 0 不同步',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=5264 DEFAULT CHARSET=utf8;

CREATE TABLE G_ACTIVITY_GOODS_TMP
	(ID_COL NUMBER(20),
	GROUP_ID NUMBER(10),
	GOODS_NAME VARCHAR2(150),
	GOODS_COMMONID VARCHAR2(60),
	ITEM_CODE VARCHAR2(450),
	GOODS_JINGLE VARCHAR2(600),
	GOODS_JINGLE2 VARCHAR2(600),
	GOODS_REDUCTION VARCHAR2(150),
	SUPERSCRIPT_IMAGE VARCHAR2(600),
	GOODS_IMAGE VARCHAR2(600),
	GOODS_PROMOTION_PRICE VARCHAR2(30),
	GOODS_MARKETPRICE VARCHAR2(30),
	GOODS_STORAGE NUMBER(10),
	GOODS_STATE NUMBER(10),
	GOODS_SALES NUMBER(10),
	ENABLE_COL NUMBER(4),
	CREATE_TIME DATE,
	UPDATE_TIME DATE,
	SORT_COL NUMBER(10),
	SALES_SORT NUMBER(10),
	SYNC_STATUS NUMBER(1),
	SYNC_TIME DATE,
	SYNC_ENABLE NUMBER(1));
