???create or replace force view bdpuser.fact_daily_zhuangti as
select "ZT_ID","ZT_NAME","ZT_START_DATE","ZT_END_DATE","STATS_DATE","ZTCL_GOODSNUM","ZTDX_GOODSNUM","ZTPV","ZTUV","ZTAVGCNT","ZTAVGTIME","ZTORDERCNT","ZTORDERRS","ZTZHRATE","ZTORDERJS","ZTORDERTOT","ZTITEMCODE","ZTITEMNAME","ZTITEMPRICE","ZTITEMPV","ZTITEMUV","ZTITEMORDERCNT","ZTITEMORDERJS","ZTITEMORDERTOT","ZTITEMMATDLT","ZTITEMBNAME","ZTITEMISTV","KEY" from  dw_user.fact_daily_zhuangti;

