???create or replace force view bdpuser.fact_video_feature as
select "ID","NAME","VIDEO_URL","SECONDS","AD_PIC","CONNER_PIC","CREATE_TIME_KEY","CREATE_TIME","PUBLISH_TIME_KEY","PUBLISH_TIME","END_TIME_KEY","END_TIME","CATEGORY_ID","CATEGORY_NAME","GOODS_CATEGORY","GOODSCATE_ICON","TAG_ID","TAG_NAME","SCREEN_RATIO","STATUS","SHARE_TITLE","SHARE_PIC","SHARE_CONTENT","SHARE_PATH","WATCHCOUNT","LIKECOUNT" from dw_user.fact_video_feature;

