???create or replace force view bdpuser.v_factec_order as
select "ORDER_ID","MEMBER_KEY","ADD_TIME","ADD_TIME_INT","PAYMENT_CODE","PAYMENT_TIME","PAYMENTCHANNEL","FINNSHED_TIME","GOODS_AMOUNT","PAY_AMOUNT","SHIPPING_FEE","ORDER_STATE","INTEGRALS_AMOUNT","ORDER_AMOUNT","REFUND_STATE","REFUND_AMOUNT","ORDER_FROM","APP_NAME","VID","ERP_ORDER_NO","ORDER_IP","VOUCHER_PRICE","VOUCHER_REF","TRANSPZONE","ZONE1_1","ZONE1_2","ZONE1_3","ZONE1_4","LAST_TIME_KEY","FOLLOW_UP_TIME_KEY","FOLLOW_UP_TIME","CANCEL_BEFORE_STATE","GOODS_NUM","LAST_TIME","CRM_ORDER_NO" from  dw_user.factec_order;

