select PML_ID,PML_TITLE,MEMBER_GRADE_DESC,count(distinct(MEMBER_KEY)),count(distinct(CRM_ORDER_NO)),
sum(PML_DISCOUNT*NUMS),sum(UNIT_PRICE*NUMS),sum(BARGAIN_PRICE*NUMS),sum(PROFIT_AMOUNT*NUMS) from (
select CRM_ORDER_NO,PML_TITLE,PML_ID,PML_DISCOUNT,MEMBER_KEY,MEMBER_GRADE_DESC,UNIT_PRICE,BARGAIN_PRICE,NUMS,PURCHASE_PRICE PROFIT_AMOUNT from (
select CRM_ORDER_NO,ERP_ORDER_NO,ERP_CODE,GOODS_NUM,PML_TITLE,PML_ID,PML_DISCOUNT from (select ORDER_ID, SUBSTR(ERP_CODE,0,6) ERP_CODE,GOODS_NUM,PML_TITLE,PML_ID,PML_DISCOUNT from fact_ec_ordergoods where ORDER_ID  in (

 select ORDER_ID from factec_order  where ADD_TIME between 20170701 and 20170731
 and order_state>10) and PML_ID >0 and PML_DISCOUNT>1) aa left join (
 select CRM_ORDER_NO,ERP_ORDER_NO,ORDER_ID from factec_order where ADD_TIME between 20170701 and 20170731
 and order_state>10) bb  on aa.ORDER_ID=bb.ORDER_ID
) cc join  (select ORDER_KEY,MEMBER_KEY,GOODS_COMMON_KEY,MEMBER_GRADE_DESC ,PROFIT_AMOUNT,UNIT_PRICE,BARGAIN_PRICE,NUMS,COST_PRICE,PURCHASE_PRICE from  fact_goods_sales where POSTING_DATE_KEY between 20170601 and 20170831 and
SALES_SOURCE_KEY=20 and order_state=1) dd on cc.CRM_ORDER_NO=dd.ORDER_KEY and cc.ERP_CODE=dd.GOODS_COMMON_KEY
) GROUP  BY PML_ID,PML_TITLE,MEMBER_GRADE_DESC







