create table member_label_head_tmp as
SELECT A.M_LABEL_ID,
       A.M_LABEL_NAME,
       A.M_LABEL_DESC,
       A.M_LABEL_TYPE_ID,
       A.M_LABEL_FATHER_ID,
       A.CREATE_DATE,
       A.CREATE_USER_ID,
       A.LAST_UPDATE_DATE,
       A.LAST_UPDATE_USER_ID,
       A.CURRENT_FLAG,
       A.SORT_FIELD
  FROM MEMBER_LABEL_HEAD@DW27 A
 WHERE TRUNC(A.LAST_UPDATE_DATE) = date'2017-10-12'
