SELECT A.AGENT,
       CASE
         WHEN REGEXP_SUBSTR(UPPER(A.AGENT), 'HUAWEI') = 'HUAWEI' THEN
          'HUAWEI'
         WHEN REGEXP_SUBSTR(UPPER(A.AGENT), 'VIVO') = 'VIVO' THEN
          'VIVO'
         WHEN REGEXP_SUBSTR(UPPER(A.AGENT), 'REDMI') = 'REDMI' THEN
          'XIAOMI'
         WHEN REGEXP_SUBSTR(UPPER(A.AGENT), 'IPHONE') = 'IPHONE' THEN
          'APPLE'
         WHEN REGEXP_SUBSTR(UPPER(A.AGENT), 'OPPO') = 'OPPO' THEN
          'OPPO'
         WHEN REGEXP_SUBSTR(UPPER(A.AGENT), 'SM-J7008') = 'SM-J7008' THEN
          'SAMSUNG'
       END BRAND
  FROM FACT_PAGE_VIEW A
 WHERE A.VISIT_DATE_KEY = 20170906;
select * from FACT_ECORDER_COMMON t;
