SELECT /*+PARALLEL(8)*/
 E.MEMBER_BP, E.ORDER_STATE, COUNT(E.ORDER_KEY) ORDER_COUNT
  FROM (SELECT A.MEMBER_BP, B.ORDER_KEY, B.ORDER_STATE
          FROM MEMBER_LIFE_PERIOD_TMP A,
               (SELECT C.MEMBER_KEY, C.ORDER_KEY, C.ORDER_STATE
                  FROM FACT_ORDER C
                 WHERE C.POSTING_DATE_KEY >= 20160101 /*统计日期从20160101开始*/
                ) B
         WHERE A.MEMBER_BP = B.MEMBER_KEY(+)) E
 GROUP BY E.MEMBER_BP, E.ORDER_STATE;

SELECT COUNT(1)
  FROM (SELECT C.MEMBER_KEY, C.ORDER_KEY, C.ORDER_STATE
          FROM FACT_ORDER C
         WHERE C.POSTING_DATE_KEY >= 20160101 /*统计日期从20160101开始*/
        );

SELECT A.MEMBER_BP, B.ORDER_KEY, B.ORDER_STATE
  FROM MEMBER_LIFE_PERIOD_TMP A,
       (SELECT C.MEMBER_KEY, C.ORDER_KEY, C.ORDER_STATE
          FROM FACT_ORDER C
         WHERE C.POSTING_DATE_KEY >= 20160101 /*统计日期从20160101开始*/
        ) B
 WHERE A.MEMBER_BP = B.MEMBER_KEY(+);

DROP TABLE MEMBER_LIFE_PERIOD_TMP_B;
CREATE TABLE MEMBER_LIFE_PERIOD_TMP_B AS
  SELECT C.POSTING_DATE_KEY, C.MEMBER_KEY, C.ORDER_KEY, C.ORDER_STATE
    FROM FACT_ORDER C
   WHERE C.POSTING_DATE_KEY >= 20160101;

INSERT INTO MEMBER_LIFE_PERIOD_TMP_B
  SELECT A.POSTING_DATE_KEY, A.MEMBER_KEY, A.ORDER_KEY, A.ORDER_STATE
    FROM FACT_ORDER A
   WHERE A.POSTING_DATE_KEY = 20160101;

select DISTINCT T.POSTING_DATE_KEY
  from MEMBER_LIFE_PERIOD_TMP_B t
 ORDER BY 1;

SELECT A.POSTING_DATE_KEY, A.MEMBER_KEY, A.ORDER_KEY, A.ORDER_STATE
  FROM FACT_ORDER A
 WHERE A.POSTING_DATE_KEY = &IN_POSTING_DATE_KEY
   AND NOT EXISTS (SELECT 1
          FROM MEMBER_LIFE_PERIOD_TMP_B B
         WHERE A.POSTING_DATE_KEY = B.POSTING_DATE_KEY
           AND A.MEMBER_KEY = B.MEMBER_KEY
           AND A.ORDER_KEY = B.ORDER_KEY);
