SELECT A.START_TIME,
       A.END_TIME,
       A.ETL_DURATION,
       A.ETL_RECORD_INS,
       A.ETL_STATUS,
       A.ERR_MSG,
       A.PROC_NAME
  FROM W_ETL_LOG A
 WHERE A.PROC_NAME = 'MEMBER_FILTER_PKG.SYNC_MEMBER_LABEL_HEAD'
 ORDER BY A.START_TIME DESC;
SELECT A.START_TIME,
       A.END_TIME,
       A.ETL_DURATION,
       A.ETL_RECORD_INS,
       A.ETL_STATUS,
       A.ERR_MSG,
       A.PROC_NAME
  FROM W_ETL_LOG A
 WHERE A.PROC_NAME = 'MEMBER_FILTER_PKG.SYNC_MEMBER_LABEL_LINK'
 ORDER BY A.START_TIME DESC;
