CREATE TABLE MLL_ROW_ID_TMP AS
SELECT A.ROW_ID FROM MEMBER_LABEL_LINK@DW27 A ;

TRUNCATE TABLE MLL_ROW_ID_TMP;

INSERT INTO MLL_ROW_ID_TMP
  SELECT A.ROW_ID FROM MEMBER_LABEL_LINK@DW27 A WHERE A.ROW_ID IS NOT NULL;
COMMIT;

SELECT *
  FROM MEMBER_LABEL_LINK A
 WHERE NOT EXISTS
 (SELECT 1 FROM MLL_ROW_ID_TMP B WHERE A.ROW_ID = B.ROW_ID);
