TRUNCATE TABLE MEMBER_TMP;
SELECT * FROM MEMBER_TMP FOR UPDATE;

SELECT A.MEMBER_KEY,COUNT(1) FROM MEMBER_TMP A GROUP BY A.MEMBER_KEY HAVING COUNT(1)>1;

SELECT *
  FROM FACT_PAGE_VIEW A
 WHERE A.VISIT_DATE_KEY >= 20171001
   AND EXISTS
 (SELECT 1 FROM MEMBER_TMP B WHERE A.MEMBER_KEY = B.MEMBER_KEY);
