SELECT *
  FROM W_ETL_LOG A
 WHERE A.PROC_NAME = 'MEMBER_LABEL_PKG.MERGE_PUSH_MSG_LOG'
 ORDER BY A.START_TIME DESC;

SELECT RANK() OVER(PARTITION BY TO_CHAR(T.START_TIME, 'YYYYMMDDHH24') ORDER BY T.END_TIME) RANK1,
       T.PROC_NAME,
       T.ETL_STATUS,
       T.ETL_DURATION,
       T.ETL_RECORD_INS,
       T.ETL_RECORD_UPD,
       T.ETL_RECORD_DEL,
       T.START_TIME,
       T.END_TIME,
       T.TABLE_NAME,
       T.ERR_MSG
  FROM W_ETL_LOG T
 WHERE T.PROC_NAME IN
       ('MEMBER_LABEL_PKG.MERGE_PUSH_MSG_LOG',
        'MEMBER_LABEL_PKG.MERGE_PUSH_TASK_RULE',
        'MEMBER_LABEL_PKG.MESSAGE_PUSH_LABEL')
--AND TRUNC(T.START_TIME) = TRUNC(SYSDATE)
 ORDER BY T.END_TIME DESC;

UPDATE PUSH_MSG_LOG_TMP A
   SET A.MEMBER_BP =
       (SELECT MIN(B.MEMBER_KEY) MEMBER_KEY
          FROM DIM_MAPPING_MEM B
         WHERE A.SEND_MEMBER = B.OPEN_ID)
 WHERE A.TASK_TYPE = 1
   AND A.MEMBER_BP IS NULL
   AND EXISTS
 (SELECT 1 FROM DIM_MAPPING_MEM C WHERE A.SEND_MEMBER = C.OPEN_ID);
