WITH ALL_MEMBER AS
/*整体会员数*/
 (SELECT COUNT(DISTINCT A.MEMBER_BP) ALL_BP_COUNT
    FROM MEMBER_ITEM_APRIORI_BASE A),
A_TRAN AS
/*A商品会员数*/
 (SELECT A.ITEM_CODE, COUNT(A.MEMBER_BP) A_BP_COUNT
    FROM MEMBER_ITEM_APRIORI_BASE A
   GROUP BY A.ITEM_CODE)
SELECT D.ITEM_CODE_A,
       D.ITEM_CODE_B,
       D.BP_COUNT / F.A_BP_COUNT,
       D.BP_COUNT / E.ALL_BP_COUNT SUPPPORT_RATE
  FROM (SELECT C.ITEM_CODE_A, C.ITEM_CODE_B, COUNT(C.MEMBER_BP) BP_COUNT
          FROM (SELECT A.MEMBER_BP,
                       A.ITEM_CODE ITEM_CODE_A,
                       B.ITEM_CODE ITEM_CODE_B
                  FROM MEMBER_ITEM_APRIORI_BASE A, MEMBER_ITEM_APRIORI_BASE B
                 WHERE A.MEMBER_BP = B.MEMBER_BP
                   AND A.ITEM_CODE <> B.ITEM_CODE) C
         GROUP BY C.ITEM_CODE_A, C.ITEM_CODE_B
         ORDER BY COUNT(C.MEMBER_BP) DESC) D,
       ALL_MEMBER E,
       A_TRAN F
 WHERE ROWNUM <= 100000
   AND D.ITEM_CODE_A = F.ITEM_CODE;
