CREATE INDEX application_key_idx
   ON FACT_PAGE_VIEW (application_key) NOLOGGING PARALLEL 10;
ALTER INDEX visit_date_key_idx PARALLEL 1;


SELECT /*+PARALLEL(16)*/
 A.APPLICATION_KEY, COUNT(1)
  FROM FACT_PAGE_VIEW A
 GROUP BY A.APPLICATION_KEY;
