SELECT * FROM MLOG$_GOODS_LABEL_LINK;

WITH GA AS
 (SELECT A.G_LABEL_ID, COUNT(1) S_CNT
    FROM GOODS_LABEL_LINK A
   GROUP BY A.G_LABEL_ID
   ORDER BY A.G_LABEL_ID),
GB AS
 (SELECT A.G_LABEL_ID, COUNT(1) T_CNT
    FROM GOODS_LABEL_LINK_V@ML18 A
   GROUP BY A.G_LABEL_ID
   ORDER BY A.G_LABEL_ID)
SELECT GA.G_LABEL_ID, GA.S_CNT, GB.T_CNT, GA.S_CNT - GB.T_CNT D_CNT
  FROM GA, GB
 WHERE GA.G_LABEL_ID = GB.G_LABEL_ID(+);

--
SELECT *
  FROM GOODS_LABEL_LINK A
 WHERE A.G_LABEL_ID = 1053
 ORDER BY A.ROW_ID;
SELECT *
  FROM GOODS_LABEL_LINK_V@ML18 A
 WHERE A.G_LABEL_ID = 1053
 ORDER BY A.ROW_ID;

--´¦Àí
DECLARE
  TYPE TYPE_ARRAYS IS RECORD(
    G_LABEL_ID NUMBER(10));
  TYPE TYPE_ARRAY IS TABLE OF TYPE_ARRAYS INDEX BY BINARY_INTEGER;
  VAR_ARRAY TYPE_ARRAY;
BEGIN
  SELECT P.*
    BULK COLLECT
    INTO VAR_ARRAY
    FROM (SELECT A.G_LABEL_ID
            FROM GOODS_LABEL_HEAD A
           WHERE A.G_LABEL_ID IN
                 (1053, 1062, 22, 25, 1004, 1005, 1060, 999, 29, 1051)) P;
  FOR I IN 1 .. VAR_ARRAY.COUNT LOOP
    UPDATE GOODS_LABEL_LINK A
       SET A.LAST_UPDATE_DATE = SYSDATE
     WHERE NOT EXISTS (SELECT 1
              FROM GOODS_LABEL_LINK_V@ML18 B
             WHERE A.ITEM_CODE = B.ITEM_CODE
               AND B.G_LABEL_ID = VAR_ARRAY(I).G_LABEL_ID)
       AND A.G_LABEL_ID = VAR_ARRAY(I).G_LABEL_ID;
    COMMIT;
  END LOOP;
END;


--
UPDATE GOODS_LABEL_LINK A
   SET A.LAST_UPDATE_DATE = A.LAST_UPDATE_DATE
 WHERE A.LAST_UPDATE_DATE >= DATE '2018-09-04';
COMMIT;

BEGIN
  GOODS_FILTER_PKG.SYNC_GOODS_LABEL_LINK;
END;
