--新媒体所有VIP会员HAPP_T6
SELECT A.MEMBER_BP
  FROM DIM_MEMBER A
 WHERE A.MEMBER_LEVEL = 'HAPP_T6'
   AND EXISTS
 (SELECT 1 FROM FACT_ECMEMBER B WHERE A.MEMBER_BP = B.MEMBER_CRMBP)
 ORDER BY A.MEMBER_BP;

SELECT A.MEMBER_BP
  FROM DIM_MEMBER A
 WHERE A.MEMBER_LEVEL = 'HAPP_T5'
   AND EXISTS
 (SELECT 1 FROM FACT_ECMEMBER B WHERE A.MEMBER_BP = B.MEMBER_CRMBP)
 ORDER BY A.MEMBER_BP;

--1-8月有过订购记录的白金会员
SELECT DISTINCT TO_NUMBER(A.CUST_NO) MEMBER_BP
  FROM FACT_EC_ORDER_2 A
 WHERE A.ADD_TIME BETWEEN DATE '2018-01-01' AND DATE '2018-08-31'
   AND A.ORDER_STATE >= 20
   AND A.CUST_NO <> 0
   AND EXISTS
 (SELECT 1
          FROM DIM_MEMBER B
         WHERE TO_NUMBER(A.CUST_NO) = B.MEMBER_BP
           AND B.MEMBER_LEVEL = 'HAPP_T4'
           AND EXISTS (SELECT 1
                  FROM FACT_ECMEMBER C
                 WHERE B.MEMBER_BP = C.MEMBER_CRMBP))
 ORDER BY 1;

SELECT A.MEMBER_BP
  FROM DIM_MEMBER A
 WHERE A.MEMBER_LEVEL = 'HAPP_T4'
   AND EXISTS
 (SELECT 1 FROM FACT_ECMEMBER B WHERE A.MEMBER_BP = B.MEMBER_CRMBP)
 ORDER BY A.MEMBER_BP;

SELECT * FROM ALL_COL_COMMENTS A WHERE A.COMMENTS LIKE '%会员池%';

SELECT * FROM OPER_ACTIVE_MEMBER_REPORT;

SELECT * FROM DIM_MEMBER;

select * from fact_ecmember;

select A.MEMBER_CRMBP, COUNT(1)
  from fact_ecmember A
 GROUP BY A.MEMBER_CRMBP
having count(1) > 1;

select * from fact_ecmember a where a.member_crmbp=1500315662;
