--1.
TRUNCATE TABLE YANGJIN.ITEM_CODE_TMP;
SELECT * FROM YANGJIN.ITEM_CODE_TMP FOR UPDATE;

--2.
UPDATE YANGJIN.ITEM_CODE_TMP A
   SET A.GOODS_COMMONID =
       (SELECT B.GOODS_COMMONID
          FROM DIM_EC_GOOD B
         WHERE A.ITEM_CODE = B.ITEM_CODE)
 WHERE EXISTS (SELECT 1 FROM DIM_EC_GOOD C WHERE A.ITEM_CODE = C.ITEM_CODE);

--3.
--‰Ø¿¿
SELECT TO_NUMBER(A.MEMBER_KEY) MEMBER_BP,
       COUNT(DISTINCT A.PAGE_VALUE) ITEM_CNT
  FROM FACT_PAGE_VIEW PARTITION(FPV2018) A
 WHERE A.VISIT_DATE_KEY BETWEEN 20180901 AND 20181203
   AND A.MEMBER_KEY <> 0
   AND a.page_value =
       translate(a.page_value,
                 '0' || translate(a.page_value, '#0123456789', '#'),
                 '0')
   AND EXISTS (SELECT 1
          FROM YANGJIN.ITEM_CODE_TMP B
         WHERE A.PAGE_VALUE = B.GOODS_COMMONID)
 GROUP BY TO_NUMBER(A.MEMBER_KEY)
 ORDER BY COUNT(DISTINCT A.PAGE_VALUE) DESC;
