SELECT *
  FROM (SELECT OD2.GOODS_KEY /**/,
               OD2.GOODS_COMMON_KEY /**/,
               OD2.SALES_SOURCE_SECOND_KEY /*销售二级组织key*/,
               OD2.ITEM_OR_GIFT /*主赠品*/,
               OD2.TRAN_TYPE /*交易类型*/,
               DECODE(OD2.TRAN_TYPE, 'TAN', '主品', 'REN', '主品退货') TRAN_TYPE_NAME /*交易类型说明*/,
               OD2.MD_PERSON /*MD工号*/,
               OD2.POSTING_DATE_KEY /*过账日期key*/,
               OD2.LIVE_OR_REPLAY /*是否播出*/,
               OD2.TOTAL_ORDER_AMOUNT /*总订购金额*/,
               OD2.NET_ORDER_AMOUNT /*净订购金额*/,
               OD2.EFFECTIVE_ORDER_AMOUNT /*有效订购金额*/,
               OD2.CANCEL_ORDER_AMOUNT /*取消订购金额*/,
               OD2.REVERSE_ORDER_AMOUNT /*退货订购金额*/,
               OD2.REJECT_ORDER_AMOUNT /*拒收订购金额*/,
               OD2.CANCEL_REVERSE_AMOUNT /*退货取消订购金额*/,
               OD2.CANCEL_REJECT_AMOUNT /*拒收取消订购金额*/,
               OD2.TOTAL_SALES_AMOUNT /*总售价金额*/,
               OD2.NET_SALES_AMOUNT /*净售价金额*/,
               OD2.EFFECTIVE_SALES_AMOUNT /*有效售价金额*/,
               OD2.TOTAL_ORDER_MEMBER_COUNT /*总订购人数*/,
               OD2.NET_ORDER_MEMBER_COUNT /*净订购人数*/,
               OD2.EFFECTIVE_ORDER_MEMBER_COUNT /*有效订购人数*/,
               OD2.CANCEL_ORDER_MEMBER_COUNT /*取消订购人数*/,
               OD2.REVERSE_MEMBER_COUNT /*退货订购人数*/,
               OD2.REJECT_MEMBER_COUNT /*拒收订购人数*/,
               OD2.CANCEL_REVERSE_MEMBER_COUNT /*退货取消订购人数*/,
               OD2.CANCEL_REJECT_MEMBER_COUNT /*拒收取消订购人数*/,
               OD2.TOTAL_ORDER_COUNT /*总订购单数*/,
               OD2.NET_ORDER_COUNT /*净订购单数*/,
               OD2.EFFECTIVE_ORDER_COUNT /*有效订购单数*/,
               OD2.CANCEL_ORDER_COUNT /*取消订购单数*/,
               OD2.REVERSE_COUNT /*退货订购单数*/,
               OD2.REJECT_COUNT /*拒收订购单数*/,
               OD2.CANCEL_REVERSE_COUNT /*退货取消订购件数*/,
               OD2.CANCEL_REJECT_COUNT /*拒收取消订购件数*/,
               OD2.TOTAL_ORDER_AMOUNT + OD2.PROFIT_AMOUNT -
               OD2.TOTAL_PURCHASE_AMOUNT GROSS_PROFIT_AMOUNT /*还原后总毛利额*/,
               OD2.NET_ORDER_AMOUNT + OD2.PROFIT_AMOUNT -
               OD2.NET_PURCHASE_AMOUNT NET_PROFIT_AMOUNT /*还原后净毛利额*/,
               OD2.EFFECTIVE_ORDER_AMOUNT + OD2.PROFIT_AMOUNT -
               OD2.EFFECTIVE_PURCHASE_AMOUNT EFFECTIVE_PROFIT_AMOUNT /*还原后有效毛利额*/,
               DECODE(OD2.TOTAL_ORDER_AMOUNT,
                      0,
                      0,
                      (OD2.TOTAL_ORDER_AMOUNT + OD2.PROFIT_AMOUNT -
                      OD2.TOTAL_PURCHASE_AMOUNT) / OD2.TOTAL_ORDER_AMOUNT) GROSS_PROFIT_RATE /*还原后总毛利率*/,
               DECODE(OD2.NET_ORDER_AMOUNT,
                      0,
                      0,
                      (OD2.NET_ORDER_AMOUNT + OD2.PROFIT_AMOUNT -
                      OD2.NET_PURCHASE_AMOUNT) / OD2.NET_ORDER_AMOUNT) NET_PROFIT_RATE /*还原后净毛利率*/,
               DECODE(OD2.EFFECTIVE_ORDER_AMOUNT,
                      0,
                      0,
                      (OD2.EFFECTIVE_ORDER_AMOUNT + OD2.PROFIT_AMOUNT -
                      OD2.EFFECTIVE_PURCHASE_AMOUNT) /
                      OD2.EFFECTIVE_ORDER_AMOUNT) EFFECTIVE_PROFIT_RATE /*还原后有效毛利率*/,
               OD2.TOTAL_ORDER_QTY /*总订购数量*/,
               OD2.NET_ORDER_QTY /*净订购数量*/,
               OD2.EFFECTIVE_ORDER_QTY /*有效订购数量*/,
               OD2.CANCEL_ORDER_QTY /*取消订购数量*/,
               OD2.REVERSE_QTY /*退货订购数量*/,
               OD2.REJECT_QTY /*拒收订购数量*/,
               OD2.CANCEL_REVERSE_QTY /*退货取消订购数量*/,
               OD2.CANCEL_REJECT_QTY /*拒收取消订购数量*/,
               OD2.NET_ORDER_CUST_PRICE /*净订购客单价*/,
               OD2.EFFECTIVE_ORDER_CUST_PRICE /*有效订购客单价*/,
               OD2.NET_ORDER_UNIT_PRICE /*净订购件单价*/,
               OD2.EFFECTIVE_ORDER_UNIT_PRICE /*有效订购件单价*/,
               OD2.TOTAL_PURCHASE_AMOUNT /*总订购成本*/,
               OD2.NET_PURCHASE_AMOUNT /*净订购成本*/,
               OD2.EFFECTIVE_PURCHASE_AMOUNT /*有效订购成本*/,
               OD2.PROFIT_AMOUNT /*折扣金额*/,
               OD2.COUPONS_AMOUNT /*优惠券金额*/,
               OD2.FREIGHT_AMOUNT /*运费*/,
               OD2.PRODUCT_AVG_PRICE /*商品平均售价*/,
               OD2.REJECT_AMOUNT /*拒退金额*/
          FROM (SELECT OD1.GOODS_KEY /**/,
                       OD1.GOODS_COMMON_KEY /**/,
                       OD1.SALES_SOURCE_SECOND_KEY /*销售二级组织key*/,
                       DECODE(OD1.TRAN_TYPE, 0, '主品', 1, '赠品') ITEM_OR_GIFT /*主赠品*/,
                       DECODE(OD1.CANCEL_STATE, 0, 'TAN', 1, 'REN') TRAN_TYPE /*交易类型*/,
                       OD1.MD_PERSON /*MD工号*/,
                       OD1.POSTING_DATE_KEY /*过账日期key*/,
                       DECODE(OD1.LIVE_OR_REPLAY,
                              '10',
                              '直播',
                              '01',
                              '重播',
                              '未分配') LIVE_OR_REPLAY /*是否播出*/,
                       SUM(DECODE(OD1.CANCEL_STATE,
                                  0,
                                  OD1.TOTAL_ORDER_AMOUNT,
                                  1,
                                  0)) TOTAL_ORDER_AMOUNT /*总订购金额*/,
                       SUM(DECODE(OD1.CANCEL_STATE,
                                  0,
                                  OD1.NET_ORDER_AMOUNT,
                                  1,
                                  -ABS(OD1.NET_ORDER_AMOUNT))) NET_ORDER_AMOUNT /*净订购金额*/,
                       SUM(DECODE(OD1.CANCEL_STATE,
                                  0,
                                  OD1.EFFECTIVE_ORDER_AMOUNT,
                                  1,
                                  -ABS(OD1.EFFECTIVE_ORDER_AMOUNT))) EFFECTIVE_ORDER_AMOUNT /*有效订购金额*/,
                       SUM(DECODE(OD1.CANCEL_STATE,
                                  0,
                                  0,
                                  1,
                                  OD1.TOTAL_ORDER_AMOUNT)) CANCEL_ORDER_AMOUNT /*取消订购金额*/,
                       0 REVERSE_ORDER_AMOUNT /*退货订购金额*/,
                       0 REJECT_ORDER_AMOUNT /*拒收订购金额*/,
                       0 CANCEL_REVERSE_AMOUNT /*退货取消订购金额*/,
                       0 CANCEL_REJECT_AMOUNT /*拒收取消订购金额*/,
                       SUM(DECODE(OD1.CANCEL_STATE,
                                  0,
                                  OD1.TOTAL_SALES_AMOUNT,
                                  1,
                                  0)) TOTAL_SALES_AMOUNT /*总售价金额*/,
                       SUM(DECODE(OD1.CANCEL_STATE,
                                  0,
                                  OD1.NET_SALES_AMOUNT,
                                  1,
                                  -ABS(OD1.NET_SALES_AMOUNT))) NET_SALES_AMOUNT /*净售价金额*/,
                       SUM(DECODE(OD1.CANCEL_STATE,
                                  0,
                                  OD1.EFFECTIVE_SALES_AMOUNT,
                                  1,
                                  -ABS(OD1.EFFECTIVE_SALES_AMOUNT))) EFFECTIVE_SALES_AMOUNT /*有效售价金额*/,
                       DECODE(OD1.CANCEL_STATE,
                              0,
                              COUNT(DISTINCT OD1.MEMBER_KEY),
                              1,
                              0) TOTAL_ORDER_MEMBER_COUNT /*总订购人数*/,
                       DECODE(OD1.CANCEL_STATE,
                              0,
                              COUNT(DISTINCT OD1.MEMBER_KEY),
                              1,
                              -COUNT(DISTINCT OD1.MEMBER_KEY)) NET_ORDER_MEMBER_COUNT /*净订购人数*/,
                       DECODE(OD1.CANCEL_STATE,
                              0,
                              COUNT(DISTINCT OD1.MEMBER_KEY),
                              1,
                              -COUNT(DISTINCT OD1.MEMBER_KEY)) EFFECTIVE_ORDER_MEMBER_COUNT /*有效订购人数*/,
                       DECODE(OD1.CANCEL_STATE,
                              0,
                              0,
                              1,
                              COUNT(DISTINCT OD1.MEMBER_KEY)) CANCEL_ORDER_MEMBER_COUNT /*取消订购人数*/,
                       0 REVERSE_MEMBER_COUNT /*退货订购人数*/,
                       0 REJECT_MEMBER_COUNT /*拒收订购人数*/,
                       0 CANCEL_REVERSE_MEMBER_COUNT /*退货取消订购人数*/,
                       0 CANCEL_REJECT_MEMBER_COUNT /*拒收取消订购人数*/,
                       DECODE(OD1.CANCEL_STATE,
                              0,
                              COUNT(DISTINCT OD1.ORDER_H_KEY),
                              1,
                              0) TOTAL_ORDER_COUNT /*总订购单数*/,
                       DECODE(OD1.CANCEL_STATE,
                              0,
                              COUNT(DISTINCT OD1.ORDER_H_KEY),
                              1,
                              -COUNT(DISTINCT OD1.ORDER_H_KEY)) NET_ORDER_COUNT /*净订购单数*/,
                       DECODE(OD1.CANCEL_STATE,
                              0,
                              COUNT(DISTINCT OD1.ORDER_H_KEY),
                              1,
                              -COUNT(DISTINCT OD1.ORDER_H_KEY)) EFFECTIVE_ORDER_COUNT /*有效订购单数*/,
                       DECODE(OD1.CANCEL_STATE,
                              0,
                              0,
                              1,
                              COUNT(DISTINCT OD1.ORDER_H_KEY)) CANCEL_ORDER_COUNT /*取消订购单数*/,
                       0 REVERSE_COUNT /*退货订购单数*/,
                       0 REJECT_COUNT /*拒收订购单数*/,
                       0 CANCEL_REVERSE_COUNT /*退货取消订购件数*/,
                       0 CANCEL_REJECT_COUNT /*拒收取消订购件数*/,
                       SUM(DECODE(OD1.CANCEL_STATE,
                                  0,
                                  OD1.TOTAL_ORDER_QTY,
                                  1,
                                  0)) TOTAL_ORDER_QTY /*总订购数量*/,
                       SUM(DECODE(OD1.CANCEL_STATE,
                                  0,
                                  OD1.NET_ORDER_QTY,
                                  1,
                                  -ABS(OD1.NET_ORDER_QTY))) NET_ORDER_QTY /*净订购数量*/,
                       SUM(DECODE(OD1.CANCEL_STATE,
                                  0,
                                  OD1.EFFECTIVE_ORDER_QTY,
                                  1,
                                  -ABS(OD1.EFFECTIVE_ORDER_QTY))) EFFECTIVE_ORDER_QTY /*有效订购数量*/,
                       DECODE(OD1.CANCEL_STATE,
                              0,
                              0,
                              1,
                              COUNT(DISTINCT OD1.TOTAL_ORDER_QTY)) CANCEL_ORDER_QTY /*取消订购数量*/,
                       0 REVERSE_QTY /*退货订购数量*/,
                       0 REJECT_QTY /*拒收订购数量*/,
                       0 CANCEL_REVERSE_QTY /*退货取消订购数量*/,
                       0 CANCEL_REJECT_QTY /*拒收取消订购数量*/,
                       SUM(OD1.NET_ORDER_AMOUNT) /
                       COUNT(DISTINCT OD1.MEMBER_KEY) NET_ORDER_CUST_PRICE /*净订购客单价*/,
                       SUM(OD1.EFFECTIVE_ORDER_AMOUNT) /
                       COUNT(DISTINCT OD1.MEMBER_KEY) EFFECTIVE_ORDER_CUST_PRICE /*有效订购客单价*/,
                       SUM(OD1.NET_ORDER_AMOUNT) / SUM(OD1.NET_ORDER_QTY) NET_ORDER_UNIT_PRICE /*净订购件单价*/,
                       SUM(OD1.EFFECTIVE_ORDER_AMOUNT) /
                       SUM(OD1.EFFECTIVE_ORDER_QTY) EFFECTIVE_ORDER_UNIT_PRICE /*有效订购件单价*/,
                       SUM(DECODE(OD1.CANCEL_STATE,
                                  0,
                                  OD1.TOTAL_PURCHASE_AMOUNT,
                                  1,
                                  0)) TOTAL_PURCHASE_AMOUNT /*总订购成本*/,
                       SUM(DECODE(OD1.CANCEL_STATE,
                                  0,
                                  OD1.NET_PURCHASE_AMOUNT,
                                  1,
                                  -ABS(OD1.NET_PURCHASE_AMOUNT))) NET_PURCHASE_AMOUNT /*净订购成本*/,
                       SUM(DECODE(OD1.CANCEL_STATE,
                                  0,
                                  OD1.EFFECTIVE_PURCHASE_AMOUNT,
                                  1,
                                  -ABS(OD1.EFFECTIVE_PURCHASE_AMOUNT))) EFFECTIVE_PURCHASE_AMOUNT /*有效订购成本*/,
                       SUM(DECODE(OD1.CANCEL_STATE,
                                  0,
                                  OD1.PROFIT_AMOUNT,
                                  1,
                                  -ABS(OD1.PROFIT_AMOUNT))) PROFIT_AMOUNT /*折扣金额*/,
                       SUM(OD1.COUPONS_AMOUNT) COUPONS_AMOUNT /*优惠券金额*/,
                       SUM(OD1.FREIGHT_AMOUNT) FREIGHT_AMOUNT /*运费*/,
                       SUM(OD1.TOTAL_SALES_AMOUNT) / SUM(OD1.TOTAL_ORDER_QTY) PRODUCT_AVG_PRICE /*商品平均售价*/,
                       0 REJECT_AMOUNT /*拒退金额*/
                  FROM (SELECT OD.ORDER_KEY /*订单权责制*/,
                               OD.ORDER_H_KEY /*订单发生制*/,
                               OD.ORDER_DESC /*订购状态*/,
                               OD.GOODS_KEY /*商品*/,
                               OD.GOODS_COMMON_KEY /*商品短编码*/,
                               OD.SALES_SOURCE_SECOND_KEY /*销售二级组织key*/,
                               OD.TRAN_TYPE /*是否赠品标志*/,
                               OD.TRAN_DESC /*交易类型*/,
                               OD.MD_PERSON /*MD工号*/,
                               OD.POSTING_DATE_KEY /*过账日期key*/,
                               TO_CHAR(OD.LIVE_STATE) ||
                               TO_CHAR(OD.REPLAY_STATE) LIVE_OR_REPLAY /*直播重播*/,
                               OD.ORDER_STATE /*订单状态*/,
                               OD.CANCEL_STATE /*取消状态*/,
                               OD.MEMBER_KEY /*会员key*/,
                               OD.NUMS TOTAL_ORDER_QTY /*总订购数量*/,
                               OD.NUMS NET_ORDER_QTY /*净订购数量*/,
                               OD.NUMS EFFECTIVE_ORDER_QTY /*有效订购数量*/,
                               OD.ORDER_AMOUNT TOTAL_ORDER_AMOUNT /*总订单金额*/,
                               OD.ORDER_AMOUNT NET_ORDER_AMOUNT /*净订购金额*/,
                               OD.ORDER_AMOUNT EFFECTIVE_ORDER_AMOUNT /*有效订购金额*/,
                               OD.SALES_AMOUNT TOTAL_SALES_AMOUNT /*总售价金额*/,
                               OD.SALES_AMOUNT NET_SALES_AMOUNT /*净订购金额*/,
                               OD.SALES_AMOUNT EFFECTIVE_SALES_AMOUNT /*有效订购金额*/,
                               OD.UNIT_PRICE /*单个商品售价*/,
                               OD.COST_PRICE /*商品单件成本*/,
                               OD.FREIGHT_AMOUNT /*运费*/,
                               OD.COUPONS_PRICE COUPONS_AMOUNT /*优惠券金额*/,
                               OD.PURCHASE_AMOUNT TOTAL_PURCHASE_AMOUNT /*总订购成本*/,
                               OD.PURCHASE_AMOUNT NET_PURCHASE_AMOUNT /*净订购成本*/,
                               OD.PURCHASE_AMOUNT EFFECTIVE_PURCHASE_AMOUNT /*有效订购成本*/,
                               OD.PROFIT_AMOUNT /*折扣金额*/
                          FROM (
                                /*取消的订单，按过账日期POSTING_DATE_KEY记正向订单。
                                2017-06-14 yangjin*/
                                SELECT ODU1.ORDER_KEY /*订单权责制*/,
                                        ODU1.ORDER_H_KEY /*订单发生制*/,
                                        ODU1.ORDER_DESC /*订购状态*/,
                                        ODU1.GOODS_KEY /*商品*/,
                                        ODU1.GOODS_COMMON_KEY /*商品短编码*/,
                                        ODU1.SALES_SOURCE_SECOND_KEY /*销售二级组织key*/,
                                        ODU1.TRAN_TYPE /*是否赠品标志*/,
                                        ODU1.TRAN_DESC /*交易类型*/,
                                        ODU1.MD_PERSON /*MD工号*/,
                                        ODU1.POSTING_DATE_KEY /*过账日期key*/,
                                        ODU1.LIVE_STATE /*是否直播*/,
                                        ODU1.REPLAY_STATE /*是否重播*/,
                                        ODU1.ORDER_STATE /*订单状态*/,
                                        CASE
                                          WHEN ODU1.CANCEL_STATE = 1 AND
                                               ODU1.POSTING_DATE_KEY <=
                                               ODU1.UPDATE_TIME THEN
                                           0
                                          ELSE
                                           ODU1.CANCEL_STATE
                                        END CANCEL_STATE /*取消状态*/,
                                        ODU1.MEMBER_KEY /*会员key*/,
                                        ODU1.NUMS,
                                        ODU1.ORDER_AMOUNT,
                                        ODU1.SALES_AMOUNT,
                                        ODU1.UNIT_PRICE /*单个商品售价*/,
                                        ODU1.COST_PRICE /*商品单件成本*/,
                                        ODU1.FREIGHT_AMOUNT /*运费*/,
                                        ODU1.COUPONS_PRICE /*优惠券金额*/,
                                        ODU1.PURCHASE_AMOUNT /*订购成本*/,
                                        ODU1.PROFIT_AMOUNT /*折扣金额*/
                                  FROM FACT_GOODS_SALES ODU1
                                 WHERE
                                /*2018-03-15剔除扫码购销售，FACT_EC_ORDER_2.order_from=76为扫码购销售*/
                                 NOT EXISTS
                                 (SELECT 1
                                    FROM FACT_EC_ORDER_2 FEO
                                   WHERE ODU1.ORDER_KEY = FEO.CRM_ORDER_NO
                                     AND FEO.ORDER_FROM = '76')
                                
                                UNION ALL
                                /*取消的订单，按更新日期UPDATE_TIME记逆向订单（虚拟记录）。
                                2017-06-14 yangjin*/
                                SELECT ODU2.ORDER_KEY /*订单权责制*/,
                                        ODU2.ORDER_H_KEY /*订单发生制*/,
                                        ODU2.ORDER_DESC /*订购状态*/,
                                        ODU2.GOODS_KEY /*商品*/,
                                        ODU2.GOODS_COMMON_KEY /*商品短编码*/,
                                        ODU2.SALES_SOURCE_SECOND_KEY /*销售二级组织key*/,
                                        ODU2.TRAN_TYPE /*是否赠品标志*/,
                                        ODU2.TRAN_DESC /*交易类型*/,
                                        ODU2.MD_PERSON /*MD工号*/,
                                        ODU2.UPDATE_TIME POSTING_DATE_KEY /*过账日期key*/,
                                        ODU2.LIVE_STATE /*是否直播*/,
                                        ODU2.REPLAY_STATE /*是否重播*/,
                                        ODU2.ORDER_STATE /*订单状态*/,
                                        ODU2.CANCEL_STATE /*取消状态*/,
                                        ODU2.MEMBER_KEY /*会员key*/,
                                        ODU2.NUMS,
                                        ODU2.ORDER_AMOUNT,
                                        ODU2.SALES_AMOUNT,
                                        ODU2.UNIT_PRICE /*单个商品售价*/,
                                        ODU2.COST_PRICE /*商品单件成本*/,
                                        ODU2.FREIGHT_AMOUNT /*运费*/,
                                        ODU2.COUPONS_PRICE /*优惠券金额*/,
                                        ODU2.PURCHASE_AMOUNT,
                                        ODU2.PROFIT_AMOUNT /*折扣金额*/
                                  FROM FACT_GOODS_SALES ODU2
                                 WHERE ODU2.CANCEL_STATE = 1
                                   AND ODU2.CANCEL_BEFORE_STATE = 1 /*发货前取消的订单才虚拟出记录*/
                                   AND ODU2.POSTING_DATE_KEY <= ODU2.UPDATE_TIME
                                      /*2018-03-15剔除扫码购销售，FACT_EC_ORDER_2.order_from=76为扫码购销售*/
                                   AND NOT EXISTS
                                 (SELECT 1
                                          FROM FACT_EC_ORDER_2 FEO
                                         WHERE ODU2.ORDER_KEY = FEO.CRM_ORDER_NO
                                           AND FEO.ORDER_FROM = '76')) OD
                         WHERE OD.POSTING_DATE_KEY = &IN_POSTING_DATE_KEY
                           AND OD.TRAN_TYPE = 0 /*只显示主品*/
                        ) OD1
                 GROUP BY OD1.GOODS_KEY,
                          OD1.GOODS_COMMON_KEY,
                          OD1.SALES_SOURCE_SECOND_KEY,
                          DECODE(OD1.TRAN_TYPE, 0, '主品', 1, '赠品'),
                          DECODE(OD1.CANCEL_STATE, 0, 'TAN', 1, 'REN'),
                          OD1.MD_PERSON,
                          OD1.POSTING_DATE_KEY,
                          DECODE(OD1.LIVE_OR_REPLAY,
                                 '10',
                                 '直播',
                                 '01',
                                 '重播',
                                 '未分配'),
                          OD1.CANCEL_STATE) OD2) A1
 WHERE A1.SALES_SOURCE_SECOND_KEY = 20017
   AND A1.GOODS_COMMON_KEY = 235272
