/*
9/1-11/30未订购但两年之内订购过的用户BP
*/
--订购
SELECT TO_NUMBER(A.CUST_NO) MEMBER_BP,
       MAX(A.ADD_TIME) MAX_ADD_TIME,
       SUM(A.ORDER_AMOUNT) ORDER_AMOUNT,
       COUNT(DISTINCT A.ORDER_ID) ORDER_CNT
  FROM FACT_EC_ORDER_2 A, FACT_EC_ORDER_GOODS B
 WHERE A.ORDER_ID = B.ORDER_ID
   AND A.ADD_TIME BETWEEN DATE '2017-01-01' AND DATE '2018-11-30'
   AND A.ORDER_STATE >= 20
   AND A.CUST_NO <> 0
   AND NOT EXISTS
 (SELECT 1
          FROM (SELECT D.CUST_NO
                  FROM FACT_EC_ORDER_2 D
                 WHERE D.ADD_TIME BETWEEN DATE '2018-09-01' AND DATE
                 '2018-11-30'
                   AND D.ORDER_STATE >= 20
                   AND D.CUST_NO <> 0) C
         WHERE A.CUST_NO = C.CUST_NO)
 GROUP BY A.CUST_NO
 ORDER BY 3 DESC, 4 DESC;
