SELECT * FROM DBA_TABLES A WHERE A.TABLESPACE_NAME='ACQUISITION_DATA';
SELECT DISTINCT A.TABLESPACE_NAME FROM DBA_TABLES A;
SELECT *
  FROM ALL_ALL_TABLES A
 WHERE A.tablespace_name = 'ACQUISITION_DATA';
