--1.运营模块页面表
SELECT *
  FROM FACT_DAILY_GOODPAGE A
 WHERE A.VISIT_DATE_KEY = 20180914
   AND A.PAGE_NAME = 'KFZT'
   AND A.PAGE_VALUE = 'PriceDwonLive';

--2.运营模块商品表
SELECT *
  FROM FACT_DAILY_GOODORDER A
 WHERE A.VISIT_DATE_KEY = 20180913
   AND A.PAGE_NAME = 'KFZT'
   AND A.PAGE_VALUE = 'PriceDwonLive';

--3.
SELECT PAGE_KEY 页面KEY,
       to_date(VISIT_DATE_KEY, 'YYYY-MM-DD HH24:MI:ss') 统计日期,
       APPLICATION_NM 应用渠道名称,
       AVG(TOTALUV) 页面总UV,
       PAGE_VALUE 页面值,
       AVG(TOTALPV) 页面总PV
  FROM fact_daily_goodpage
 where VISIT_DATE_KEY = 20180913
   --AND PAGE_VALUE = 'PriceDwonLive'
 GROUP BY APPLICATION_NM, VISIT_DATE_KEY, PAGE_KEY, PAGE_VALUE;

--tmp
SELECT *
  FROM FACT_DAILY_GOODPAGE A
 WHERE A.VISIT_DATE_KEY = 20180913
   AND A.PAGE_NAME = 'KFZT'
   AND A.PAGE_VALUE = 'Games0830wechat';
SELECT *
  FROM FACT_DAILY_GOODORDER A
 WHERE A.VISIT_DATE_KEY = 20180913
   AND A.PAGE_NAME = 'KFZT'
   AND A.PAGE_VALUE = 'Games0830wechat';
