SELECT * FROM FACT_PT_ORDER;

SELECT A.ORDER_TYPE, COUNT(1) FROM FACT_EC_ORDER_2 A GROUP BY A.ORDER_TYPE;

SELECT *
  FROM W_ETL_LOG A
 WHERE A.PROC_NAME = 'processmemberpageorder'
 ORDER BY A.START_TIME DESC;

--
ALTER TABLE DW_USER.FACT_MEMBER_PAGE_ORDER MOVE PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DW_USER.FMPO_MEMBER_KEY REBUILD PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DW_USER.FMPO_DAY_KEY REBUILD PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DW_USER.FMPO_MEMBER_KEY NOPARALLEL;
ALTER INDEX DW_USER.FMPO_DAY_KEY NOPARALLEL;
--
ALTER TABLE DW_USER.FACT_MEMBER_PAGE_ORDER_TOTAL MOVE PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DW_USER.FMPOT_MEMBER_KEY REBUILD PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DW_USER.FMPOT_ITEM_CODE REBUILD PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DW_USER.FMPOT_MEMBER_KEY NOPARALLEL;
ALTER INDEX DW_USER.FMPOT_ITEM_CODE NOPARALLEL;

SELECT *
  FROM (SELECT 603007956 MEMBER_KEY, 44 COL1
          FROM DUAL
        UNION ALL
        SELECT 1102299867 MEMBER_KEY, 32 COL1
          FROM DUAL) TAB_A
  FULL OUTER JOIN (SELECT 1310185425 MEMBER_KEY, 12 COL2
                     FROM DUAL
                   UNION ALL
                   SELECT 1102299867 MEMBER_KEY, 11 COL2
                     FROM DUAL) TAB_B
    ON TAB_A.MEMBER_KEY = TAB_B.MEMBER_KEY;

SELECT NVL(TAB_A.MEMBER_KEY, TAB_B.MEMBER_KEY) MEMBER_KEY,
       NVL(TAB_A.COL1, 0) COL1,
       NVL(TAB_B.COL2, 0) COL2
  FROM (SELECT 603007956 MEMBER_KEY, 44 COL1
          FROM DUAL
        UNION ALL
        SELECT 1102299867 MEMBER_KEY, 32 COL1
          FROM DUAL) TAB_A
  FULL OUTER JOIN (SELECT 1310185425 MEMBER_KEY, 12 COL2
                     FROM DUAL
                   UNION ALL
                   SELECT 1102299867 MEMBER_KEY, 11 COL2
                     FROM DUAL) TAB_B
    ON TAB_A.MEMBER_KEY = TAB_B.MEMBER_KEY;
