--1.
SELECT A.POSTING_DATE_KEY, SUM(A.REJECT_AMOUNT)
  FROM OPER_PRODUCT_DAILY_REPORT A
 WHERE A.POSTING_DATE_KEY = 20180121
 GROUP BY A.POSTING_DATE_KEY;

SELECT A.POSTING_DATE_KEY, SUM(A.ORDER_AMOUNT)
  FROM FACT_GOODS_SALES A
 WHERE A.POSTING_DATE_KEY = 20180121
   AND A.TRAN_TYPE = 0
   AND A.ORDER_STATE = 1
 GROUP BY A.POSTING_DATE_KEY;

SELECT A.POSTING_DATE_KEY, SUM(A.ORDER_AMOUNT)
  FROM FACT_GOODS_SALES_REVERSE A
 WHERE A.POSTING_DATE_KEY = 20180121
 GROUP BY A.POSTING_DATE_KEY;

SELECT A.CRMPOSTDAT, A.CRM_PRCTYP, COUNT(1)
  FROM ODSHAPPIGO.ODS_ORDER A
 WHERE A.CRMPOSTDAT = '20180121'
 GROUP BY A.CRMPOSTDAT, A.CRM_PRCTYP
 ORDER BY A.CRMPOSTDAT, A.CRM_PRCTYP;

--2.
SELECT DISTINCT LENGTH(A.ITEM_CODE)
  FROM OPER_PRODUCT_DAILY_REPORT A
 WHERE A.POSTING_DATE_KEY = 20180121;

SELECT * FROM FACT_GOODS_SALES A WHERE A.POSTING_DATE_KEY = 20180121;
SELECT * FROM ALL_COL_COMMENTS A WHERE A.COLUMN_NAME LIKE '%SUPPLIER%';
SELECT * FROM odshappigo.ods_vendor;

SELECT *
  FROM FACT_GOODS_SALES A
 WHERE A.POSTING_DATE_KEY BETWEEN 20170101 AND 20171231
   AND A.GOODS_COMMON_KEY = 203684;

SELECT *
  FROM (SELECT TRUNC(A.ZVENDOR) ZVENDOR, A.ZVEN_NAME
          FROM odshappigo.ods_vendor A
         WHERE A.ZVENDOR =
               TRANSLATE(A.ZVENDOR,
                         '0' || TRANSLATE(A.ZVENDOR, '#0123456789', '#'),
                         '0')) B
 WHERE B.ZVENDOR = 105454;

SELECT TO_NUMBER('0012'), TRUNC('0012') FROM DUAL;
