--1.
SELECT * FROM ALL_ALL_TABLES A WHERE A.PARTITIONED='YES';
/*
DW_USER FACT_SESSION
DW_USER DATA_ACQUISITION_ITEM
DW_USER MEMBER_LABEL_LINK
DW_USER FACT_MEMBER_REGISTER
DW_USER DATA_ACQUISITION_ITEM_CURRENT
DW_USER FACT_PAGE_VIEW
DW_USER FACT_VISITOR_REGISTER
DW_USER DATA_ACQUISITION_ITEM_BASE
*/
