

select * from v$session_longops a where a.SID=29;
select * from v$session;

select * from sys.mysession;

processkillsession;


SELECT * FROM DBA_PART_TABLES A WHERE A.table_name = 'FACT_PAGE_VIEW';
SELECT * FROM DBA_TAB_PARTITIONS A WHERE A.table_name = 'FACT_PAGE_VIEW';

SELECT FILE# AS FILE_NUMBER,
       NAME AS NAME,
       CREATION_TIME AS CREATION_TIME,
       BLOCK_SIZE AS BLOCK_SIZE,
       BYTES / 1024 / 1024 / 1024 AS "FILE_SIZE(G)",
       CREATE_BYTES / 1024 / 1024 / 1024 AS "INIT_SIZE(G)",
       STATUS AS STATUS,
       ENABLED AS ENABLED
  FROM V$TEMPFILE;

SELECT USERNAME, TEMPORARY_TABLESPACE FROM DBA_USERS;

SELECT * FROM ALL_SOURCE A WHERE UPPER(A.TEXT) LIKE '%DIM_GOOD_COST%';

SELECT * FROM DIM_GOOD_COST;

SELECT * FROM OPER_EC_PRODUCT_SUMMARY_REPORT A WHERE A.COST_PRICE IS NOT NULL;

SELECT A.W_INSERT_DT, COUNT(1)
  FROM OPER_EC_PRODUCT_SUMMARY_REPORT A
 GROUP BY A.W_INSERT_DT
 ORDER BY A.W_INSERT_DT;

SELECT A.W_UPDATE_DT, COUNT(1)
  FROM OPER_EC_PRODUCT_SUMMARY_REPORT A
 GROUP BY A.W_UPDATE_DT;

SELECT COUNT(1) FROM OPER_EC_PRODUCT_SUMMARY_TMP A;

SELECT C3.ITEM_CODE,
       C3.COST_PRICE,
       C3.REPORT_DATE,
       C3.VALID_DATE,
       C3.CREATE_DATE,
       C3.SALE_PRICE
  FROM (SELECT C2.ITEM_CODE,
               C2.COST_PRICE,
               C2.REPORT_DATE,
               C2.VALID_DATE,
               C2.CREATE_DATE,
               C2.SALE_PRICE,
               ROW_NUMBER() OVER(PARTITION BY C2.ITEM_CODE ORDER BY C2.REPORT_DATE DESC) RN
          FROM DIM_GOOD_COST C2
         WHERE C2.VALID_DATE =
               TRANSLATE(C2.VALID_DATE,
                         '0' || TRANSLATE(C2.VALID_DATE, '#0123456789', '#'),
                         '0')) C3
 WHERE C3.RN = 1;
