SELECT *
  FROM ALL_SOURCE A
 WHERE UPPER(A.TEXT) LIKE '%KPI_VID_FIRST_VISIT%';
 
SELECT * FROM KPI_VID_FIRST_VISIT;

SELECT * FROM ALL_ALL_TABLES A WHERE A.table_name LIKE '%ORDER%';
SELECT * FROM ALL_COL_COMMENTS A WHERE A.COLUMN_NAME LIKE '%VID%';

SELECT * FROM FACT_GOODS_SALES;
