--1.新老会员
DROP TABLE YANGJIN.MEMBER_NEW_OLD PURGE;
CREATE TABLE YANGJIN.MEMBER_NEW_OLD AS
SELECT C.MEMBER_BP, C.FIRST_ORDER_ID, C.MIN_ORDER_DATE, C.ORDER_TYPE
  FROM (SELECT TO_NUMBER(B.CUST_NO) MEMBER_BP,
               B.ORDER_ID FIRST_ORDER_ID,
               TO_NUMBER(TO_CHAR(B.ADD_TIME, 'YYYYMMDD')) MIN_ORDER_DATE,
               B.ORDER_TYPE,
               RANK() OVER(PARTITION BY B.CUST_NO ORDER BY B.ORDER_ID) RN
          FROM FACT_EC_ORDER_2 B
         WHERE B.ORDER_STATE >= 20) C
 WHERE C.RN = 1;

DROP TABLE YANGJIN.ORDER_1018_TMP PURGE;
CREATE TABLE YANGJIN.ORDER_1018_TMP AS
SELECT A.ORDER_ID,
       A.ERP_ORDER_NO,
       TO_NUMBER(TO_CHAR(A.ADD_TIME, 'YYYYMMDD')) ORDER_DATE,
       TO_NUMBER(A.CUST_NO) MEMBER_BP,
       A.ORDER_TYPE,
       B.GOODS_COMMONID,
       B.GOODS_NUM ORDER_QTY,
       B.GOODS_PAY_PRICE * B.GOODS_NUM ORDER_AMOUNT,
       C.COST_PRICE * B.GOODS_NUM ORDER_COST
  FROM FACT_EC_ORDER_2 A, FACT_EC_ORDER_GOODS B, FACT_GOODS_SALES C
 WHERE A.ORDER_ID = B.ORDER_ID
   AND A.CRM_ORDER_NO = C.ORDER_H_KEY
   AND A.ADD_TIME BETWEEN DATE '2018-08-06' AND DATE '2018-10-14'
   AND A.ORDER_STATE >= 20;

DROP TABLE YANGJIN.ORDER_1018_TMP1 PURGE;
CREATE TABLE YANGJIN.ORDER_1018_TMP1 AS
SELECT A.ORDER_ID,
       A.ERP_ORDER_NO,
       A.ORDER_DATE,
       A.MEMBER_BP,
       A.ORDER_TYPE,
       A.GOODS_COMMONID,
       A.ORDER_QTY,
       A.ORDER_AMOUNT,
       A.ORDER_COST,
       CASE
         WHEN B.MIN_ORDER_DATE BETWEEN 20180910 AND 20181014 AND
              B.ORDER_TYPE = 2 THEN
          1
         ELSE
          0
       END IS_NEW,
       CASE
         WHEN B.MIN_ORDER_DATE BETWEEN 20180910 AND 20181014 THEN
          1
         ELSE
          0
       END IS_NEW2,
			 CASE
         WHEN B.MIN_ORDER_DATE BETWEEN 20180806 AND 20180909 THEN
          1
         ELSE
          0
       END IS_NEW3
  FROM YANGJIN.ORDER_1018_TMP A, YANGJIN.MEMBER_NEW_OLD B
 WHERE A.MEMBER_BP = B.MEMBER_BP(+);
 
--2.拼拼拼商品客单价、客毛利 
SELECT A.IS_NEW,
       SUM(A.ORDER_AMOUNT) ORDER_AMOUNT,
       SUM(A.ORDER_AMOUNT - A.ORDER_COST) ORDER_PROFIT,
       COUNT(DISTINCT A.MEMBER_BP) MEMBER_COUNT
  FROM YANGJIN.ORDER_1018_TMP1 A
 WHERE A.ORDER_DATE BETWEEN 20180910 AND 20181014
   AND A.ORDER_TYPE = 2
 GROUP BY A.IS_NEW;
 
--3.普通商品客单价、客毛利 
SELECT A.IS_NEW,
       SUM(A.ORDER_AMOUNT) ORDER_AMOUNT,
       SUM(A.ORDER_AMOUNT - A.ORDER_COST) ORDER_PROFIT,
       COUNT(DISTINCT A.MEMBER_BP) MEMBER_COUNT
  FROM YANGJIN.ORDER_1018_TMP1 A
 WHERE A.ORDER_DATE BETWEEN 20180910 AND 20181014
   AND A.ORDER_TYPE = 1
 GROUP BY A.IS_NEW;
 
--4.整体客单价、客毛利 
SELECT A.IS_NEW,
       SUM(A.ORDER_AMOUNT) ORDER_AMOUNT,
       SUM(A.ORDER_AMOUNT - A.ORDER_COST) ORDER_PROFIT,
       COUNT(DISTINCT A.MEMBER_BP) MEMBER_COUNT
  FROM YANGJIN.ORDER_1018_TMP1 A
 WHERE A.ORDER_DATE BETWEEN 20180910 AND 20181014
 GROUP BY A.IS_NEW;
 
--5.常规会员（未买过拼拼拼商品的会员）客单价、客毛利
SELECT A.IS_NEW2,
       SUM(A.ORDER_AMOUNT) ORDER_AMOUNT,
       SUM(A.ORDER_AMOUNT - A.ORDER_COST) ORDER_PROFIT,
       COUNT(DISTINCT A.MEMBER_BP) MEMBER_COUNT
  FROM YANGJIN.ORDER_1018_TMP1 A
 WHERE A.ORDER_DATE BETWEEN 20180910 AND 20181014
   AND NOT EXISTS (SELECT 1
          FROM YANGJIN.ORDER_1018_TMP1 B
         WHERE A.MEMBER_BP = B.MEMBER_BP
           AND B.ORDER_TYPE = 2)
 GROUP BY A.IS_NEW2;

--08.06~09.09 
SELECT A.IS_NEW3,
       SUM(A.ORDER_AMOUNT) ORDER_AMOUNT,
       SUM(A.ORDER_AMOUNT - A.ORDER_COST) ORDER_PROFIT,
       COUNT(DISTINCT A.MEMBER_BP) MEMBER_COUNT
  FROM YANGJIN.ORDER_1018_TMP1 A
 WHERE A.ORDER_DATE BETWEEN 20180806 AND 20180909
   AND NOT EXISTS (SELECT 1
          FROM YANGJIN.ORDER_1018_TMP1 B
         WHERE A.MEMBER_BP = B.MEMBER_BP
           AND B.ORDER_TYPE = 2)
 GROUP BY A.IS_NEW3;

--TMP
SELECT B.*
  FROM FACT_EC_ORDER_2 A, FACT_EC_ORDER_GOODS B,FACT_GOODS_SALES C
 WHERE A.ORDER_ID=B.ORDER_ID AND A.CRM_ORDER_NO=C.ORDER_H_KEY
 AND A.ADD_TIME BETWEEN DATE '2018-09-10' AND DATE
 '2018-10-14'
   AND A.ORDER_STATE >= 20;

--3.



SELECT * FROM FACT_ORDER;
SELECT * FROM FACT_GOODS_SALES;

SELECT DATE '2018-10-14' - DATE '2018-09-10',
       DATE '2018-09-09' - DATE '2018-08-06'
  FROM DUAL;
