SELECT *
  FROM W_ETL_LOG A
 WHERE A.PROC_NAME = 'processvisitor_active'
 ORDER BY A.START_TIME DESC;

SELECT *
  FROM ALL_SOURCE A
 WHERE UPPER(A.TEXT) LIKE '%INSERT INTO FACT_VISITOR_ACTIVE%';

SELECT TO_CHAR(A.VISIT_DATE, 'YYYY-MM-DD HH24') T, COUNT(1)
  FROM FACT_PAGE_VIEW A
 WHERE A.VISIT_DATE_KEY >= 20180911
 GROUP BY TO_CHAR(A.VISIT_DATE, 'YYYY-MM-DD HH24')
 ORDER BY TO_CHAR(A.VISIT_DATE, 'YYYY-MM-DD HH24');

SELECT TO_CHAR(A.VISIT_DATE, 'YYYYMMDD HH24:MI') T, COUNT(1)
  FROM FACT_PAGE_VIEW A
 WHERE A.VISIT_DATE_KEY = 20180912
 GROUP BY TO_CHAR(A.VISIT_DATE, 'YYYYMMDD HH24:MI')
 ORDER BY TO_CHAR(A.VISIT_DATE, 'YYYYMMDD HH24:MI');

SELECT (SELECT MAX(ID) FROM FACT_PAGE_VIEW) - (SELECT ID FROM W_ACTIVE_NUM)
  FROM DUAL;
