/*
前提：拼拼拼的老会员(9.10-10.14订购过拼拼拼商品，首单日期<=09.10)
日期范围：9.10-10.14
其他逻辑：时间段内订购的普通商品件数
捞取拼拼拼的老会员普通商品的复购率
*/
--1.
TRUNCATE TABLE YANGJIN.MEMBER_TMP;
INSERT INTO YANGJIN.MEMBER_TMP
select DISTINCT A.MEMBER_BP
  from YANGJIN.ORDER_1018_TMP A
 WHERE A.ORDER_DATE BETWEEN 20180910 AND 20181014
   AND A.ORDER_TYPE = 2
   AND EXISTS (SELECT 1
          FROM YANGJIN.MEMBER_NEW_OLD B
         WHERE A.MEMBER_BP = B.MEMBER_BP
           AND B.MIN_ORDER_DATE < 20180910)
 ORDER BY A.MEMBER_BP;
			
--2.订购普通商品人数
SELECT COUNT(C.MEMBER_BP) MEMBER_COUNT
  FROM (SELECT DISTINCT A.MEMBER_BP
          FROM YANGJIN.ORDER_1018_TMP A
         WHERE A.ORDER_DATE BETWEEN 20180910 AND 20181014
           AND A.ORDER_TYPE = 1
           AND EXISTS (SELECT 1
                  FROM YANGJIN.MEMBER_TMP B
                 WHERE A.MEMBER_BP = B.MEMBER_KEY)) C;

--3.订购二次普通商品人数
SELECT COUNT(C.MEMBER_BP) MEMBER_COUNT
  FROM (SELECT A.MEMBER_BP, COUNT(DISTINCT A.ORDER_ID) ORDER_CNT
          FROM YANGJIN.ORDER_1018_TMP A
         WHERE A.ORDER_DATE BETWEEN 20180910 AND 20181014
           AND A.ORDER_TYPE = 1
           AND EXISTS (SELECT 1
                  FROM YANGJIN.MEMBER_TMP B
                 WHERE A.MEMBER_BP = B.MEMBER_KEY)
         GROUP BY A.MEMBER_BP
        HAVING COUNT(DISTINCT A.ORDER_ID) > 1) C;

--4.
SELECT 657/1129 FROM DUAL;
