SELECT T.MANUAL_ID,
       T.ITEM_CODE,
       T.COMMON_ID,
       T.ZMALAB,
       T.ZLABNAME,
       T.ZMALABTXT,
       T.CHECKED,
       T.ADD_TIME,
       T.SHOW_SORT
  FROM FACT_EC_GOODS_MANUAL T;
