/*
捞取新媒体11月4日-11月7日未登录过APP的黄金，白金，钻石，VIP会员BP号和20180101至今的订购次数
*/
--11月4日-11月7日未登录过APP的黄金，白金，钻石，VIP会员BP号
CREATE TABLE YANGJIN.MEMBER_TMP1 AS
SELECT A.MEMBER_BP
  FROM DIM_MEMBER A
 WHERE A.MEMBER_LEVEL IN ('HAPP_T3', 'HAPP_T4', 'HAPP_T5', 'HAPP_T6')
   AND NOT EXISTS
 (SELECT 1 FROM YANGJIN.MEMBER_TMP C WHERE A.MEMBER_BP = C.MEMBER_KEY)
 ORDER BY A.MEMBER_BP;

--浏览
TRUNCATE TABLE YANGJIN.MEMBER_TMP;
INSERT INTO YANGJIN.MEMBER_TMP
  SELECT DISTINCT B.MEMBER_KEY
    FROM FACT_PAGE_VIEW B
   WHERE B.VISIT_DATE_KEY BETWEEN 20181104 AND 20181107
     AND B.MEMBER_KEY <> 0;
COMMIT;

--20180101至今的订购次数
SELECT TO_NUMBER(A.CUST_NO) MEMBER_BP, COUNT(1) ORDER_COUNT
  FROM FACT_EC_ORDER_2 A
 WHERE A.ADD_TIME >= DATE '2018-01-01'
   AND EXISTS
 (SELECT 1 FROM YANGJIN.MEMBER_TMP1 B WHERE A.CUST_NO = B.MEMBER_BP)
 GROUP BY A.CUST_NO
 ORDER BY COUNT(1) DESC;
