/*
20170101-20170631      
20180101-20180631   
整体  TV转化率  自营转化率
*/
--1.整体-------------------------------------------------------------
--临时表
DROP TABLE YANGJIN.FACT_PAGE_VIEW_2018_F;
CREATE TABLE YANGJIN.FACT_PAGE_VIEW_2018_F AS
SELECT A.VID,A.PAGE_VALUE
  FROM FACT_PAGE_VIEW A
 WHERE A.VISIT_DATE_KEY BETWEEN 20180101 AND 20180630
   AND A.PAGE_NAME IN ('Good', 'good')
   AND A.PAGE_VALUE =
       TRANSLATE(A.PAGE_VALUE,
                 '0' || TRANSLATE(A.PAGE_VALUE, '#0123456789', '#'),
                 '0');

--PV
SELECT COUNT(DISTINCT A.VID)
  FROM YANGJIN.FACT_PAGE_VIEW_2018_F A
 WHERE EXISTS (SELECT 1
          FROM DIM_EC_GOOD B
         WHERE A.PAGE_VALUE = TO_CHAR(B.GOODS_COMMONID)
           AND B.MATDL IN (30, 31));

--ORDER
SELECT COUNT(DISTINCT C.VID)
  FROM FACT_EC_ORDER_2 C, FACT_EC_ORDER_GOODS D
 WHERE C.ORDER_ID = D.ORDER_ID
   AND TRUNC(C.ADD_TIME) BETWEEN DATE '2018-01-01' AND DATE
 '2018-06-30'
   AND EXISTS (SELECT 1
          FROM DIM_EC_GOOD E
         WHERE D.GOODS_COMMONID = E.GOODS_COMMONID
           AND E.MATDL IN (30, 31));

--2.TV转化率-------------------------------------------------------------
--PV
SELECT COUNT(DISTINCT A.VID)
  FROM YANGJIN.FACT_PAGE_VIEW_2017_F A
 WHERE EXISTS (SELECT 1
          FROM DIM_EC_GOOD B
         WHERE A.PAGE_VALUE = TO_CHAR(B.GOODS_COMMONID)
           AND B.MATDL IN (30, 31)
					 AND B.IS_TV=1);

--ORDER
SELECT COUNT(DISTINCT C.VID)
  FROM FACT_EC_ORDER_2 C, FACT_EC_ORDER_GOODS D
 WHERE C.ORDER_ID = D.ORDER_ID
   AND TRUNC(C.ADD_TIME) BETWEEN DATE '2017-01-01' AND DATE
 '2017-06-30'
   AND EXISTS (SELECT 1
          FROM DIM_EC_GOOD E
         WHERE D.GOODS_COMMONID = E.GOODS_COMMONID
           AND E.MATDL IN (30, 31)
					 AND E.IS_TV=1);


--3.自营转化率-------------------------------------------------------------
--PV
SELECT COUNT(DISTINCT A.VID)
  FROM YANGJIN.FACT_PAGE_VIEW_2017_F A
 WHERE EXISTS (SELECT 1
          FROM DIM_EC_GOOD B
         WHERE A.PAGE_VALUE = TO_CHAR(B.GOODS_COMMONID)
           AND B.MATDL IN (30, 31)
           AND B.IS_OWN_SHOP = 1
           AND B.STORE_ID = 1
           AND B.IS_TV = 0);

--ORDER
SELECT COUNT(DISTINCT C.VID)
  FROM FACT_EC_ORDER_2 C, FACT_EC_ORDER_GOODS D
 WHERE C.ORDER_ID = D.ORDER_ID
   AND TRUNC(C.ADD_TIME) BETWEEN DATE '2017-01-01' AND DATE
 '2017-06-30'
   AND EXISTS (SELECT 1
          FROM DIM_EC_GOOD E
         WHERE D.GOODS_COMMONID = E.GOODS_COMMONID
           AND E.MATDL IN (30, 31)
					 AND E.IS_OWN_SHOP=1
           AND E.STORE_ID = 1
           AND E.IS_TV = 0);

