--1.
MERGE /*+APPEND*/
INTO KPI_ASMT_WX_DAU T
USING (SELECT SUBSTR(A.VISIT_DATE_KEY, 1, 6) MONTH_KEY,
              ROUND(AVG(NVL(A.UVCNT, 0) + NVL(A.LITEUVCNT, 0))) DAU,
              SYSDATE W_INSERT_DT,
              SYSDATE W_UPDATE_DT
         FROM FACT_DAILY_WX A
        WHERE A.VISIT_DATE_KEY BETWEEN &V_MONTH_FIRST_DATE_KEY AND
              &IN_DATE_KEY
        GROUP BY SUBSTR(A.VISIT_DATE_KEY, 1, 6)) S
ON (T.MONTH_KEY = S.MONTH_KEY)
WHEN MATCHED THEN
  UPDATE SET T.DAU = S.DAU, T.W_UPDATE_DT = S.W_UPDATE_DT
WHEN NOT MATCHED THEN
  INSERT
    (T.MONTH_KEY, T.DAU, T.W_INSERT_DT, T.W_UPDATE_DT)
  VALUES
    (S.MONTH_KEY, S.DAU, S.W_INSERT_DT, S.W_UPDATE_DT);

--
select MIN(T.VISIT_DATE_KEY)
  from FACT_DAILY_WX t
 WHERE T.LITEUVCNT IS NOT NULL;
 
SELECT * FROM KPI_ASMT_WX_DAU;

SELECT * FROM kpi_asmt_total_month FOR UPDATE;
