--FIRST_ORDER_SOURCE_KEY,FIRST_ORDER_DATE_KEY
CREATE TABLE YANGJIN.DIM_MEMBER_TMP AS
SELECT D.MEMBER_BP,
       D.FIRST_ORDER_SOURCE_KEY S_FIRST_ORDER_SOURCE_KEY,
       D.FIRST_ORDER_DATE_KEY S_FIRST_ORDER_DATE_KEY,
       C.FIRST_ORDER_SOURCE_KEY T_FIRST_ORDER_SOURCE_KEY,
       C.FIRST_ORDER_DATE_KEY T_FIRST_ORDER_DATE_KEY
  FROM (SELECT B.MEMBER_KEY,
               B.FIRST_ORDER_SOURCE_KEY,
               B.FIRST_ORDER_DATE_KEY
          FROM (SELECT A.MEMBER_KEY,
                       A.ORDER_KEY,
                       A.ORDER_DATE_KEY FIRST_ORDER_DATE_KEY,
                       A.SALES_SOURCE_KEY FIRST_ORDER_SOURCE_KEY,
                       RANK() OVER(PARTITION BY A.MEMBER_KEY ORDER BY A.ORDER_KEY) RO
                  FROM FACT_ORDER A) B
         WHERE B.RO = 1) C,
       DIM_MEMBER D
 WHERE D.MEMBER_BP = C.MEMBER_KEY;

UPDATE DIM_MEMBER A
   SET (A.FIRST_ORDER_SOURCE_KEY, A.FIRST_ORDER_DATE_KEY) =
       (SELECT C.T_FIRST_ORDER_SOURCE_KEY, C.T_FIRST_ORDER_DATE_KEY
          FROM YANGJIN.DIM_MEMBER_TMP C
         WHERE A.MEMBER_BP = C.MEMBER_BP)
 WHERE (A.FIRST_ORDER_SOURCE_KEY = 0 OR A.FIRST_ORDER_DATE_KEY = 0)
   AND EXISTS (SELECT 1
          FROM YANGJIN.DIM_MEMBER_TMP B
         WHERE A.MEMBER_BP = B.MEMBER_BP);

--FIRSTW_ORDER_SOURCE_KEY,FIRSTW_ORDER_DATE_KEY
CREATE TABLE YANGJIN.DIM_MEMBER_TMP1 AS
SELECT D.MEMBER_BP,
       D.FIRST_ORDER_SOURCE_KEY S_FIRST_ORDER_SOURCE_KEY,
       D.FIRST_ORDER_DATE_KEY S_FIRST_ORDER_DATE_KEY,
       C.FIRST_ORDER_SOURCE_KEY T_FIRST_ORDER_SOURCE_KEY,
       C.FIRST_ORDER_DATE_KEY T_FIRST_ORDER_DATE_KEY
  FROM (SELECT B.MEMBER_KEY,
               B.FIRST_ORDER_SOURCE_KEY,
               B.FIRST_ORDER_DATE_KEY
          FROM (SELECT A.CUST_NO MEMBER_KEY,
                       A.ORDER_ID,
                       TO_CHAR(TRUNC(A.ADD_TIME),'YYYYMMDD') FIRST_ORDER_DATE_KEY,
                       A. FIRST_ORDER_SOURCE_KEY,
                       RANK() OVER(PARTITION BY A.CUST_NO ORDER BY A.ORDER_ID) RO
                  FROM FACT_EC_ORDER_2 A) B
         WHERE B.RO = 1) C,
       DIM_MEMBER D
 WHERE D.MEMBER_BP = C.MEMBER_KEY;
