/*
20180701-20181014  3个月内订购过但10月15.16.17.18.19没有过登录的黄金以及以下会员
黄金会员：HAPP_T0,HAPP_T1,HAPP_T2,HAPP_T3
*/
--订购
SELECT A2.MEMBER_BP, A2.ORDER_CNT, A3.MEMBER_LEVEL
  FROM (SELECT F.MEMBER_BP, F.ORDER_CNT
          FROM (SELECT TO_NUMBER(A.CUST_NO) MEMBER_BP,
                       COUNT(DISTINCT A.ORDER_ID) ORDER_CNT
                  FROM FACT_EC_ORDER_2 A
                 WHERE A.ADD_TIME BETWEEN DATE '2018-07-01' AND DATE
                 '2018-10-14'
                   AND A.ORDER_STATE >= 20
                   AND A.CUST_NO <> 0
                 GROUP BY A.CUST_NO) F
         WHERE NOT EXISTS
         (SELECT 1
                  FROM (SELECT DISTINCT A.MEMBER_KEY MEMBER_BP
                          FROM FACT_PAGE_VIEW A
                         WHERE A.MEMBER_KEY <> 0
                           AND A.VISIT_DATE_KEY BETWEEN 20181015 AND 20181019) A1
                 WHERE F.MEMBER_BP = A1.MEMBER_BP)
         ORDER BY F.ORDER_CNT DESC, F.MEMBER_BP) A2,
       DIM_MEMBER A3
 WHERE A2.MEMBER_BP = A3.MEMBER_BP
   AND A3.MEMBER_LEVEL IN ('HAPP_T0', 'HAPP_T1', 'HAPP_T2', 'HAPP_T3')
 ORDER BY A2.ORDER_CNT DESC;

--浏览
SELECT DISTINCT A.MEMBER_KEY MEMBER_BP
  FROM FACT_PAGE_VIEW A
 WHERE A.MEMBER_KEY <> 0
   AND A.VISIT_DATE_KEY BETWEEN 20181015 AND 20181019;

--tmp
SELECT * FROM DIM_MEMBER;
SELECT * FROM FACT_ECMEMBER;
