--10月18日晚20:00-10月21日24点
--1.快乐币使用
SELECT C.MEMBER_BP, C.MEMBER_LEVEL, B.ORDER_AMOUNT, B.INTEGRALS_AMOUNT
  FROM (SELECT TO_NUMBER(A.CUST_NO) MEMBER_BP,
               SUM(A.ORDER_AMOUNT) ORDER_AMOUNT,
               SUM(A.INTEGRALS_AMOUNT) INTEGRALS_AMOUNT
          FROM FACT_EC_ORDER_2 A
         WHERE A.ADD_TIME BETWEEN DATE '2018-10-18'+8/24 AND DATE
         '2018-10-21'
           AND A.ORDER_STATE >= 20
           AND A.INTEGRALS_AMOUNT > 0
         GROUP BY A.CUST_NO) B,
       DIM_MEMBER C
 WHERE B.MEMBER_BP = C.MEMBER_BP;

--2.会员购买商品
SELECT TO_NUMBER(A.CUST_NO) MEMBER_BP,
       B.ERP_CODE,
       B.GOODS_NAME,
       B.GOODS_PRICE
  FROM FACT_EC_ORDER_2 A, FACT_EC_ORDER_GOODS B
 WHERE A.ORDER_ID = B.ORDER_ID
   AND A.ADD_TIME BETWEEN DATE '2018-10-18'+8/24 AND DATE
 '2018-10-21'
   AND A.ORDER_STATE >= 20
   AND A.INTEGRALS_AMOUNT > 0;

--3.
SELECT COUNT(A.ORDER_ID) ORDER_COUNT, SUM(A.ORDER_AMOUNT) ORDER_AMOUNT
  FROM FACT_EC_ORDER_2 A
 WHERE A.ADD_TIME BETWEEN DATE '2018-10-18' + 8 / 24 AND DATE
 '2018-10-21'
   AND A.ORDER_STATE >= 20;

SELECT C.MEMBER_BP, C.MEMBER_LEVEL, B.INTEGRALS_AMOUNT
  FROM (SELECT TO_NUMBER(A.CUST_NO) MEMBER_BP,
               SUM(A.ORDER_AMOUNT) ORDER_AMOUNT,
               SUM(A.INTEGRALS_AMOUNT) INTEGRALS_AMOUNT
          FROM FACT_EC_ORDER_2 A
         WHERE A.ADD_TIME BETWEEN DATE '2018-10-01' AND DATE
         '2018-10-31'
           AND A.ORDER_STATE >= 20
           AND A.INTEGRALS_AMOUNT > 0
         GROUP BY A.CUST_NO) B,
       DIM_MEMBER C
 WHERE B.MEMBER_BP = C.MEMBER_BP;

SELECT * FROM FACT_EC_ORDER;
SELECT * FROM FACT_EC_ORDER_2;
SELECT DATE'2018-10-01'+8/24+30/60/24 FROM DUAL;
