--1.
SELECT *
  FROM W_ETL_LOG A
 WHERE A.PROC_NAME = 'processgoodpage'
 ORDER BY A.START_TIME DESC;
 
SELECT *
  FROM W_ETL_LOG A
 WHERE A.PROC_NAME = 'processpagerelation'
 ORDER BY A.START_TIME DESC;

--2.
DROP TABLE YANGJIN.FACT_PAGE_VIEW_ID_TMP PURGE;
CREATE TABLE YANGJIN.FACT_PAGE_VIEW_ID_TMP AS
SELECT A.ID, COUNT(1) CNT
  FROM FACT_PAGE_VIEW A
 WHERE A.VISIT_DATE_KEY BETWEEN 20181121 AND 20181122
 GROUP BY A.ID
HAVING COUNT(1) > 1;

--3.
DROP TABLE YANGJIN.FACT_PAGE_VIEW_ID_TMP1 PURGE;
CREATE TABLE YANGJIN.FACT_PAGE_VIEW_ID_TMP1 AS
SELECT B.ID, MAX(ROWID) MAXROWID
  FROM FACT_PAGE_VIEW B
 WHERE B.VISIT_DATE_KEY BETWEEN 20181121 AND 20181122
   AND EXISTS
 (SELECT 1 FROM YANGJIN.FACT_PAGE_VIEW_ID_TMP C WHERE B.ID = C.ID)
 GROUP BY B.ID
 ORDER BY B.ID;
 
--4.
DELETE FROM FACT_PAGE_VIEW A
 WHERE A.VISIT_DATE_KEY BETWEEN 20181121 AND 20181122
   AND EXISTS (SELECT 1
          FROM YANGJIN.FACT_PAGE_VIEW_ID_TMP1 B
         WHERE A.ROWID = B.MAXROWID
           AND A.ID = B.ID);
					 
--tmp
select to_number(to_char(sysdate - 2, 'yyyymmdd')) as maxday,
       to_number(to_char(sysdate + 1, 'yyyymmdd')) as maxday2
  from dual;

SELECT MIN(B.ID), MAX(B.ID)
  FROM (SELECT A.ID, COUNT(1)
          FROM FACT_PAGE_VIEW A
         WHERE A.VISIT_DATE_KEY BETWEEN 20181112 AND 20181115
         GROUP BY A.ID
        HAVING COUNT(1) > 1) B;

SELECT * FROM FACT_PAGE_VIEW A WHERE A.ID=1351121537;
SELECT * FROM FACT_PAGE_VIEW A WHERE A.ID=1351121538;
SELECT * FROM FACT_PAGE_VIEW A WHERE A.ID=1351121539;
SELECT * FROM FACT_PAGE_VIEW A WHERE A.ID=1351121540;

SELECT MIN(ROWID), A.ID
  FROM FACT_PAGE_VIEW A
 WHERE A.ID = 1351121537
 GROUP BY A.ID;
SELECT * FROM FACT_PAGE_VIEW A WHERE A.ID=1351207614;

SELECT A.ID, COUNT(1) CNT
  FROM FACT_PAGE_VIEW A
 WHERE A.VISIT_DATE_KEY BETWEEN 20181111 AND 20181115
 GROUP BY A.ID
HAVING COUNT(1) > 1;





processgoodpage;
