/*
12/15-12/17的新媒体总的和单超级会员日专题的uv,订购人数，订购金额，客单价，件单价，使用快乐币的订单数和使用快乐币的总数。
*/
--1.订购人数，订购金额，客单价，件单价
SELECT SUM(C.ORDER_AMOUNT) 订购金额,
       COUNT(DISTINCT C.MEMBER_BP) 订购人数,
       SUM(C.ORDER_AMOUNT) / COUNT(DISTINCT C.MEMBER_BP) 客单价,
       SUM(C.ORDER_AMOUNT) / SUM(C.ORDER_QTY) 件单价
  FROM (SELECT A.ORDER_ID,
               TO_NUMBER(A.CUST_NO) MEMBER_BP,
               B.GOODS_COMMONID,
               B.GOODS_NUM ORDER_QTY,
               B.GOODS_PRICE * B.GOODS_NUM ORDER_AMOUNT
          FROM FACT_EC_ORDER_2 A, FACT_EC_ORDER_GOODS B
         WHERE A.ORDER_ID = B.ORDER_ID
           AND A.ADD_TIME BETWEEN DATE '2018-12-15' AND DATE
         '2018-12-17'
           AND A.ORDER_STATE >= 20) C;

--2.uv
SELECT COUNT(DISTINCT A.VID), COUNT(DISTINCT A.MEMBER_KEY)
  FROM FACT_PAGE_VIEW A
 WHERE A.VISIT_DATE_KEY BETWEEN 20181215 AND 20181217
   AND A.PAGE_NAME = 'KFZT'
   AND A.PAGE_VALUE = 'supervip181215';

--3.使用快乐币的订单数和使用快乐币的总数
SELECT COUNT(A.ORDER_ID) ORDER_CNT,
       SUM(A.INTEGRALS_AMOUNT) INTEGRALS_AMOUNT
  FROM FACT_EC_ORDER_2 A
 WHERE A.ADD_TIME BETWEEN DATE '2018-12-15' AND DATE
 '2018-12-17'
   AND A.ORDER_STATE >= 20
   AND A.INTEGRALS_AMOUNT > 0;
