--1.
SELECT A.VISIT_DATE_KEY, COUNT(1)
  FROM FACT_PAGE_VIEW A
 WHERE A.VISIT_DATE_KEY >= 20181110
 GROUP BY A.VISIT_DATE_KEY;
 
SELECT MAX(A.VISIT_DATE) FROM FACT_PAGE_VIEW A;

SELECT A.CREATEON
  FROM ODSHAPPIGO.ODS_PAGEVIEW A
 WHERE EXISTS (SELECT 1
          FROM (SELECT MAX(C.ID) ID FROM ODSHAPPIGO.ODS_PAGEVIEW C) B
         WHERE A.ID = B.ID);
				 
--2.
SELECT *
  FROM W_ETL_LOG A
 WHERE A.PROC_NAME = 'createpaveviewfact'
 ORDER BY A.START_TIME DESC;

--tmp
SELECT *
  FROM ALL_SOURCE A
 WHERE UPPER(A.TEXT) LIKE '%INSERT %FACT_PAGE_VIEW%';
CREATEPAVEVIEWFACT;

SELECT * FROM S_PARAMETERS2 FOR UPDATE;

SELECT A.ID, COUNT(1)
  FROM FACT_PAGE_VIEW A
 WHERE A.VISIT_DATE_KEY = 20181122
 GROUP BY A.ID
HAVING COUNT(1) > 1;

SELECT 299/88,(88*4-150)/4 FROM DUAL;

