DECLARE
  IN_DATE_INT NUMBER(8);
  IN_DATE     DATE;
  BEGIN_DATE  DATE := DATE '2018-01-17';
  END_DATE    DATE := DATE '2018-11-30';
BEGIN
  IN_DATE := BEGIN_DATE;
  WHILE IN_DATE <= END_DATE LOOP
    IN_DATE_INT := TO_CHAR(IN_DATE, 'YYYYMMDD');
    UPDATE FACT_PAGE_VIEW C
       SET C.APPLICATION_KEY =
           (SELECT D.APPLICATION_KEY
              FROM DIM_APPLICATION D
             WHERE D.APPLICATION_NAME = C.APPLICATION_NAME),
           C.CHANNEL_KEY    =
           (SELECT E.CHANNEL_KEY
              FROM DIM_APPLICATION E
             WHERE E.APPLICATION_NAME = C.APPLICATION_NAME)
     WHERE C.VISIT_DATE_KEY = IN_DATE_INT
       AND C.APPLICATION_KEY IS NULL;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE(IN_DATE);
    IN_DATE := IN_DATE + 1;
  END LOOP;
END;
/
