TRUNCATE TABLE YANGJIN.MEMBER_TMP;
SELECT * FROM YANGJIN.MEMBER_TMP FOR UPDATE;

SELECT A.MEMBER_KEY, B.MEMBER_TIME
  FROM YANGJIN.MEMBER_TMP A,
       (SELECT C.MEMBER_CRMBP, MIN(C.MEMBER_TIME) MEMBER_TIME
          FROM FACT_ECMEMBER C
         GROUP BY C.MEMBER_CRMBP) B
 WHERE A.MEMBER_KEY = B.MEMBER_CRMBP(+)
   AND NVL(B.MEMBER_TIME, 0) >= 20180427;

SELECT C.MEMBER_KEY, D.ORDER_COUNT, D.ORDER_QTY, D.ORDER_AMOUNT
  FROM YANGJIN.MEMBER_TMP C,
       (SELECT A.CUST_NO,
               COUNT(A.ORDER_ID) ORDER_COUNT,
               SUM(B.GOODS_NUM) ORDER_QTY,
               SUM(A.ORDER_AMOUNT) ORDER_AMOUNT
          FROM FACT_EC_ORDER_2 A, FACT_EC_ORDER_GOODS B
         WHERE A.ORDER_ID = B.ORDER_ID
           AND A.ADD_TIME BETWEEN DATE '2018-04-27' AND DATE
         '2018-05-10'
           AND A.ORDER_STATE >= 20
         GROUP BY A.CUST_NO) D
 WHERE C.MEMBER_KEY = D.CUST_NO(+)
 ORDER BY C.MEMBER_KEY;

SELECT * FROM FACT_ECMEMBER A WHERE A.MEMBER_CRMBP=1312533267;
SELECT A.MEMBER_CRMBP, COUNT(1)
  FROM FACT_ECMEMBER A
 GROUP BY A.MEMBER_CRMBP
HAVING COUNT(1) > 1;
