/*
20180101-20180931  浏览过投资收藏品类用户
*/
--浏览临时表
CREATE TABLE YANGJIN.FACT_PAGE_VIEW_2018_1_9 AS
  SELECT /*+PARALLEL(8)*/
  DISTINCT A.VISIT_DATE_KEY, A.MEMBER_KEY, A.PAGE_VALUE
    FROM FACT_PAGE_VIEW A
   WHERE A.VISIT_DATE_KEY BETWEEN 20180101 AND 20180831
     AND A.PAGE_NAME IN ('good', 'Good')
     AND A.MEMBER_KEY <> 0
     AND A.PAGE_VALUE =
         TRANSLATE(A.PAGE_VALUE,
                   '0' || TRANSLATE(A.PAGE_VALUE, '#0123456789', '#'),
                   '0');
--浏览
SELECT TO_NUMBER(A.MEMBER_KEY) MEMBER_BP,
       COUNT(DISTINCT A.PAGE_VALUE) ITEM_CNT
  FROM YANGJIN.FACT_PAGE_VIEW_2018_1_9 A
 WHERE A.MEMBER_KEY <> 0
   AND a.page_value =
       translate(a.page_value,
                 '0' || translate(a.page_value, '#0123456789', '#'),
                 '0')
   AND EXISTS (SELECT 1
          FROM (SELECT D.GOODS_COMMONID
                  FROM DIM_EC_GOOD D, DIM_GOOD_CLASS E
                 WHERE D.MATKL = E.MATKL
                   AND E.MATDL = 58) B
         WHERE A.PAGE_VALUE = B.GOODS_COMMONID)
 GROUP BY TO_NUMBER(A.MEMBER_KEY)
 ORDER BY COUNT(DISTINCT A.PAGE_VALUE) DESC;



--TMP
SELECT * FROM DIM_GOOD_CLASS A WHERE A.MATDLT LIKE '%收藏%';
SELECT * FROM DIM_GOOD_CLASS A WHERE A.MATZLT LIKE '%收藏%';
SELECT * FROM DIM_GOOD_CLASS A WHERE A.MATXLT LIKE '%收藏%';
SELECT * FROM DIM_GOOD_CLASS A WHERE A.Matklt LIKE '%收藏%';
