SELECT A.CRMPOSTDAT, COUNT(1)
  FROM ODSHAPPIGO.ODS_ORDER A
 GROUP BY A.CRMPOSTDAT
 ORDER BY A.CRMPOSTDAT;

DECLARE
  IN_DATE_INT NUMBER(8);
  IN_DATE     DATE;
  BEGIN_DATE  DATE := DATE '2018-03-01';
  END_DATE    DATE := DATE '2018-04-02';
BEGIN
  IN_DATE := BEGIN_DATE;
  WHILE IN_DATE <= END_DATE LOOP
    IN_DATE_INT := TO_CHAR(IN_DATE, 'YYYYMMDD');
    YANGJIN_PKG.FACT_GOODS_SALES_FIX(IN_DATE_INT, 'FACT');
    IN_DATE := IN_DATE + 1;
  END LOOP;
END;
/
DECLARE
  IN_DATE_INT NUMBER(8);
  IN_DATE     DATE;
  BEGIN_DATE  DATE := DATE '2018-03-01';
  END_DATE    DATE := DATE '2018-04-02';
BEGIN
  IN_DATE := BEGIN_DATE;
  WHILE IN_DATE <= END_DATE LOOP
    IN_DATE_INT := TO_CHAR(IN_DATE, 'YYYYMMDD');
    YANGJIN_PKG.FACT_GOODS_SALES_FIX(IN_DATE_INT, 'OPER');
    IN_DATE := IN_DATE + 1;
  END LOOP;
END;
