SELECT TO_CHAR(A.ORDER_SN) ORDER_SN,
       A.CUST_NO,
       A.MEMBER_LEVEL,
       A.ADD_TIME,
       A.GOODS_AMOUNT 商品总价格,
       A.ORDER_AMOUNT 订单总金额,
       A.APP_NAME,
       TO_CHAR(A.ERP_ORDER_NO) ERP_ORDER_NO,
       TO_CHAR(A.CRM_ORDER_NO) CRM_ORDER_NO,
       A.INTEGRALS_AMOUNT 积分抵扣金额,
       A.DISCOUNT_MANSONG_AMOUNT 订单满减折扣金额,
       A.DISCOUNT_PAYMENTWAY_AMOUNT 支付方式享受折扣,
       A.DISCOUNT_PAYMENTCHANEL_AMOUNT 支付渠道享受折扣,
       B.ERP_CODE 商品编码,
       B.GOODS_NAME 商品名称,
       B.GOODS_PRICE 商品价格,
       B.GOODS_NUM 订购件数,
       B.GOODS_PAY_PRICE 商品实际成交价,
       B.TV_DISCOUNT_AMOUNT TV直播立减金额,
       C.VOUCHER_NAME 代金券名称,
       C.VOUCHER_PRICE 代金券面额,
       C.VOUCHER_DESC 代金券备注,
       C.VOUCHER_REF EC的优惠券模板号,
       C.VOUCHER_CODE 代金券编码
  FROM FACT_EC_ORDER_2 A, FACT_EC_ORDER_GOODS B, FACT_EC_ORDER_COMMON C
 WHERE A.ORDER_ID = B.ORDER_ID
   AND A.ORDER_ID = C.ORDER_ID
   AND A.ADD_TIME BETWEEN DATE '2018-11-11' AND DATE
 '2018-11-12'
   AND A.ORDER_STATE >= 20
 ORDER BY A.ORDER_ID;

SELECT *
  FROM FACT_EC_ORDER_2 A, FACT_EC_ORDER_GOODS B, FACT_EC_ORDER_COMMON C
 WHERE A.ORDER_ID = B.ORDER_ID
   AND A.ORDER_ID = C.ORDER_ID
   AND A.ADD_TIME BETWEEN DATE '2018-11-11' AND DATE '2018-11-12';
