/*
 2.10月19-21日3天的唤醒数据
3.10月19-21日3天的唤醒数据   这个按19、20、21  3天总共
S_AGO_2_MONTH_LAST_DAY_KEY:早二个月的最后一天
S_AGO_3_MONTH_FIRST_DAY_KEY:早三个月的第一天
S_AGO_4_MONTH_LAST_DAY_KEY:早四个月的最后一天
*/
--1.
SELECT A.START_DATE_KEY, COUNT(DISTINCT(MEMBER_KEY)) WAKE_MEMBER_COUNT
  FROM FACT_SESSION A
 WHERE A.START_DATE_KEY BETWEEN 20181019 AND 20181021
   AND MEMBER_KEY IN
       (SELECT MEMBER_CRMBP FROM FACT_ECMEMBER WHERE MEMBER_TIME <= 20180630)
   AND MEMBER_KEY NOT IN
       (SELECT DISTINCT (MEMBER_KEY)
          FROM FACT_SESSION
         WHERE START_DATE_KEY BETWEEN 20180701 AND 20180831)
 GROUP BY A.START_DATE_KEY;
 
--2.
SELECT '合计', COUNT(DISTINCT(MEMBER_KEY)) WAKE_MEMBER_COUNT
  FROM FACT_SESSION A
 WHERE A.START_DATE_KEY BETWEEN 20181019 AND 20181021
   AND MEMBER_KEY IN
       (SELECT MEMBER_CRMBP FROM FACT_ECMEMBER WHERE MEMBER_TIME <= 20180630)
   AND MEMBER_KEY NOT IN
       (SELECT DISTINCT (MEMBER_KEY)
          FROM FACT_SESSION
         WHERE START_DATE_KEY BETWEEN 20180701 AND 20180831);
				 
				 
--tmp
SELECT TO_CHAR(LAST_DAY(ADD_MONTHS(TO_DATE(&IN_DATE_KEY, 'YYYYMMDD'), -2)),
               'YYYYMMDD')
  FROM DUAL;
 
 
 

