ALTER TABLE  DW_HAPPIGO.R_JOB_LOCK MOVE LOB (LOCK_MESSAGE) STORE AS (TABLESPACE EXDATA);

SELECT * FROM DBA_LOBS A WHERE A.TABLESPACE_NAME='DWDATA00';

SELECT *
  FROM DBA_EXTENTS A
 WHERE A.tablespace_name = 'DWDATA00'
   AND A.owner = 'DW_HAPPIGO'
   AND A.segment_type = 'INDEX';

ALTER INDEX SYS_C0033808 REBUILD TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX SYS_C0033772 REBUILD TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX SYS_C0033773 REBUILD TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX SYS_C0033774 REBUILD TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX SYS_C0033775 REBUILD TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX SYS_C0033777 REBUILD TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX SYS_C0033778 REBUILD TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX IDX_DATABASE_ATTRIBUTE_AK REBUILD TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX SYS_C0033780 REBUILD TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX SYS_C0033781 REBUILD TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX IDX_TRANS_ATTRIBUTE_LOOKUP REBUILD TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX IDX_TRANS_ATTRIBUTE_LOOKUP REBUILD TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX SYS_C0033782 REBUILD TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX IDX_JOB_ATTRIBUTE_LOOKUP REBUILD TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX SYS_C0033792 REBUILD TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX SYS_C0033795 REBUILD TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX SYS_C0033796 REBUILD TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX SYS_C0033797 REBUILD TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX IDX_STEP_ATTRIBUTE_LOOKUP REBUILD TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX IDX_STEP_DATABASE_LU1 REBUILD TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX IDX_STEP_DATABASE_LU2 REBUILD TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX SYS_C0033798 REBUILD TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX SYS_C0033800 REBUILD TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX SYS_C0033801 REBUILD TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX SYS_C0033802 REBUILD TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX SYS_C0033803 REBUILD TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX SYS_C0033804 REBUILD TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX IDX_JOBENTRY_ATTRIBUTE_LOOKUP REBUILD TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX SYS_C0033805 REBUILD TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;


SELECT 'ALTER INDEX ' || A.segment_name ||
       ' REBUILD TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;'
  FROM DBA_EXTENTS A
 WHERE A.tablespace_name = 'DWDATA00'
   AND A.owner = 'DW_HAPPIGO'
   AND A.segment_type = 'INDEX';

ALTER TABLE R_USER MOVE TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER TABLE R_REPOSITORY_LOG MOVE TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER TABLE R_VERSION MOVE TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER TABLE R_DATABASE_TYPE MOVE TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER TABLE R_DATABASE_CONTYPE MOVE TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER TABLE R_DATABASE MOVE TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER TABLE R_DATABASE_ATTRIBUTE MOVE TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER TABLE R_TRANSFORMATION MOVE TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER TABLE R_TRANS_ATTRIBUTE MOVE TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER TABLE R_TRANS_ATTRIBUTE MOVE TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER TABLE R_JOB_ATTRIBUTE MOVE TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER TABLE R_TRANS_HOP MOVE TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER TABLE R_STEP_TYPE MOVE TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER TABLE R_STEP MOVE TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER TABLE R_STEP_ATTRIBUTE MOVE TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER TABLE R_STEP_DATABASE MOVE TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER TABLE R_LOGLEVEL MOVE TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER TABLE R_JOB MOVE TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER TABLE R_JOBENTRY_TYPE MOVE TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER TABLE R_JOBENTRY MOVE TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER TABLE R_JOBENTRY_COPY MOVE TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER TABLE R_JOBENTRY_ATTRIBUTE MOVE TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER TABLE R_JOB_HOP MOVE TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;

SELECT 'ALTER TABLE ' || A.segment_name ||
       ' MOVE TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;'
  FROM DBA_EXTENTS A
 WHERE A.tablespace_name = 'DWDATA00'
   AND A.owner = 'DW_HAPPIGO'
   AND A.segment_type = 'TABLE';

SELECT *
  FROM DBA_INDEXES A
 WHERE A.tablespace_name = ''

  SELECT *
          FROM DBA_DATA_FILES A
         WHERE A.TABLESPACE_NAME = 'DWDATA00';


SELECT A.FILE_ID, COUNT(1)
  FROM DBA_EXTENTS A
 WHERE A.tablespace_name = 'DWDATA00'
 group by A.FILE_ID;

SELECT * FROM DBA_SEGMENTS A WHERE A.tablespace_name = 'DWDATA00';

ALTER INDEX FACT_VISITOR_REGISTER_VID REBUILD PARTITION VR5 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;

ALTER INDEX SYS_C0033772 REBUILD TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX SYS_C0033772 NOPARALLEL;

ALTER INDEX MR_DK REBUILD PARTITION MR1 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_HMK REBUILD PARTITION MR1 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_HDK REBUILD PARTITION MR1 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_HTK REBUILD PARTITION MR1 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_APK REBUILD PARTITION MR1 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_HDK REBUILD PARTITION MR2 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_DK REBUILD PARTITION MR2 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_APK REBUILD PARTITION MR2 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_HMK REBUILD PARTITION MR2 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_HTK REBUILD PARTITION MR2 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_APK REBUILD PARTITION MR3 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_HTK REBUILD PARTITION MR3 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_HDK REBUILD PARTITION MR3 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_HMK REBUILD PARTITION MR3 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_DK REBUILD PARTITION MR3 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_DK REBUILD PARTITION MR4 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_APK REBUILD PARTITION MR4 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_HDK REBUILD PARTITION MR4 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_HTK REBUILD PARTITION MR4 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_HMK REBUILD PARTITION MR4 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_HDK REBUILD PARTITION MR5 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_HTK REBUILD PARTITION MR5 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_DK REBUILD PARTITION MR5 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_HMK REBUILD PARTITION MR5 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_APK REBUILD PARTITION MR5 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_DK REBUILD PARTITION MR6 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_APK REBUILD PARTITION MR6 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_HMK REBUILD PARTITION MR6 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_HTK REBUILD PARTITION MR6 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_HDK REBUILD PARTITION MR6 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_APK REBUILD PARTITION MR7 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_HMK REBUILD PARTITION MR7 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_HTK REBUILD PARTITION MR7 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_HDK REBUILD PARTITION MR7 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_DK REBUILD PARTITION MR7 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;

ALTER INDEX MR_IGK REBUILD PARTITION MR1 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_IGK REBUILD PARTITION MR2 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_IGK REBUILD PARTITION MR3 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_IGK REBUILD PARTITION MR4 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_IGK REBUILD PARTITION MR5 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_IGK REBUILD PARTITION MR6 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_IGK REBUILD PARTITION MR7 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;

ALTER INDEX MR_MDK REBUILD PARTITION MR1 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_MDK REBUILD PARTITION MR2 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_MDK REBUILD PARTITION MR3 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_MDK REBUILD PARTITION MR4 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_MDK REBUILD PARTITION MR5 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_MDK REBUILD PARTITION MR6 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_MDK REBUILD PARTITION MR7 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;

ALTER INDEX MR_MID REBUILD PARTITION MR1 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_MID REBUILD PARTITION MR2 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_MID REBUILD PARTITION MR3 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_MID REBUILD PARTITION MR4 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_MID REBUILD PARTITION MR5 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_MID REBUILD PARTITION MR6 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_MID REBUILD PARTITION MR7 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;

ALTER INDEX MR_MK REBUILD PARTITION MR1 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_MK REBUILD PARTITION MR2 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_MK REBUILD PARTITION MR3 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_MK REBUILD PARTITION MR4 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_MK REBUILD PARTITION MR5 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_MK REBUILD PARTITION MR6 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_MK REBUILD PARTITION MR7 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;

ALTER INDEX MR_RDK REBUILD PARTITION MR1 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_RDK REBUILD PARTITION MR2 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_RDK REBUILD PARTITION MR3 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_RDK REBUILD PARTITION MR4 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_RDK REBUILD PARTITION MR5 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_RDK REBUILD PARTITION MR6 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_RDK REBUILD PARTITION MR7 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;

ALTER INDEX MR_RTK REBUILD PARTITION MR1 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_RTK REBUILD PARTITION MR2 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_RTK REBUILD PARTITION MR3 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_RTK REBUILD PARTITION MR4 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_RTK REBUILD PARTITION MR5 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_RTK REBUILD PARTITION MR6 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MR_RTK REBUILD PARTITION MR7 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;

ALTER INDEX FACT_MEMBER_REGISTER REBUILD PARTITION MR5 TABLESPACE EXDATA PARALLEL(DEGREE 4);
ALTER INDEX FACT_MEMBER_REGISTER REBUILD PARTITION MR6 TABLESPACE EXDATA PARALLEL(DEGREE 4);
ALTER INDEX FACT_MEMBER_REGISTER REBUILD PARTITION MR7 TABLESPACE EXDATA PARALLEL(DEGREE 4);
ALTER INDEX FACT_VISITOR_REGISTER_IP_INT REBUILD PARTITION VR4 TABLESPACE EXDATA PARALLEL(DEGREE 4);
ALTER INDEX FACT_VISITOR_REGISTER_IP_INT REBUILD PARTITION VR5 TABLESPACE EXDATA PARALLEL(DEGREE 4);

SELECT * from dba_segments a where a.segment_name = 'FACT_SESSION_FIST_IP';

ALTER INDEX FACT_SESSION_FIST_IP REBUILD PARTITION SESSIONP1 TABLESPACE EXDATA PARALLEL(DEGREE 4);

ALTER TABLE FACT_MEMBER_REGISTER MOVE PARTITION MR5 TABLESPACE BDUDATA00 PARALLEL(DEGREE 4) NOLOGGING;
ALTER TABLE FACT_MEMBER_REGISTER MOVE PARTITION MR6 TABLESPACE BDUDATA00 PARALLEL(DEGREE 4) NOLOGGING;
ALTER TABLE FACT_MEMBER_REGISTER MOVE PARTITION MR7 TABLESPACE BDUDATA00 PARALLEL(DEGREE 4) NOLOGGING;

ALTER INDEX FACT_SESSION_FIST_IP REBUILD PARTITION SESSIONP1 TABLESPACE EXDATA PARALLEL(DEGREE 4);
ALTER INDEX FACT_SESSION_FIST_IP REBUILD PARTITION SESSIONP2 TABLESPACE EXDATA PARALLEL(DEGREE 4);
ALTER INDEX FACT_SESSION_FIST_IP REBUILD PARTITION SESSIONP3 TABLESPACE EXDATA PARALLEL(DEGREE 4);
ALTER INDEX FACT_SESSION_FIST_IP REBUILD PARTITION SESSIONP4 TABLESPACE EXDATA PARALLEL(DEGREE 4);

ALTER INDEX FLAG_BLACK_IDX REBUILD TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX FLAG_BLACK_IDX NOPARALLEL;
ALTER INDEX MEMBER_LABEL_LINK_I5 REBUILD TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX MEMBER_LABEL_LINK_I5 NOPARALLEL;

ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201612 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201701 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201702 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201703 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201704 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201705 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201706 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201707 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201708 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201709 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201710 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201711 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201712 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201801 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201802 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201803 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201804 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201805 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201806 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201807 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201808 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201809 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201810 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201811 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201812 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201901 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201902 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201903 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201904 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201905 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201906 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201907 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201908 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201909 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201910 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201911 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P201912 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P202001 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P202002 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P202003 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P202004 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P202005 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P202006 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P202007 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P202008 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P202009 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P202010 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P202011 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P202012 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P202101 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P202102 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P202103 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P202104 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P202105 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P202106 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P202107 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P202108 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P202109 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P202110 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P202111 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P202112 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P202201 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P202202 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P202203 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P202204 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P202205 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P202206 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P202207 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P202208 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P202209 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P202210 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION P202211 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX DATA_ACQUISITION_ITEM_BASE_I1 REBUILD PARTITION PMAX TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;

ALTER INDEX FACT_VISITOR_REGISTER_I1 REBUILD PARTITION VR1 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX FACT_VISITOR_REGISTER_I1 REBUILD PARTITION VR2 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX FACT_VISITOR_REGISTER_I1 REBUILD PARTITION VR3 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX FACT_VISITOR_REGISTER_I1 REBUILD PARTITION VR4 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;
ALTER INDEX FACT_VISITOR_REGISTER_I1 REBUILD PARTITION VR5 TABLESPACE EXDATA PARALLEL(DEGREE 4) NOLOGGING;

SELECT * FROM TOAD_PLAN_TABLE;
