--1.
SELECT A.SALES_SOURCE_SECOND_NAME,
       SUM(A.EFFECTIVE_ORDER_AMOUNT) EFFECTIVE_ORDER_AMOUNT
  FROM OPER_PRODUCT_DAILY_REPORT A
 WHERE A.POSTING_DATE_KEY = 20180611
   AND A.SALES_SOURCE_NAME = '电商'
 GROUP BY A.SALES_SOURCE_SECOND_NAME;

--2.
SELECT A.ITEM_CODE, SUM(A.EFFECTIVE_ORDER_AMOUNT) EFFECTIVE_ORDER_AMOUNT
  FROM OPER_PRODUCT_DAILY_REPORT A
 WHERE A.POSTING_DATE_KEY = 20180611
   AND A.SALES_SOURCE_SECOND_NAME = '新媒体微信（2.0）'
 GROUP BY A.ITEM_CODE
 ORDER BY A.ITEM_CODE;

--3.
SELECT *
  FROM OPER_PRODUCT_DAILY_REPORT A
 WHERE A.POSTING_DATE_KEY = 20180611
   AND A.SALES_SOURCE_SECOND_NAME = '新媒体微信（2.0）'
   AND A.ITEM_CODE = 225508;

--4.
SELECT *
  FROM FACT_GOODS_SALES A
 WHERE A.ORDER_KEY = 5204819931
   AND A.GOODS_COMMON_KEY = 225508
   AND A.SALES_SOURCE_SECOND_DESC = 'A20021';

--5.
SELECT *
  FROM FACT_GOODS_SALES_REVERSE A
 WHERE A.ORDER_KEY = 5204819931
   AND A.GOODS_COMMON_KEY = 225508
   AND A.SALES_SOURCE_SECOND_DESC = 'A20021';

--6.
SELECT *
  FROM ODSHAPPIGO.ODS_ORDER A
 WHERE A.ZTCRMC04 = 5204819931
 ORDER BY A.CRM_OBJ_ID;

--7.
SELECT *
  FROM odshappigo.sap_bic_aztcrd00100 A
 WHERE A.CRM_OHGUID = 20171102260639;

--8.
SELECT * FROM ODSHAPPIGO.OD_ORDER_ITEM A WHERE A.ORDER_NO = 20171102260639;

--********************************************************************************
--fix
--********************************************************************************
--1.
BEGIN
  -- FACT_GOODS_SALES
  CREATEORDERGOODS(20171102);
  PROCESSUPDATEORDER(20171102);
END;
/

--2.
BEGIN
  -- OPER_PRODUCT_DAILY_REPORT
  YANGJIN_PKG.OPER_PRODUCT_DAILY_RPT(20180611);
END;
/


--3.
UPDATE ODSHAPPIGO.ODS_ORDER A
   SET A.ZCRMD018 =
       (SELECT ZCRMD018
          FROM (SELECT C.ZTCRMC04, MIN(C.ZCRMD018) ZCRMD018
                  FROM ODSHAPPIGO.ODS_ORDER C
                 WHERE C.ZCRMD018 IS NOT NULL
                 GROUP BY C.ZTCRMC04) B
         WHERE A.ZTCRMC04 = B.ZTCRMC04)
 WHERE A.ZCRMD018 IS NULL
   AND EXISTS (SELECT 1
          FROM (SELECT E.ZTCRMC04, MIN(E.ZCRMD018) ZCRMD018
                  FROM ODSHAPPIGO.ODS_ORDER E
                 WHERE E.ZCRMD018 IS NOT NULL
                 GROUP BY E.ZTCRMC04) D
         WHERE A.ZTCRMC04 = D.ZTCRMC04);
				 
--4.
SELECT *
  FROM ODSHAPPIGO.ODS_ORDER A
 WHERE A.ZCRMD018 IS NULL
   AND EXISTS (SELECT 1
          FROM (SELECT E.ZTCRMC04, MIN(E.ZCRMD018) ZCRMD018
                  FROM ODSHAPPIGO.ODS_ORDER E
									WHERE E.ZCRMD018 IS NOT NULL
                 GROUP BY E.ZTCRMC04) D
         WHERE A.ZTCRMC04 = D.ZTCRMC04);
				 
SELECT * FROM ODSHAPPIGO.ODS_ORDER A WHERE A.ZTCRMC04=5207490638;
SELECT * FROM ODSHAPPIGO.OD_ORDER_ITEM A WHERE A.ORDER_NO=20180326622768;
SELECT * FROM ODSHAPPIGO.OD_ORDER A WHERE A.ORDER_NO=20180326622768;

--********************************************************************************************************
--fix2
--********************************************************************************************************
--1.
BEGIN
  ODSHAPPIGO.OD_ORDER_ETL.INSERT_ODS_ORDER(20180326);
END;
/

--2.

--3.


