ALTER TABLE MEMBER_LABEL_LINK MOVE PARTITION M_LABEL_TYPE_ID_1 PARALLEL(DEGREE 4) NOLOGGING;
ALTER TABLE MEMBER_LABEL_LINK MOVE PARTITION M_LABEL_TYPE_ID_2 PARALLEL(DEGREE 4) NOLOGGING;
ALTER TABLE MEMBER_LABEL_LINK MOVE PARTITION M_LABEL_TYPE_ID_3 PARALLEL(DEGREE 4) NOLOGGING;
ALTER TABLE MEMBER_LABEL_LINK MOVE PARTITION M_LABEL_TYPE_ID_4 PARALLEL(DEGREE 4) NOLOGGING;

ALTER INDEX MEMBER_LABEL_LINK_I4 REBUILD PARALLEL (DEGREE 4) NOLOGGING;
ALTER INDEX MEMBER_LABEL_LINK_I4 NOPARALLEL;
ALTER INDEX MEMBER_LABEL_LINK_I5 REBUILD PARALLEL (DEGREE 4) NOLOGGING;
ALTER INDEX MEMBER_LABEL_LINK_I5 NOPARALLEL;

ALTER INDEX MEMBER_LABEL_LINK_I2 REBUILD PARTITION M_LABEL_TYPE_ID_1 PARALLEL (DEGREE 4) NOLOGGING;
ALTER INDEX MEMBER_LABEL_LINK_I2 REBUILD PARTITION M_LABEL_TYPE_ID_2 PARALLEL (DEGREE 4) NOLOGGING;
ALTER INDEX MEMBER_LABEL_LINK_I2 REBUILD PARTITION M_LABEL_TYPE_ID_3 PARALLEL (DEGREE 4) NOLOGGING;
ALTER INDEX MEMBER_LABEL_LINK_I2 REBUILD PARTITION M_LABEL_TYPE_ID_4 PARALLEL (DEGREE 4) NOLOGGING;

ALTER INDEX MEMBER_LABEL_LINK_I3 REBUILD PARTITION M_LABEL_TYPE_ID_1 PARALLEL (DEGREE 4) NOLOGGING;
ALTER INDEX MEMBER_LABEL_LINK_I3 REBUILD PARTITION M_LABEL_TYPE_ID_2 PARALLEL (DEGREE 4) NOLOGGING;
ALTER INDEX MEMBER_LABEL_LINK_I3 REBUILD PARTITION M_LABEL_TYPE_ID_3 PARALLEL (DEGREE 4) NOLOGGING;
ALTER INDEX MEMBER_LABEL_LINK_I3 REBUILD PARTITION M_LABEL_TYPE_ID_4 PARALLEL (DEGREE 4) NOLOGGING;





alter tablespace dwdata01 coalesce;
