/*
11-12月购买和加车（美食类 山货、干货、生鲜、原产，米面粮油类）商品的用户
*/
--订购
SELECT F.CUST_NO, F.ITEM_CNT
  FROM (SELECT TO_NUMBER(A.CUST_NO) CUST_NO,
               COUNT(DISTINCT B.ERP_CODE) ITEM_CNT
          FROM FACT_EC_ORDER_2 A, FACT_EC_ORDER_GOODS B
         WHERE A.ORDER_ID = B.ORDER_ID
           AND A.ADD_TIME BETWEEN DATE '2018-09-01' AND DATE
         '2018-12-31'
           AND A.ORDER_STATE >= 20
           AND A.CUST_NO <> 0
           AND EXISTS
         (SELECT 1
                  FROM (SELECT D.GOODS_COMMONID
                          FROM DIM_EC_GOOD D, DIM_GOOD_CLASS E
                         WHERE D.MATDL = E.MATDL
                           AND (E.MATZL IN (5105, 5106))) C
                 WHERE B.GOODS_COMMONID = C.GOODS_COMMONID)
         GROUP BY A.CUST_NO) F
 ORDER BY 2 DESC, 1;

--加车
SELECT A.MEMBER_KEY, COUNT(DISTINCT A.SCGID) ITEM_CNT
  FROM FACT_SHOPPINGCAR A
 WHERE A.CREATE_DATE_KEY BETWEEN 20180901 AND 20181231
   AND A.MEMBER_KEY <> 0
   AND EXISTS (SELECT 1
          FROM (SELECT C.GOODS_COMMONID
                  FROM DIM_EC_GOOD C, DIM_GOOD_CLASS D
                 WHERE C.MATKL = D.MATKL
                   AND (D.MATZL IN (5105, 5106))) B
         WHERE A.SCGID = B.GOODS_COMMONID)
 GROUP BY A.MEMBER_KEY
 ORDER BY 2 DESC, 1;

--tmp
/*
510502南北干货
5106生鲜食品
5105粮油调味
*/
SELECT * FROM DIM_GOOD_CLASS A WHERE A.MATDLT LIKE '%粮油%';
SELECT * FROM DIM_GOOD_CLASS A WHERE A.MATZLT LIKE '%粮油%';
SELECT * FROM DIM_GOOD_CLASS A WHERE A.MATXLT LIKE '%粮油%';
SELECT * FROM DIM_GOOD_CLASS A WHERE A.Matklt LIKE '%粮油%';
