--1.
SELECT DISTINCT A.APPLICATION_NAME
  FROM FACT_PAGE_VIEW A
 WHERE A.APPLICATION_KEY IS NULL
   AND A.VISIT_DATE_KEY = 20181005;

--2.
SELECT *
  FROM DIM_APPLICATION A
 WHERE A.APPLICATION_NAME IN
       ('wxlite_maill', 'KLGmgTV', 'KLGMProtal', 'KLGProtal');
--3.
DECLARE
  IN_DATE_INT NUMBER(8);
  IN_DATE     DATE;
  BEGIN_DATE  DATE := DATE '2018-12-01';
  END_DATE    DATE := DATE '2018-12-19';
BEGIN
  IN_DATE := BEGIN_DATE;
  WHILE IN_DATE <= END_DATE LOOP
    IN_DATE_INT := TO_CHAR(IN_DATE, 'YYYYMMDD');
    UPDATE FACT_PAGE_VIEW A
       SET A.APPLICATION_KEY = 30
     WHERE A.VISIT_DATE_KEY = IN_DATE_INT
       AND A.APPLICATION_KEY IS NULL
       AND A.APPLICATION_NAME = 'KLGMProtal';
    COMMIT;
    UPDATE FACT_PAGE_VIEW A
       SET A.APPLICATION_KEY = 40
     WHERE A.VISIT_DATE_KEY = IN_DATE_INT
       AND A.APPLICATION_KEY IS NULL
       AND A.APPLICATION_NAME = 'KLGProtal';
    COMMIT;
    UPDATE FACT_PAGE_VIEW A
       SET A.APPLICATION_KEY = 70
     WHERE A.VISIT_DATE_KEY = IN_DATE_INT
       AND A.APPLICATION_KEY IS NULL
       AND A.APPLICATION_NAME = 'wxlite_maill';
    COMMIT;
    UPDATE FACT_PAGE_VIEW A
       SET A.APPLICATION_KEY = 90
     WHERE A.VISIT_DATE_KEY = IN_DATE_INT
       AND A.APPLICATION_KEY IS NULL
       AND A.APPLICATION_NAME = 'KLGmgTV';
    COMMIT;
    IN_DATE := IN_DATE + 1;
  END LOOP;
END;
/
