/*
订购和访问频次：17-21，按会员等级，捞取 访问频次和订购频次。订购频次就是17-21号订购次数，访问频次不捞取访问次数，而是捞取17-21号访问过的天数。
*/
--访问天数
SELECT D.MEMBER_LEVEL, D.DAYS, COUNT(1)
  FROM (SELECT C.MEMBER_LEVEL, C.MEMBER_KEY, COUNT(1) DAYS
          FROM (SELECT DISTINCT A.MEMBER_KEY,
                                A.VISIT_DATE_KEY,
                                B.MEMBER_LEVEL
                  FROM FACT_PAGE_VIEW A, DIM_MEMBER B
                 WHERE A.MEMBER_KEY = B.MEMBER_BP
                   AND A.VISIT_DATE_KEY BETWEEN 20180817 AND 20180821
                   AND A.MEMBER_KEY <> 0
                   AND B.MEMBER_LEVEL IS NOT NULL) C
         GROUP BY C.MEMBER_LEVEL, C.MEMBER_KEY) D
 GROUP BY D.MEMBER_LEVEL, D.DAYS
 ORDER BY D.MEMBER_LEVEL, D.DAYS;

--订购频次
SELECT C.MEMBER_LEVEL, COUNT(C.ORDER_ID)
  FROM (SELECT B.MEMBER_LEVEL, B.MEMBER_BP, A.ORDER_ID
          FROM FACT_EC_ORDER_2 A, DIM_MEMBER B
         WHERE A.CUST_NO = B.MEMBER_BP
           AND B.MEMBER_LEVEL IS NOT NULL
           AND A.ORDER_STATE >= 20
           AND TO_CHAR(A.ADD_TIME, 'YYYYMMDD') BETWEEN 20180817 AND 20180821) C
 GROUP BY C.MEMBER_LEVEL
 ORDER BY C.MEMBER_LEVEL;
