--1.
/*DROP TABLE YANGJIN.EMP;
CREATE TABLE YANGJIN.EMP(EMP_NO NUMBER(10),EMP_NAME VARCHAR2(10),WV NUMBER);
DROP TABLE YANGJIN.EMP_DUTY;
CREATE TABLE YANGJIN.EMP_DUTY(EMP_NO NUMBER(10),DUTY_DATE DATE,WEEK VARCHAR2(10));*/

SELECT * FROM YANGJIN.EMP FOR UPDATE;

SELECT * FROM YANGJIN.EMP;
SELECT * FROM YANGJIN.EMP_DUTY;

SELECT A.EMP_NO,
       A.EMP_NAME,
       B.DUTY_DATE,
       B.WEEK,
       B.DUTY_DATE - LAG(B.DUTY_DATE) OVER(PARTITION BY B.EMP_NO ORDER BY B.DUTY_DATE) LAST_DUTY_DATE
  FROM YANGJIN.EMP A, YANGJIN.EMP_DUTY B
 WHERE A.EMP_NO = B.EMP_NO
   AND B.DUTY_DATE BETWEEN DATE '2018-01-01' AND DATE '2018-12-31'
--AND A.EMP_NAME = '杨进'
 ORDER BY B.DUTY_DATE;

--周六周日
SELECT C.EMP_NO, C.EMP_NAME, C.WEEK, COUNT(1) DAYS
  FROM (SELECT A.EMP_NO, A.EMP_NAME, B.DUTY_DATE, B.WEEK
          FROM YANGJIN.EMP A, YANGJIN.EMP_DUTY B
         WHERE A.EMP_NO = B.EMP_NO
           AND B.DUTY_DATE BETWEEN DATE '2018-01-01' AND DATE
         '2018-12-31'
           AND UPPER(B.WEEK) IN ('星期六', '星期日')) C
 GROUP BY C.EMP_NO, C.EMP_NAME, C.WEEK
 ORDER BY C.EMP_NO, C.EMP_NAME, C.WEEK;

--周末
SELECT C.EMP_NO, C.EMP_NAME, COUNT(1) DAYS
  FROM (SELECT A.EMP_NO, A.EMP_NAME, B.DUTY_DATE, B.WEEK
          FROM YANGJIN.EMP A, YANGJIN.EMP_DUTY B
         WHERE A.EMP_NO = B.EMP_NO
           AND B.DUTY_DATE BETWEEN DATE '2018-01-01' AND DATE
         '2018-12-31'
           AND UPPER(B.WEEK) IN ('星期六', '星期日')) C
 GROUP BY C.EMP_NO, C.EMP_NAME
 ORDER BY COUNT(1) DESC, C.EMP_NO;

--值班天数
SELECT C.EMP_NO, C.EMP_NAME, COUNT(1) DAYS
  FROM (SELECT A.EMP_NO, A.EMP_NAME, B.DUTY_DATE, B.WEEK
          FROM YANGJIN.EMP A, YANGJIN.EMP_DUTY B
         WHERE A.EMP_NO = B.EMP_NO
           AND B.DUTY_DATE BETWEEN DATE '2018-01-01' AND DATE
         '2018-12-31') C
 GROUP BY C.EMP_NO, C.EMP_NAME
 ORDER BY COUNT(1) DESC, C.EMP_NO;

UPDATE YANGJIN.EMP A SET A.WV = NULL;
COMMIT;
TRUNCATE TABLE YANGJIN.EMP_DUTY;

--2.
/*
(0.9 ,19,26)
(0.95,19,26)
*/
DECLARE
  V_EMP_COUNT       NUMBER;
  V_DUTY_EMP_NO     NUMBER(10);
  V_CURRENT_WV      NUMBER;
  V_WEEK            VARCHAR2(10);
  V_DUTY_DATE       DATE;
  V_BEGIN_DUTY_DATE DATE := DATE '2010-01-01';
  V_END_DUTY_DATE   DATE := DATE '2020-12-31';
  V_MONDAY_VALUE    NUMBER := 0.9;
  V_TUESDAY_VALUE   NUMBER := V_MONDAY_VALUE;
  V_WEDNESDAY_VALUE NUMBER := V_MONDAY_VALUE;
  V_THURSDAY_VALUE  NUMBER := V_MONDAY_VALUE;
  V_FRIDAY_VALUE    NUMBER := V_MONDAY_VALUE;
  V_SATURDAY_VALUE  NUMBER := (7 - V_MONDAY_VALUE * 5) / 2;
  V_SUNDAY_VALUE    NUMBER := (7 - V_MONDAY_VALUE * 5) / 2;
BEGIN
  UPDATE YANGJIN.EMP A SET A.WV = NULL;
  COMMIT;
  EXECUTE IMMEDIATE 'TRUNCATE TABLE YANGJIN.EMP_DUTY';

  SELECT COUNT(1) INTO V_EMP_COUNT FROM YANGJIN.EMP;
  V_DUTY_DATE := V_BEGIN_DUTY_DATE;
  WHILE V_DUTY_DATE <= V_END_DUTY_DATE LOOP
    V_WEEK := TRIM(TO_CHAR(V_DUTY_DATE,
                           'DAY',
                           'NLS_DATE_LANGUAGE=''SIMPLIFIED CHINESE'''));
    /*每天+1*/
    UPDATE YANGJIN.EMP A SET A.WV = NVL(A.WV, 0) + 1;
    COMMIT;
    /*权重值最小的值班，如果权重值一样，则员工号最小的先值班*/
    SELECT A.EMP_NO, A.WV
      INTO V_DUTY_EMP_NO, V_CURRENT_WV
      FROM (SELECT B.EMP_NO,
                   B.WV,
                   ROW_NUMBER() OVER(ORDER BY B.WV DESC, B.EMP_NO) RN
              FROM YANGJIN.EMP B) A
     WHERE A.RN = 1;
  
    /*值班的减去权重值*/
    UPDATE YANGJIN.EMP A
       SET A.WV = NVL(A.WV, 0) -
                  DECODE(V_WEEK,
                         '星期一',
                         V_MONDAY_VALUE * V_EMP_COUNT,
                         '星期二',
                         V_TUESDAY_VALUE * V_EMP_COUNT,
                         '星期三',
                         V_WEDNESDAY_VALUE * V_EMP_COUNT,
                         '星期四',
                         V_THURSDAY_VALUE * V_EMP_COUNT,
                         '星期五',
                         V_FRIDAY_VALUE * V_EMP_COUNT,
                         '星期六',
                         V_SATURDAY_VALUE * V_EMP_COUNT,
                         '星期日',
                         V_SUNDAY_VALUE * V_EMP_COUNT)
     WHERE A.EMP_NO = V_DUTY_EMP_NO;
    COMMIT;
    /*插入值班表*/
    INSERT INTO YANGJIN.EMP_DUTY
      (EMP_NO, DUTY_DATE, WEEK, CURRENT_WV)
    VALUES
      (V_DUTY_EMP_NO, V_DUTY_DATE, LOWER(V_WEEK), V_CURRENT_WV);
    COMMIT;
    V_DUTY_DATE := V_DUTY_DATE + 1;
  END LOOP;
END;
