--Size  389 GB
ALTER TABLE FACT_PAGE_VIEW ENABLE ROW MOVEMENT;
ALTER TABLE FACT_PAGE_VIEW SHRINK SPACE;
ALTER TABLE FACT_PAGE_VIEW DISABLE ROW MOVEMENT;
BEGIN
  DBMS_STATS.GATHER_TABLE_STATS(OWNNAME => 'DW_USER',
                                TABNAME => 'FACT_PAGE_VIEW',
                                DEGREE  => 4,
                                CASCADE => TRUE);
END;

SELECT *
  FROM W_ETL_LOG A
 WHERE A.PROC_NAME = 'YJ_OPTIMIZATION.TABLE_OPTIMIZATION'
 ORDER BY A.START_TIME DESC;


