select * from kpi_asmt_app_item_cvr;
select * from KPI_ASMT_WX_NEW_REG t;
truncate table KPI_ASMT_WX_NEW_REG;
SELECT * FROM ALL_SOURCE A WHERE UPPER(A.TEXT) LIKE '%INSERT%FACT_DAILY_WX%';
PROCESSWXDAILY;
select *
  from OPER_NM_PROMOTION_ITEM_REPORT t
 WHERE T.ORDER_SN = '630570483402375016';
select *
  from OPER_NM_PROMOTION_ORDER_REPORT t
 WHERE T.ORDER_SN = '630570483402375016';
select * from OPER_NM_VOUCHER_REPORT t where t.voucher_title = '129¼õ10';
select * from FACT_EC_ORDER_2 t WHERE T.ORDER_SN = '630570483402375016';
SELECT * FROM FACT_EC_P_MANSONG T WHERE T.MANSONG_ID = 235;
SELECT * FROM OPER_NM_VOUCHER_REPORT A WHERE A.voucher_title = '129¼õ10';

TRUNCATE TABLE OPER_NM_VOUCHER_REPORT;
begin
  -- Call the procedure
  yangjin_pkg.oper_nm_voucher_rpt;
end;
/

DECLARE IN_DATE_INT NUMBER(8);
IN_DATE DATE;
BEGIN_DATE DATE := DATE '2018-01-01';
END_DATE DATE := DATE '2018-03-07';
BEGIN
  IN_DATE := LAST_DAY(BEGIN_DATE);
  WHILE IN_DATE <= END_DATE LOOP
    IN_DATE_INT := TO_CHAR(IN_DATE, 'YYYYMMDD');
    YANGJIN_PKG.OPER_NM_PROMOTION_ITEM_RPT(IN_DATE_INT);
    YANGJIN_PKG.OPER_NM_PROMOTION_ORDER_RPT(IN_DATE_INT);
    IN_DATE := LAST_DAY(IN_DATE + 1);
  END LOOP;
END;
/

  select -34.84 + 14.68 from dual;

SELECT * FROM ALL_ALL_TABLES;
select A.OWNER, A.segment_name, A.bytes / 1024 / 1024 from DBA_segments A;
SELECT a.owner, a.table_name, a.num_rows * a.avg_row_len/1024/1024/1024 G
  FROM ALL_ALL_TABLES a;

SELECT * FROM ODSHAPPIGO.ODS_PAGEVIEW;
SELECT * FROM ODS_PAGEVIEW;
