SELECT * FROM MEMBER_FILTER_OPTION_HEAD;

SELECT MIN(A.FILTER_ID)
  --INTO V_TABLE_HEAD.FILTER_ID
  FROM MEMBER_FILTER_OPTION_HEAD A
 WHERE (A.MEMBER_LABEL_ID_SET IS NOT NULL OR A.ITEM_CODE_SET IS NOT NULL OR
       A.BRAND_SET IS NOT NULL OR A.MATXL_SET IS NOT NULL) /*如果会员标签、商品编码、品牌、小类编码都为空，则不执行*/
   AND A.STATUS = 0;
