SELECT * FROM W_ETL_LOG A ORDER BY A.START_TIME DESC;

/*
processstatvtminute
processstatvtminute5
processstatvtminute30
*/

SELECT B.VISIT, B.APPLICATION_KEY, COUNT(DISTINCT B.VID) VID_CNT
  FROM (SELECT TRUNC(A.VISIT_DATE, 'MI') VISIT, A.APPLICATION_KEY, A.VID
          FROM FACT_PAGE_VIEW A
         WHERE A.VISIT_DATE_KEY = 20181206
         GROUP BY TRUNC(A.VISIT_DATE, 'MI'), A.APPLICATION_KEY, A.VID) B
 GROUP BY B.VISIT, B.APPLICATION_KEY
 ORDER BY B.VISIT, B.APPLICATION_KEY;

SELECT A.VISIT_DATE, TRUNC(A.VISIT_DATE, 'MI')
  FROM FACT_PAGE_VIEW A
 WHERE A.VISIT_DATE_KEY = 20181206;

SELECT *
  FROM FACT_PAGE_VIEW A
 WHERE A.VISIT_DATE_KEY = 20181206
   AND A.APPLICATION_KEY IS NULL;

SELECT *
  FROM FACT_PAGE_VIEW A
 WHERE A.VISIT_DATE_KEY = 20181206
   AND A.APPLICATION_KEY = -1;

SELECT A.VISIT_DATE_KEY, COUNT(1)
  FROM FACT_PAGE_VIEW A
 WHERE A.VISIT_DATE_KEY >= 20181201
   AND A.APPLICATION_KEY IS NULL
 GROUP BY A.VISIT_DATE_KEY
 ORDER BY A.VISIT_DATE_KEY;

PROCESSPVAPPLICATION

  SELECT *
    FROM FACT_PAGE_VIEW A
   WHERE A.VISIT_DATE_KEY >= 20181201
     AND A.APPLICATION_NAME = 'KLGMProtal';

SELECT *
  FROM ALL_SOURCE A
 WHERE UPPER(A.TEXT) LIKE '%UPDATE%FACT_PAGE_VIEW%'
 ORDER BY A.OWNER, A.name;

SELECT *
  FROM W_ETL_LOG A
 WHERE A.PROC_NAME = 'processpvapplication'
 ORDER BY A.START_TIME DESC;
--wxlite_mall
select * from DIM_APPLICATION t WHERE T.APPLICATION_KEY = 70;

select * from DIM_APPLICATION A ORDER BY A.ID FOR UPDATE;

INSERT INTO DIM_APPLICATION
  (ID,
   APPLICATION_KEY,
   APPLICATION_NAME,
   CREATE_DATE,
   APPLICATION__CN_NAME,
   CHANNEL_KEY,
   CHANNEL_NAME)
VALUES
  (22, 70, 'wxlite_mall', SYSDATE, '快乐购小程序', 7, '快乐购小程序');

SELECT A.VISIT_DATE_KEY, COUNT(1)
  FROM FACT_PAGE_VIEW A
 WHERE A.VISIT_DATE_KEY >= 20180101
   AND A.APPLICATION_KEY IS NULL
 GROUP BY A.VISIT_DATE_KEY
 ORDER BY A.VISIT_DATE_KEY;

update fact_page_view c
   set c.application_key =
       (select d.application_key
          from dim_application d
         where d.application_name = c.application_name),
       c.channel_key    =
       (select e.channel_key
          from dim_application e
         where e.application_name = c.application_name)
 where c.visit_date_key = 20181130
   and c.application_key is null;
commit;

SELECT *
  FROM FACT_PAGE_VIEW A
 WHERE A.VISIT_DATE_KEY = 20181207
   AND A.APPLICATION_NAME = 'KLGMProtal'
 ORDER BY A.VISIT_DATE DESC;


SELECT COUNT(1) FROM TMP_TOPIC_GOODS;

INSERT INTO TMP_TOPIC_GOODS
  SELECT W1.TITLE,
         W6.GOODS_COMMONID,
         W6.GOODS_NAME,
         W2.APPLICATION_KEY,
         'hdact' AS ZTTYPE,
         W2.VISIT_DATE_KEY
    FROM G_ACTIVITY W1,
         (SELECT DISTINCT R1.PAGE_NAME,
                          R1.PAGE_VALUE,
                          R1.APPLICATION_KEY,
                          R1.VISIT_DATE_KEY
            FROM FACT_PAGE_VIEW R1
           WHERE R1.VISIT_DATE_KEY = 20181206
             AND R1.PAGE_NAME = 'hdact') W2,
         (SELECT DISTINCT W3.ID_COL, W3.ACTIVITY_ID
            FROM G_ACTIVITY_GOODS_GROUP W3) W5,
         G_ACTIVITY_GOODS W6
   WHERE W1.KEY_SOURCE = W2.PAGE_VALUE
     AND W1.ID_COL = W5.ACTIVITY_ID
     AND W5.ID_COL = W6.GROUP_ID;
