/*
11/29-11/30两天订购总金额
*/
--1.
TRUNCATE TABLE YANGJIN.MEMBER_TMP;
SELECT * FROM YANGJIN.MEMBER_TMP FOR UPDATE;

--2.订购
SELECT SUM(F.ORDER_AMOUNT)
  FROM (SELECT TO_NUMBER(A.CUST_NO) MEMBER_BP,
               SUM(A.ORDER_AMOUNT) ORDER_AMOUNT,
               COUNT(DISTINCT A.ORDER_ID) ORDER_CNT
          FROM FACT_EC_ORDER_2 A, FACT_EC_ORDER_GOODS B
         WHERE A.ORDER_ID = B.ORDER_ID
           AND A.ADD_TIME BETWEEN DATE '2018-11-29' AND DATE
         '2018-12-01'
           AND A.ORDER_STATE >= 20
           AND A.CUST_NO <> 0
           AND EXISTS (SELECT 1
                  FROM YANGJIN.MEMBER_TMP C
                 WHERE A.CUST_NO = C.MEMBER_KEY)
         GROUP BY A.CUST_NO) F;
 
SELECT DISTINCT A.ADD_TIME
  FROM FACT_EC_ORDER_2 A
 WHERE A.ADD_TIME BETWEEN DATE '2018-11-29' AND DATE '2018-12-01'
 ORDER BY A.ADD_TIME;
