--CRM_ORDER_NO
CREATE TABLE CRM_ORDER_NO_TMP  (CRM_ORDER_NO NUMBER(15));

TRUNCATE TABLE CRM_ORDER_NO_TMP;

SELECT * FROM CRM_ORDER_NO_TMP FOR UPDATE;

SELECT A.CRM_ORDER_NO,
       CASE
         WHEN B.ORDER_FROM = '76' THEN
          '是'
         ELSE
          '否'
       END 是否扫码购
  FROM CRM_ORDER_NO_TMP A, FACT_EC_ORDER_2 B
 WHERE A.CRM_ORDER_NO = B.CRM_ORDER_NO(+);

--ITEM_CODE 
CREATE TABLE ITEM_CODE_TMP (ITEM_CODE NUMBER(11));

TRUNCATE TABLE ITEM_CODE_TMP;

SELECT * FROM ITEM_CODE_TMP FOR UPDATE;

SELECT A.ITEM_CODE,
       CASE
         WHEN B.STORE_ID = 1 AND B.IS_TV = 0 THEN
          '是'
         ELSE
          '否'
       END 是否自营商品
  FROM ITEM_CODE_TMP A, DIM_EC_GOOD B
 WHERE SUBSTR(A.ITEM_CODE, 1, 6) = B.ITEM_CODE(+);

--TMP
SELECT * FROM FACT_EC_ORDER_2 A WHERE TRUNC(A.ADD_TIME)=DATE'2018-03-22';
SELECT DISTINCT LENGTH(A.ITEM_CODE) FROM DIM_EC_GOOD A;
SELECT * FROM DIM_EC_GOOD;
SELECT DISTINCT LENGTH(A.ITEM_CODE) FROM DIM_GOOD A;
