--1.
create table YANGJIN.M_SOURCE_TAB
(
  rid   NUMBER(10) not null,
  names VARCHAR2(30)
);

alter table YANGJIN.M_SOURCE_TAB
  add constraint M_SOURCE_TAB_PK primary key (RID);

--2.
CREATE MATERIALIZED VIEW LOG ON YANGJIN.M_SOURCE_TAB WITH PRIMARY KEY;

--3.
DROP MATERIALIZED VIEW YANGJIN.M_TARGET_MV;
CREATE MATERIALIZED VIEW YANGJIN.M_TARGET_MV 
(RID,NAMES) 
REFRESH FAST ON DEMAND    
WITH PRIMARY KEY                
AS 
SELECT RID, NAMES FROM YANGJIN.M_SOURCE_TAB;

--4.
INSERT INTO YANGJIN.M_SOURCE_TAB VALUES(1,'AAA');
COMMIT;
INSERT INTO YANGJIN.M_SOURCE_TAB VALUES(2,'BBB');
COMMIT;

--5.
SELECT * FROM MLOG$_M_SOURCE_TAB;

--6.
CALL DBMS_MVIEW.refresh('M_TARGET_MV','FAST');
CALL DBMS_MVIEW.refresh('M_TARGET_MV','C');

--7.
TRUNCATE TABLE YANGJIN.M_SOURCE_TAB;

SELECT * FROM YANGJIN.M_SOURCE_TAB;
SELECT * FROM YANGJIN.M_TARGET_MV ;

--8.
MERGE /*+APPEND*/
INTO YANGJIN.M_SOURCE_TAB T
USING (SELECT 2 RID, 'ABC' NAMES
         FROM DUAL
       UNION ALL
       SELECT 3 RID, 'CCC' NAMES
         FROM DUAL) S
ON (T.RID = S.RID)
WHEN MATCHED THEN
  UPDATE SET T.NAMES = S.NAMES
WHEN NOT MATCHED THEN
  INSERT (T.RID, T.NAMES) VALUES (S.RID, S.NAMES);
COMMIT;
