/*
食品自营目前在架的直配送商品清单
商品编号  商品名称 库存数量  供应商编号 供应商名称 MD编号
*/
SELECT A.ITEM_CODE,
       A.GOODS_NAME,
       A.STOCK_NUMS,
       A.SUPPLIER_ID,
       A.SUPPLIER_NAME,
       A.MD
  FROM FACT_GOODS_DIM_TOTAL A
 WHERE A.DELIVERY_KEY = 1
   AND A.ZJ_STATE = 1;


--TMP
SELECT D.ITEM_CODE,
       D.GOODS_NAME,
       F.GOODS_STOCK,
       D.SUPPLIER_ID,
       D.SUPPLIER_NAME,
       E.MD
  FROM (SELECT A.ITEM_CODE, A.GOODS_NAME, A.SUPPLIER_ID, A.SUPPLIER_NAME
          FROM DIM_EC_GOOD A
         WHERE A.IS_SHIPPING_SELF = 1) D,
       (SELECT B.ITEM_CODE, B.MD FROM DIM_GOOD B) E,
       (SELECT C.ITEM_CODE, C.GOODS_STOCK FROM FACT_ECGOODS_STOCK C) F
 WHERE D.ITEM_CODE = E.ITEM_CODE
   AND D.ITEM_CODE = F.ITEM_CODE;
SELECT * FROM FACT_ECGOODS_STOCK;
SELECT * FROM DIM_EC_GOOD;
SELECT * FROM DIM_GOOD;
SELECT * FROM FACT_GOODS_DIM_TOTAL;

SELECT A.ITEM_CODE, A.GOODS_NAME, A.SUPPLIER_ID, A.SUPPLIER_NAME
  FROM DIM_EC_GOOD A
 WHERE A.IS_SHIPPING_SELF = 1;
SELECT B.ITEM_CODE, B.MD FROM DIM_GOOD B;
SELECT C.ITEM_CODE, C.GOODS_STOCK FROM FACT_ECGOODS_STOCK C;
SELECT * FROM DIM_EC_GOOD A WHERE A.ITEM_CODE = 109652;
SELECT * FROM DIM_GOOD A WHERE A.ITEM_CODE = 109652;
SELECT A.ITEM_CODE, COUNT(1)
  FROM DIM_EC_GOOD A
 GROUP BY A.ITEM_CODE
HAVING COUNT(1) > 1;
SELECT * FROM ALL_COL_COMMENTS A WHERE A.COMMENTS LIKE '%在架%';
SELECT * FROM ALL_COL_COMMENTS A WHERE A.COLUMN_NAME = 'SUPPLIER_NAME';
